### ISSUE TITLE
[RFC] Split Server-Tools for v11

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#1006]
[Bringing this in from a mailing list thread for final discussion.](https://odoo-community.org/groups/tools-22/tools-44031?mode=thread)

From @dreispt (there's more in the thread, but this is the one that's still relevant right now and should be discussed):

> Hello,
>
> I believe that the repo can be subdivided in several more focused ones.
>
> I propose to keep OCA/serverl-tools mostly for features related to configuration and administration tasks.
> The other features can be moved to a few new spinf-off repos.
> 
> I can think of four new repos to create as spin-offs:
> - OCA/server-auth (10 modules): Authentication related
> - OCA/server-backend (5 modules): Server ORM extensions, new fields
> - OCA/server-brand (8 modules and counting): (De)branding related
> - OCA/server-ux (11 modules): Server side features for usability and user experience related
>
> Supporting the above division, and as a starting point for the discussion, I prepared this spreadsheet:
https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit?usp=sharing

cc @pedrobaeza @hbrunn @OCA/board

**Comment by dreispt** [comment]
Bringing up this again was on my list, thanks a lot for bringing it up Dave.
Experience tells us that focused repositories have better direction and more motivated maintainers.
This repository covers too much different topics for it to be effectively maintained.
It also has signs of being too large, looking at the number of existing modules and open PRs.

The list spinoffs proposed is quite old, so they might need an update.

**Comment by JordiBForgeFlow** [comment]
@dreispt I do not see consensus, and at the same time I see that the PR's to v11 are occurring as we speak. I propose to defer this topic until v12, as it seems that this kind of structural changes need to be planned well in advance of a new release.

**Comment by elicoidal** [comment]
Unfortunately I have to agree that this conversation is starting too late: we need to plan now the repository structure for v12 NOW.

**Comment by JordiBForgeFlow** [comment]
OK, I have renamed the issue accordingly.

**Comment by pedrobaeza** [comment]
No, it can be perfectly done in v11, and more as repo has been emptied. I'm creating the repos next day.

**Comment by lasley** [comment]
I brought this topic up back in ~~June~~ August. My standpoint is that we should do it now or it will never get done.

**Comment by JordiBForgeFlow** [comment]
If @pedrobaeza creates the repos then it is ok. We have some PR's pending to merge to v11, and we'll wait until he is done to decide where to put them.

**Comment by dreispt** [comment]
@jbeficent It is not too late, the v11 branches are still empty.
AFAICR there was no opposition to this move, it just wasn't implemented.
Maybe @lasley has a link for the discussion.

**Comment by JordiBForgeFlow** [comment]
@dreispt no problem. We are so eager to start pushing to v11!!! I will wait for @pedrobaeza

**Comment by pedrobaeza** [comment]
I'm on it!

**Comment by pedrobaeza** [comment]
OK, I have created all the new repositories. You can start pushing to them. Closing this issue and including the document with the mapping on the migration issue.

**Comment by JordiBForgeFlow** [comment]
Thanks!!

**Comment by gurneyalex** [comment]
thanks @lasley and @pedrobaeza

**Comment by hbrunn** [comment]
do we also want to ask people proposing new modules to server-tools in lower versions to move their PRs there? Would make sense imho
(edit: Of course only unmerged PRs that really introduce a new module)

**Comment by pedrobaeza** [comment]
Well, I haven't created branches for lower versions, but if you think it's interesting, then go ahead.

**Comment by elicoidal** [comment]
Shall we advertise it in the contributor ML?

**Comment by pedrobaeza** [comment]
Yeah, it can be interesting. And it should be part of next newsletter.

**Comment by hbrunn** [comment]
first time I review such a PR I'll create the branch - don't see a reason to do that beforehand now

**Comment by pedrobaeza** [comment]
OK, agreed

**Comment by lasley** [comment]
> And it should be part of next newsletter.

I created a ticket so we don't forget for the newsletter. Good idea

**Comment by dreispt** [comment]
To help people with what goes where, we should have v11 migration issues with the list of modules excepted to be migrated on each of the repos.

**Comment by dreispt** [comment]
Regrading the ML communication, it should done asap. In the next newsletter we will also mention that, with a link to the ML message.
