### ISSUE TITLE
Framework Module for Materialized view

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-tools#101]
Hi all, 

I recently discovered a new concept in PostgreSQL, the materialized views. I so experimented this tools in a custom modules. (You can read the code [here](https://github.com/grap/odoo-addons-misc/tree/7.0/pos_sale_reporting/model) )
I would like to refactor the class materialized_view and share it into an OCA Module.

As it will be a 'framework' module, I don't know if 'server-tools' is the best repository. What is your point of view ? Do you think it could interest some of you ?

For people who don't know what it is, the materialized view is a computed view. It is defined like a standard view, but a real table is generated. So the data are accessible faster. On the other side, the data are not up to date, and the materialized view must be 'refreshed' regularly.
This is usefull for reports in dashboard, and specially if the view uses "UNION" request.
In the case of my custom module I want to merge 'sale' and 'POS' orders information. With a medium sized database, (PO : 120k ; SO : 10k ):
- without materialized view : request : ~ 50 sec;
- with materialized view : request : < 1sec; refresh duration : ~ 60 sec; (each night)

I would like to create a (V7) module that : 
[x] manage this new kind of Model;
[x] check if the postgres version is compatible . (need PG 9.3 +)
[x] propose functions to refresh the view;
[x] create a cron task that must be configured after, to indicate the frequence of the refresh;
[ ] Display to the user the date of the last refresh; ('web' changes);

**Comment by bwrsandman** [comment]
Sounds interesting. Keep us posted!

**Comment by pedrobaeza** [comment]
You should join efforts with Anybox to build a powerful one with the best of both modules: https://bitbucket.org/anybox/materialized_sql_view/.

**Comment by legalsylvain** [comment]
I close My issues as AnyBox added the PR #110.

Thanks for your remarks.
