### ISSUE TITLE
[RFC] base_user_gravatar: use ui-avatars.com as fallback

### ISSUE THREAD

**Issue by naglis** [OCA/server-tools#1016]
Hey,

saw this service on HN: [ui-avatars.com](https://ui-avatars.com/) - they allow to get an avatar with user's initials. What is nice is their URL can be passed to Gravatar.com as a fallback in case a user with given email does not have a Gravatar set.

### Considerations
* Does this idea sound good to others?
* What if the service is short-lived (in which case we would simply get no fallback)?
* If yes, do we adapt _base_user_gravatar_ to allow extending and put this into a separate addon, or just extend _base_user_gravatar_?
* They provide size/background/color/length/font-size/rounded customization - which of these (apart from size) do we want the user to be able to configure and how/where?
* Although they state _No usage tracking and no information is stored._, I suggest we simply pass first letters of each name part in user's name?

CC @Endika @lasley

**Comment by lasley** [comment]
Interesting idea @naglis - I like the idea of a fallback avatar. 

I wonder though - this is fairly simple to do in code vs. using an external service. Odoo already does something like it with the colored partner avatars. Have you played with this at all?

Regarding whether it should be an extension - that would probably be best yeah. I could see some instances in which this could be undesirable, although most of the ones I can think of are security related and why would a security conscious company be using Gravatar?

Configuration at the user level is probably a bit much. We could maybe sprinkle in a bit of randomization though, maybe add a tilt here and there or something.

**Comment by naglis** [comment]
Thanks for the feedback @lasley.

I haven't attempted anything with code yet (knowing my artistic abilities, I'd most likely bodge it). I guess something [similar to this](https://github.com/odoo/odoo/blob/10.0/addons/web_editor/controllers/main.py#L76-L134) might work. I'll give it a try.

**Comment by LasseRafn** [comment]
The api and underlying code is also open source if you dont like relying on third party 👍
