### ISSUE TITLE
[8.0] users_ldap_push - Encoding error when trying to add LDAP values containing Unicode characters

### ISSUE THREAD

**Issue by diggy128** [OCA/server-tools#1031]
LDAP server: OpenLDAP
How to reproduce: Setup users_ldap_push module and try to change the user's display name to a unicode string such as "Δημήτριος", or create a user with a name containing unicode characters.
Happens every time: Yes
Method that exposes the error: _get_ldap_values

How it should work: Allow unicode characters in values for attributes that allow it.

**Comment by flotho** [comment]
Hi,
Do you user partner_firstname from OCA? I had the same issue and updated my rupo. It solved my issues.
Regards
