### ISSUE TITLE
[Security] auth_totp : can be bypass by xml_rpc

### ISSUE THREAD

**Issue by fmdl** [OCA/server-tools#1041]
1- install instance with auth_totp
2- add device and enable MFA
3- connecte with your browser
4- disconnecte on your browser

Use xml_rpc to connecte with your login/password only, MFA no checked !!!

MFA doen't work with xml_rpc.

@obulkin @lasley

**Comment by lasley** [comment]
Thanks for the report @fmdl - I never considered XML-RPC in this. Thinking about it, I'm actually not sure how it would be possible while still fitting within the framework of the RPC spec (or any API really).

I think the solution here is a module that allows for the restriction of XML-RPC based on some user options/ACL, then leverage that in `auth_totp` to allow the user to disable their XML-RPC or accept the risks.

Do you agree with this? Or maybe have a good idea on how to have MFA work with an API? I'm having a bit of trouble wrapping my head around the implementation for an API with MFA TBH.

**Comment by fmdl** [comment]
​It is possible to solve this issue. You can not disable xml_rpc, because the UI web client use json_rpc (and you can do the same things).

​The solution is inside the odoo module : `auth_crypt`.
When you install this mode it copy the field `password` in `password_crypt` whis SHA cryptage. And it set to `NULL` the `password` field. Like that the standard methode (check the field password) return AccesDenied.

In this case create a new field `password_crypt_MFA`, when you active the MFA for an user, you need to copy password_crypt in `password_crypt_MFA`, and set to `NULL` `password_crypt`. Like that the methode to check of `auth_crypt` module return `AccesDenied`. 
And in methode check_credential, you need to do some thinks like that :

1- check_credential check if it is the good password in `password_crypt_FMA`, if it okay, it generate a token and a cookies, and return AccesDenied
2- the main.py know that the AccesDenied, but he see that there a token for this user and return to the auth_totp page.
3- the user set the confirmation code, and now the check_credential check cookie, token, and the confirmation code. If it is okay, set that is good.
4- when the system check credential (not for login), just check cookies and token lifetime.

Question, you system it is multi browser use in same time (iPhone, Home PC, Work PC) ? (At first view, I think no because there can be only one token per user).
Maybe create a new model of token with this fields to use in multi-brower:
- token (default = generate_token)
- confirmecode_validate (default = False)
- max date_time
- cookies_key (default = generate_cookies_key)


Nota 1 : to generate a token you can use `uuid5` or https://docs.python.org/3/library/secrets.html,  ?
Nota 2 : do not use de `database_secret` to crypt the cookies, because if some one know this I can hack other user. Use an uuid5 for each token.
Nota 3: use private methode (with `_`), if not any one can execute with xml_rpc.
Nota 4: don't forget to inherit `def _compute_password(self)` and `def _inverse_password(self)` in res.users model (in `auth_crypt` module), for the wizard to change password (you need to copy in `password_crypt_FMA`).

**Comment by obulkin** [comment]
Thanks for the input, @fmdl. I've followed up on all of these points, and they seem to boil down to three separate issues with the current implementation:

- Users with MFA enabled can still connect to the API with just a password and should instead be blocked from accessing it.
- Multiple simultaneous sessions are not supported since users can only have one MFA login token at a time.
- All device cookies are encrypted using the same secret. This isn't an issue per se, but the system would be even more secure with a more granular encryption process, so I'll probably introduce user-specific cookie encryption keys.

I'll be working on addressing all three of these so stay tuned for more info.

**Comment by fmdl** [comment]
It is correct.

**Comment by obulkin** [comment]
I've pushed up a PR that addresses all of these issues: https://github.com/OCA/server-tools/pull/1065

**Comment by MiquelRForgeFlow** [comment]
This issue can be closed.
