### ISSUE TITLE
[RFC] History for views

### ISSUE THREAD

**Issue by yuriqp** [OCA/server-tools#1053]
We would like to have a feature which allows keeping a history of changes in the arch of a view. This will allow keeping different versions of the views available, so it could be used to prototype, easily restore changes, etc… This could be especially useful for Odoo form and tree views, reports and websites.

We already developed a prototype (module view_history), available here: https://github.com/blooparksystems/view_history. The basic idea is to have a new model (ir.ui.view.version) which stores all changes made to a particular view.

![image](https://user-images.githubusercontent.com/8631284/32752649-438342fc-c8ca-11e7-805e-c380621a626d.png)

Here are some keys to understand the way it works:
- In the ir.ui.view model, we have a boolean field (enable_history) which allow us to activate this functionality for a view (from the user interface).
- The create and write methods of ir.ui.view are extended, so they create new versions (ir.ui.view.version) with the changes on arch field when the enable_history flag is activated.
- Versions are listed in the ir.ui.view form view in a separate tab.
- The current_version field indicates which version is used for the standard actions (like retrieving the arch field when rendering a view). The read and render methods are extended with this purpose.
- When changes are made, those are not automatically “activated”, but stores, let's say, as a draft. To “activate” this changes, one needs to manually set the respective version as “current”. This could be done selection one version from the list of versions.

Notes:
- All changes are made to the latest version.
- Every time there is a change or a version is selected (except when selecting the latest version) a new version is created
- All changes are store using the complete arch field. We considered using another approach (like saving only the differences), but:
  - it makes the implementation more complex
  - could face performance issues (a lot of recursive calls to compute a view)
  - if the goal is to save space, it does not work well on all cases
- We do not handle the case of changing of inherited views, i.e. if an ir.ui.view has enable_history activated, changes in inherited view are not detected.

**Comment by yajo** [comment]
And what's the question?

**Comment by dreispt** [comment]
@Yajo this is an RFC.
@yuriqp sounds like an interesting features for me. On the design side, I would be more comfortable if the active view would always be on the "ir.ui.view" model. this would make it's "current_version" flag redundant.

**Comment by hbrunn** [comment]
I do something quite similar for list views in https://github.com/OCA/web/pull/787 - but then without the history, which should be very simple to add

**Comment by yuriqp** [comment]
Thank you all for your comments. 
@Yajo You are right, I should have used an RFC tag in the issue title.
@dreispt, you may have a point. At the end, if we keep the arch of the active version in the ir.ui.view record, the 'latest' version could be determined by the write_date. Thanks, we will check this.
@hbrunn  We will take a look at the link you posted. Thanks
