### ISSUE TITLE
[RFC] base_blockchain: Become a Hipster

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#1064]
This module will provide a blockchain for use in distributed information platforms. Motivation behind this, outside of simply hopping on the hipster bandwagon (let me find my mustache), is to allow for multiple disparate entities to collaborate on a similar dataset. Usage examples include drug traceability requirements, product pedigree or genealogy data, clinical trials/labs.

At the moment I'm operating purely on theory, as well as some basic code implementations. At this time, my high level question is which solution to implement ([HyperLedger](https://github.com/hyperledger), [OpenChain](https://github.com/openchain), [MultiChain](https://github.com/MultiChain), [BigChainDB](https://github.com/bigchaindb/bigchaindb)), and if it's possible to somehow abstract out the base logic to make an abstract interface allowing to the use of whatever technology that someone wants to build a module for.

High level requirements:
  * create a block and add to chain
  * create a transaction and add to block
  * hash a block
  * verify a hash
  * get the last block
  * get the full chain

I'll be updating this as I think more, I just wanted to drop the prelim RFC to let anyone else interested to also start thinking & drop some ideas/theories/experiences/random comments 😉

**Comment by yajo** [comment]
This sounds like the kind of thing @OSevangelist would be interested on. Am I right? 😜

**Comment by lasley** [comment]
Interestingly enough, I have this working for the most part. 

Major roadblock at this point is that we require a public/private key storage mechanism in order for the sign/hash of the block. Once I finish guaranteeing my theory, this will likely be dependent on #673
