### ISSUE TITLE
base_import_match module for 1tomany fields doesn't work

### ISSUE THREAD

**Issue by Aaqiu** [OCA/server-tools#1067]
![clipboard](https://user-images.githubusercontent.com/31339358/33106851-5118ee7a-cf6f-11e7-8188-fb33ac5de1d8.png)

**Comment by Aaqiu** [comment]
Plus, in version 10，THX! @rvalyi @jbq @phuihock @cmayo @taifu

**Comment by yajo** [comment]
Sorry, not enough information to debug your problem. Please provide steps to reproduce, configurations involved, expected results, actual results, etc. and reopen then.
