### ISSUE TITLE
[prototype] rename module

### ISSUE THREAD

**Issue by bjoliveau** [OCA/server-tools#108]
It would be better to rename this module with : 
- "module_prototyper"
- or "module_builder"

to avoid any confusion with prototype or engineering industry

**Comment by max3903** [comment]
:+1: for module_prototyper

**Comment by pedrobaeza** [comment]
I think this module can be extended later and the name `module_builder` is more generic for this purpose.

**Comment by foutoucour** [comment]
The module has been thought to help to prototype module. In the sense, only few types of module will be able to be released directly from it. Most of work wll need to be reviewed ans improved by a developer after the export.
For that reason, I would second @max3903 for module_prototyper.

**Comment by pedrobaeza** [comment]
OK, we can rename it when it will get more features.

**Comment by foutoucour** [comment]
Renamed to module_prototyper in https://github.com/savoirfairelinux/server-tools/commit/525cbfa9c52b42e175a03bdd4287bfd6570f5776

**Comment by foutoucour** [comment]
Do you think we can close the issue?

**Comment by bjoliveau** [comment]
OK, this issue can be closed
