### ISSUE TITLE
v8 module "import_odbc" ported to v10

### ISSUE THREAD

**Issue by Bilbonet** [OCA/server-tools#1089]
The module (import_odbc) is ported to v10 in:

  https://github.com/Bilbonet/server-tools/tree/10.0/import_odbc

**Comment by dreispt** [comment]
Check https://github.com/OCA/server-tools/pull/596

**Comment by Bilbonet** [comment]
I've checked de #596 
I modified the module base_external_import and fixed the problems.
I have the module in my repository and works fine.

https://github.com/Bilbonet/server-tools/tree/10.0/base_external_import

Maybe is posible tomake de PR to OCA
