### ISSUE TITLE
[9.0][kpi] Python code calculation doesn't support complex expressions

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/server-tools#1094]
Currently, the code expects a simple eval expression that calculates into a value.

As an improvement, it could support complext expressions where the user has to assign the value to a `value` variable, for instance. (Similar to how server actions work)

An object pool could be exposed, along with a more extended context, to allow the user to query objects and get data from odoo instead of querying the database.

I'm wondering if this was made like this to prevent the user from evaluating possibly dangerous code (ie: writing on records). I don't know if it's possible to prevent the user from doing this, while exposing `pool` to him.

Any thoughts?

**Comment by max3903** [comment]
@ivantodorovich this was made to provide flexibility but I've never had a use case to actually use it. If you want to improve the module to support your case, be my guest. I'll be happy to review your contribution.
