### ISSUE TITLE
Module with same name (mgmtsystem_kpi) on OCA/server-tools and OCA/management-system

### ISSUE THREAD

**Issue by joserprieto** [OCA/server-tools#1106]
There are a module with the same name in two repositories:

mgmtsystem_kpi

https://github.com/OCA/server-tools/tree/10.0/mgmtsystem_kpi

https://github.com/OCA/management-system/tree/10.0/mgmtsystem_kpi

I think that they are the same module, in two different repos.

Regards.

**Comment by yajo** [comment]
Lol, true! Could you PR to remove the server-tools one?

**Comment by pedrobaeza** [comment]
server-tools one can be removed.

**Comment by joserprieto** [comment]
I can make the PR to remove from server-tools; but; what is better? remove from server-tools, or from management-system?
I think that is better remove from server-tools (imho).

Regards :)

**Comment by yajo** [comment]
Yes please

**Comment by joserprieto** [comment]
Done:

https://github.com/OCA/server-tools/pull/1141

Sorry for the delay.

Regards.
