### ISSUE TITLE
[10.0] html_text: Wrong dependancy lxml.html

### ISSUE THREAD

**Issue by kh-badep** [OCA/server-tools#1113]
Hello,

I was trying to install html_text and it gives me this error:

> Collecting lxml.html (from odoo10-addon-html-text->odoo10-addons-oca-server-tools)
>   Could not find a version that satisfies the requirement lxml.html (from odoo10-addon-html-text->odoo10-addons-oca-server-tools) (from versions: )
> No matching distribution found for lxml.html (from odoo10-addon-html-text->odoo10-addons-oca-server-tools)
> 

Even though lxml is already installed:

> root@server3:/home/ubuntu# pip list | grep lxml
> DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
> lxml (4.1.1)

I think in the manifest file for the module, in external dependancies there just need to be 'lxml' and not 'lxml.html':

>     "external_dependencies": {
>         "python": [
>             "lxml",
>         ],
>     },

**Comment by MLauri** [comment]
The same problem also affects Odoo11 branch.

**Comment by pedrobaeza** [comment]
Fixed in 5355b2628133d3dd7f9fdf0ea2d0b1d948fda7a3

**Comment by GleydsonHudson** [comment]
The aforementioned issue in branch 10.0 was not corrected. I would like to ask if it is possible to do it so, as I am having the same issue.
