### ISSUE TITLE
auditlog -> rule ->  Log Reads then give this error

### ISSUE THREAD

**Issue by akhodifad** [OCA/server-tools#1122]
![selectreallog](https://user-images.githubusercontent.com/32675315/34718940-9faa6dce-f55e-11e7-9aca-a905e68b836d.png)
![openso](https://user-images.githubusercontent.com/32675315/34718939-9f7b039a-f55e-11e7-9c57-08b986dd9235.png)

**Comment by avmediadesign** [comment]
I'm facing the same error on v10 Enterprise.
```
 File "/odoo/odoo-server/odoo/models.py", line 4911, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 10; 2 is required
```
It appears on any model.
The logs are properly recorded but this error message pops up.
Any idea?

**Comment by uakhhhh** [comment]
I'am same error on v10 community.
