### ISSUE TITLE
[11.0] Why removing "#  -*- coding: utf-8 -*- " in 11.0 version ?

### ISSUE THREAD

**Issue by mbcosta** [OCA/server-tools#1132]
Hi all.
I noticed in version 11.0  "#  -*- coding: utf-8 -*- "  was removed https://github.com/OCA/server-tools/blob/11.0/auditlog/models/__init__.py#L1 https://github.com/OCA/server-tools/blob/10.0/auditlog/models/__init__.py#L1 , there is any reason for it ? Because in my local enviroment  when I try to access the server an error happened

  File "/workspace/parts/server-tools/auditlog/models/__init__.py", line 3, in <module>
    from . import rule
File "/workspace/parts/server-tools/auditlog/models/rule.py", line 1
SyntaxError: Non-ASCII character '\xc2' in file /workspace/parts/server-tools/auditlog/models/rule.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

cc @rvalyi

**Comment by Garamotte** [comment]
Odoo 11 must be run using python3, I think you still use python2.

**Comment by sebalix** [comment]
Hi,

It's because Odoo 11.0 should be executed with Python 3.5, and the default encoding with Python3 source code is ``utf-8`` so there is no need to add it (https://docs.python.org/3/howto/unicode.html#the-string-type).

**Comment by mbcosta** [comment]
Thanks @sebalix @sylvain-garancher
