### ISSUE TITLE
[11.0][auditlog] Logging `create` events on `account.move.line` breaks invoice validation

### ISSUE THREAD

**Issue by MaxyMoos** [OCA/server-tools#1134]
## Minimum setup to reproduce the issue:

* Create a new Odoo V11 database
* Install `account_invoicing` and `auditlog`
* Create an auditlog rule, logging Create/Write/Delete events on `account.move.line` items
* Create a Customer Invoice
* Try to validate the invoice

## Problem

A popup appears with the error message:
"Cannot create moves for different companies."

## Analysis

It appears that the account.move.line instances that are created during the invoice validation process are missing the `company_id` field value, hence the error message displayed.

From what I've gathered from debugging, the problem is coming from the `create_full` function in the auditlog module:

```python
@api.model
@api.returns('self', lambda value: value.id)
def create_full(self, vals, **kwargs):
    self = self.with_context(auditlog_disabled=True)
    rule_model = self.env['auditlog.rule']
    new_record = create_full.origin(self, vals, **kwargs)
    new_values = dict(
        (d['id'], d) for d in new_record.sudo()
        .with_context(prefetch_fields=False).read(list(self._fields)))
    rule_model.sudo().create_logs(
        self.env.uid, self._name, new_record.ids,
        'create', None, new_values, {'log_type': log_type})
    return new_record
```

When we call the `origin` method to create `new_record`, everything is OK: printing `new_record.company_id` gives out the correct value.

The problem is that the generation of the `new_values` dict, and especially the call to `new_record.read` does remove the `company_id` value from `new_record`.
Maybe because it's not yet commited in the database but we still try to read data from it. I've stopped my investigations here since I've started to get in a bit over my head.

**Comment by MaxyMoos** [comment]
After experimenting a bit more, it would appear that all the fields using both the `related=<class>` option and the `store=True` option are afflicted by this issue.
Another example being the fields `journal_id`, `user_type_id` or `date` on the account.move.line model.

**Comment by sebalix** [comment]
Maybe this is due to the `.with_context(prefetch_fields=False)`, try to remove it just to see if it works?

**Comment by MaxyMoos** [comment]
No, unfortunately it seems like the problem is still there whether I drop the call to `with_context` altogether or if I just remove the `prefetch_fields` parameter from the call.

**Comment by MaxyMoos** [comment]
As a quick-and-dirty workaround, here's what I've done so far - feedback appreciated by Odoo's inner workings experts as to what can be done to improve this:

```python
@api.model
@api.returns('self', lambda value: value.id)
def create_full(self, vals, **kwargs):
    self = self.with_context(auditlog_disabled=True)
    rule_model = self.env['auditlog.rule']
    new_record = create_full.origin(self, vals, **kwargs)
    new_values = {}
    for rec in new_record:
        rec_dict=  {}
        for f in list(self._fields):
            tmp = getattr(rec, f)
            if isinstance(tmp, models.BaseModel):
                tmp = [x.id for x in tmp]
            rec_dict[f] = tmp
        new_values[rec['id']] = rec_dict
    rule_model.sudo().create_logs(
        self.env.uid, self._name, new_record.ids,
        'create', None, new_values, {'log_type': log_type})
    return new_record
```

**Comment by smangukiya** [comment]
@MaxyMoos : Hi, I was facing the same issue while generating Journal Entry. I've tried resolving that and having success with below given PR. I hope that will help.
 
https://github.com/OCA/server-tools/pull/1399

Thanks
Sandip
