### ISSUE TITLE
[module_auto_update] Server is not restarted after update?

### ISSUE THREAD

**Issue by BT-astauder** [OCA/server-tools#1151]
IMHO the server must be restarted to read apply changes in python code. Or am I wrong?

This would be in fact quite easy

from odoo.service.server import restart
restart()

We have a similar approach in our company. But there are a few things different:
- We first load all translations of a changes module. We do that also for all modules that depend on the changed module. So modules for our customers always win in the "translation battle".
- Then we just mark the changed modules in the DB as to upgrade.
- Then we restart the server and the upgrades are made as it would be called by -u

The upgrade is done in done before spanning the workers. So no concurrent problems with that.
The restart waits for cron jobs to finish first. Can be seen as advantages, but also disadvantage...

@Yajo @pedrobaeza

**Comment by pedrobaeza** [comment]
Thanks for the advises, Andreas.

About restarting, I see it feasible for the module indeed. TIL that method.

About the general method, what we want to avoid is server downtime, so there can be of course concurrency problems, but repeating is for now our approach, as we consider more important to keep the system running. And as we are running over Docker, there's little chance that the system gets unusable during the repetitions.

**Comment by astirpe** [comment]
What about enabling the restart with a flag in configuration? Restarting the server in the night would be acceptable by many companies I guess.

**Comment by pedrobaeza** [comment]
I think it's a hard change in the module, but @Yajo can say more accurately.

**Comment by yajo** [comment]
Seems legit, feel free to open PR. I guess we'd have to use mock for testing though... Not much of a problem.

**Comment by BT-astauder** [comment]
Thank you all for your responses. I just tested the behaviour again in 11.0:
New fields are created without any restart, but changes in code are not loaded. So I do not understand how this module is supposed to work. How do you get new code running?

For better understanding I like to clarify some differences in the approches.

module_auto_update: 
Updates in a single worker. Other workers are informed right after the update to invalidate the cache. But during the update process concurrency problems may occur. I just can guess that the update during the night works mostly because no other worker is doing something. Otherwise I guess the other workers runs quite soon in concurrency errors.
So the big advantage, that all other workers continue is more theoretically in my eyes. When they really try to do something, they are not very reliable anymore and will fail quite soon.

Our module:
Marks all modules as 'to_update' and restarts the server then. The update then is done before the workers are spanned up again and only a single process is running:
https://github.com/odoo/odoo/blob/2aabdc00c353aa0b2d4e98e66094cee9f149c000/odoo/service/server.py#L619-L629
This prevents (nearly) all concurrent updates and makes the process very reliable. The only problem I saw very rarely was in fact when writing the new checksum on ir.module.

Our current implementation has one big drawback: to write the checksum after the restart we patched in the core the function load_module_graph() :
https://github.com/odoo/odoo/blob/2aabdc00c353aa0b2d4e98e66094cee9f149c000/odoo/modules/loading.py#L28
When I remember correctly, the patch was needed only, because when updating 'base' the addons_path is not yet applied and a monkey patch is not yet possible. But hey, who updates 'base' ;)

I would really like to bring the two approaches together. But currently I do not understand how this module is used, when after the update the old python code is still active. Or do I miss something? I do not want to break something.

**Comment by pedrobaeza** [comment]
We launch a command for restarting Odoo after performing the autoupdate. In our Docker infrastructure is:
```fish
docker-compose run --rm odoo autoupdate ; and docker-compose restart odoo
```

**Comment by pedrobaeza** [comment]
In your approach I still see the problem that all requests will be blocked until the update process finishes (and that can take long time), and I see also a problem when there's an error updating. What happens?

**Comment by yajo** [comment]
There are 2 approaches:

1. Stop, update, restart, as @BT-astauder does: no concurrency errors are possible, but service must be unavailable in the mean time.
2. Update in parallel, as we do: concurrency errors are possible, and there's room to avoid stopping Odoo.

This addon was born to use the 2nd one. If you have concurrency errors, in general terms you can retry X times and then restart the server if it didn't work to fallback to method 1.

However making the module support both would be a good improvement indeed.

**Comment by BT-astauder** [comment]
@pedrobaeza Thank you for explaining how you are using the tool exactly. Now I understand. And I like your approach a lot over ours. The only thing I am very unsure: How can the other workers still be functional? Or will they fail by the first change the updating worker did (either DB or e.g. in a view)?

When they still work, I do not see many arguments for our process. If they do not work anymore in a meaningful way, I do not see, why they should stay active. Then odoo is blocked during the update process because all responses are not reliable anymore.

**Comment by sbidoul** [comment]
@BT-astauder I made #1176 after reading this conversation.

**Comment by pedrobaeza** [comment]
There should be only one module in OCA for this. We can and we should fix possible issues, but not to have several approaches for the same problem.

**Comment by sbidoul** [comment]
It's not a different approach Pedro, it's a refactoring that splits the module in two.

**Comment by pedrobaeza** [comment]
OK, but I don't want that, sorry. I prefer that both concentrates on solve the problems you mention (which I don't see, except the uninstallation part, that can work for not being a problem), and not diverge in the update method. The autocommit one is something inherent of the upgrade process, so I don't see where's the problem.

**Comment by BT-astauder** [comment]
@sbidoul With your new module, what is the additional benefit of the original module_auto_update?

Or very specific asked: What is the benefit of

https://github.com/acsone/server-tools/blob/63b5fc961475a63eeb8033f6dd720cec081f05de/module_auto_update/wizards/module_upgrade.py#L23

over just 

env['ir.module.module'].upgrade_changed_checksum()

?

**Comment by sbidoul** [comment]
@BT-astauder for my use cases there are no benefits in `module_auto_update` over env['ir.module.module'].upgrade_changed_checksum(). I personally prefer to have separate method that does not touch the standard Odoo upgrade process.

That's why I want to keep them both separate while sharing the common code if needd.

**Comment by pedrobaeza** [comment]
@sbidoul can you explain then what is going to be your update strategy? Maybe it's better than the current one and we can switch.

**Comment by BT-astauder** [comment]
I join @pedrobaeza suggestion to skip the original module completely. The automated update at 3am is not very useful from inside odoo anyway, because you need to pull the new sources from outside.

**Comment by sbidoul** [comment]
@pedrobaeza our upgrade strategy is to run `env['ir.module.module'].upgrade_changed_checksum()` in an Odoo shell with the main instance stopped. But I see no reason you could not run it with a cron on a running instance (except the restart remains necessary for coping with python code changes of course). Probably you can run it in a separate shell while the main instance is running, and restart it afterwards.

**Comment by sbidoul** [comment]
So it looks like this matter is settled :)

**Comment by yajo** [comment]
Yep, it's been a long way, thanks everybody involved :blush:
