### ISSUE TITLE
How can I use webhook in Odoo community?

### ISSUE THREAD

**Issue by Alubba** [OCA/server-tools#1174]
Hi OCA,

I have downloaded your webhook module and unzip to my project, what's more I followed below documentation to configure the webhook in user panel but it seems different. I did not find any fields which u mention in document guide.

Documentation URL :http://odoo-webhook.readthedocs.io/en/latest/configuration.html#through-user-panel

Let me show you the pics:
My odoo environment:
![pic1](https://user-images.githubusercontent.com/36148006/36715212-2e5eac8c-1bd0-11e8-8af2-a29747b7b93b.png)

documentation:
![pic2](https://user-images.githubusercontent.com/36148006/36715216-33ecc328-1bd0-11e8-8e9d-0ba03662415e.png)

Could you please give me some advice how can I use it?

**Comment by pedrobaeza** [comment]
This is not an issue nor this module belongs here, so I close. Please make the question in forums/lists.

**Comment by Alubba** [comment]
Could you please tell me where can I put this question for help?

**Comment by pedrobaeza** [comment]
General Odoo forum or Odoo lists.

**Comment by legalsylvain** [comment]
> nor this module belongs here

@pedrobaeza I think he's talking about this module https://github.com/OCA/server-tools/tree/10.0/webhook

regard.

**Comment by pedrobaeza** [comment]
But the documentation was not from that module. Any way, he is asking for help, not putting an issue. And it's not even something specific. He hasn't investigated enough. I remind you this link: http://www.catb.org/esr/faqs/smart-questions.html

**Comment by Alubba** [comment]
Thanks for help. @legalsylvain @pedrobaeza 
Because my English is not pretty good. If you kindly give me a link to put this question I am very appreciate.

Cause I am confused that the documentation shown me is different when integrate the webhook downloaded from OCA.

**Comment by miteshdhaduk** [comment]
@Alubba I also face same issue. Have you got anything?
