### ISSUE TITLE
[11.0] SyntaxError: Non-ASCII character '\xc2'

### ISSUE THREAD

**Issue by scigghia** [OCA/server-tools#1197]
We need to substitute every  © char from the first line in every python file 
because it give this error:
File "/opt/odoo/11enterprise/parts/server-tools/auditlog/models/log.py", line 1
SyntaxError: Non-ASCII character '\xc2' in file /opt/odoo/11enterprise/parts/server-tools/auditlog/models/log.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

(python 2.7.9)

**Comment by pedrobaeza** [comment]
Odoo v11 should be use with Python 3, not Python 2

**Comment by slimit** [comment]
Exactlty the same for v10.
