### ISSUE TITLE
[10.0][auth_session_timeout]Doesn work anymore after Odoo commit da1f153d61d747d9357694382fe04f96c0ca886a

### ISSUE THREAD

**Issue by sferket** [OCA/server-tools#1237]
The function check in res.users simply doesn't get called anymore after this patch because password is not stored in the session anymore. 

See Odoo commit: 
https://github.com/odoo/odoo/commit/da1f153d61d747d9357694382fe04f96c0ca886a#diff-03542f2676ca18278ea62cb40f5a2261

**Comment by yelizariev** [comment]
This update should be applied for branch 10: https://github.com/OCA/server-auth/commit/f19bd6ef199e284cbbfd002ba0b40ef3bd67b598

**Comment by lfreeke** [comment]
Isn't fixed by this merge request? https://github.com/OCA/server-tools/pull/1495

**Comment by yelizariev** [comment]
It doesn't look so

**Comment by anassahmed** [comment]
The method `_compute_session_token` isn't called with each request like `check` was.

In `11.0` version of `auth_session_timeout`; it uses `_authenticate` in `ir.http` model, which is called with each request (we've been using the `11.0` version with our Odoo `10.0` instance for some time now).
