### ISSUE TITLE
[10.0] auth_totp - Remember this device working?

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/server-tools#1246]
I am testing auth_topt in runbot and local. 
![image](https://user-images.githubusercontent.com/7683926/40068199-5a021584-5868-11e8-8920-2dc64b9ce44c.png)

Although I press 'Remember this device' Odoo keeps asking me for MFA code when I log out and attempt to log in again.

As a user, I set up a new device in My Preferences, and set set MFA.
Then I log out. 
Then I enter my user and pass, and I am prompted to enter the MFA code. I also press 'Remember this device'.
Then I have to enter again my user/pwd (again?), and then I'm finally in Odoo.

Then I log out, and when I try to log in again, I have to enter the MFA once again.

Am I missing something? From a usability perspective I see:
* I have to enter my user/pwd twice. Is that necessary?
* I have to enter the MFA code every time, even when I pressed 'Remember this device'.

Same problem applies to the migration to 11.0 https://github.com/OCA/server-auth/pull/17

@obulkin Perpahs you know if this is a bug, or we're just using the application incorrectly?

**Comment by JordiBForgeFlow** [comment]
cc @mreficent

**Comment by obulkin** [comment]
The issue with remembering the device is probably due to the following limitation described in the README: 

> By default, the trusted device cookies introduced by this module have a Secure flag. This decreases the likelihood of cookie theft via eavesdropping but may result in cookies not being set by certain browsers unless your Odoo instance uses HTTPS. If necessary, you can disable this flag by going to ``Settings > Parameters > System Parameters`` and changing the ``auth_totp.secure_cookie`` key to 0.

The second username/password request seems like a bug.

**Comment by JordiBForgeFlow** [comment]
@obulkin Thanks. Using https I was able to get past the first issue

I will look further into the second issue. Closing this for now.

**Comment by travish2** [comment]
@JordiBForgeFlow  did you ever find an answer to having to log in twice? It happens on runbot with https in v11 but not v12
