### ISSUE TITLE
auditlog module: field deletion triggers log removal

### ISSUE THREAD

**Issue by PieterPaulussen** [OCA/server-tools#1260]
I noticed the following cascade deletes [here](https://github.com/OCA/server-tools/blob/8.0/auditlog/models/log.py#L36-L39).

Is it desired that removing a model / field (f.i. during a migration) removes the auditlog lines as well?
What if we keep the auditlog line and use a related field to store the field name (and the log for that matter). Would that not be preferable to losing record in the auditlog?
@sebalix @hbrunn

**Comment by sebalix** [comment]
@PieterPaulussen indeed if you need to preserve the logs even if the corresponding field is removed, you can change the `ondelete` to `set null` on `field_id` (however we should not change the `log_id` IMO). Feel free to open a PR for that, I don't see any problem with that feature.

**Comment by pedrobaeza** [comment]
Isn't that field required?

**Comment by PieterPaulussen** [comment]
@pedrobaeza Indeed, the field is required. If we raise an exception during create/write on the value of the field, we could cover that. 
@sebalix I will keep the cascade on log_id. Thanks for the suggestion. 
PR coming up ;-)
