### ISSUE TITLE
[base_suspend_security] Can not bypass access rights on fields (using attributes groups)

### ISSUE THREAD

**Issue by novawish** [OCA/server-tools#1268]
**Current situation:**
A field was defined with groups: `name = fields.Char(groups="base.group_user")`
If the user does not belong to group `base.group_user`, he can not read or update the above field even with option `suspend_security()`.

The reason is module **base_suspend_security** only disable (temporarily) all the **record rules** and **access rights**. Meanwhile the check of security on fields is processed in function `def check_field_access_rights` of `class BaseModel(object):`.

**Suggested solution:**
Can we do an override to function `check_field_access_rights` to bypass security check whenever it is called with option `suspend_security()`?

**Comment by hbrunn** [comment]
sure. The magic works by checking if `self.env.uid` is our marker class as in https://github.com/OCA/server-tools/blob/10.0/base_suspend_security/models/ir_model_access.py#L31 - should be simple to do

**Comment by novawish** [comment]
@hbrunn Thanks for your reply, however what i'm afraid is should we override a base function that is almost used everywhere. Is there any risk if i do the same as the existing method?

**Comment by hbrunn** [comment]
well, there's always the risk of messing up, but if you do, we'll tell you during review, no worries. Don't forget to add a test case too

**Comment by novawish** [comment]
I’m writting the test case, however i’m struggling to find a way to set attr groups to a field inside testing environment. It seems that the security setup is stored in m2m field named groups in model ir.model.fields but no, it has nothing to do with the attr groups. There must be somewhere stores that kind of information, could you please help me to give an idea for that?

**Comment by hbrunn** [comment]
read the code of `check_field_access` - it just looks at the groups attribute, so you can simply monkey patch that for some field, run the test, undo your patch

**Comment by novawish** [comment]
After trying several methods, i think that in the Unit test environment the system does not check for access rights on fields (i have created a real patch: set groups on the fields and tried on the GUI to make sure the testing user can not update restricted field, however he still be able to write that field in the Test Case). The checking security on fields is tricky, it's not simple as record rules nor access rights, how do you think?
