### ISSUE TITLE
inactive_session_time_out question

### ISSUE THREAD

**Issue by ericzen** [OCA/server-tools#1270]
Hello,

I'm using Odoo entreprise 10 with nginx and i want to know if this module is ready for this config.

Indeed i've installed it and session still be active.

Thanks for your help

**Comment by pedrobaeza** [comment]
The module is called in v10 auth_session_timeout. I think you have installed an incorrect version.

**Comment by ericzen** [comment]
Sorry for my confusion in the name. 


I've effectively install auth_session_timeout and it's not working on my config. 


Regards

**Comment by ericzen** [comment]
hello,
Is this auth_session_timeout working with odoo enterprise ? Because still not working on my config.

**Comment by yelizariev** [comment]
It doesn't work. See https://github.com/OCA/server-tools/issues/1237
