### ISSUE TITLE
[11][Asking]Prototyper for Odoo 11

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/server-tools#1278]
Hello guys, thank you for this tools.

I want to ask you: What's about module prototyper for 11?

**Comment by pedrobaeza** [comment]
Nobody has communicated about migrating it to that version.

**Comment by SalahAdDin** [comment]
But, why?

**Comment by sebalix** [comment]
Because someone has to migrate it to make it available on Odoo 11.0: you or someone else :)

**Comment by pedrobaeza** [comment]
You can also finance any OCA contributor to do it.
