### ISSUE TITLE
[10.0] Requirements conflict with requirements from partner-contact

### ISSUE THREAD

**Issue by igallart** [OCA/server-tools#1304]
If you install requirements from partner contact 10.0, it say python-stdnum==1.1, but in server-tool there isn't version. The problem is that the version 1.1 from partner-contact not containt the import damm, and show a warning in the module sequence_check_digit.

Maybe the issue should go to partner-contact. I'm not sure that solution is the correct, change requirement in partner-contact?

**Comment by Garamotte** [comment]
As discussed [here](https://github.com/OCA/maintainer-quality-tools/issues/494), we should avoid a version freeze in OCA's repos.

Does partner-contact's modules work with the latest version ?
If not, is it possible to fix them to work with the latest version ?

**Comment by sbidoul** [comment]
@igallart can you point me to the place where it is said `python-stdnum==1.1`? I don't find it right away.

**Comment by Garamotte** [comment]
@sbidoul this is in the `requirements.txt` file of the 10.0 branch in partner-contact: https://github.com/OCA/partner-contact/blob/10.0/requirements.txt#L1

**Comment by sbidoul** [comment]
Ah yes. There is nothing in the commit history explaining why the version is pinned to 1.1. So I suggest to remove it and if something breaks, that something will need to be fixed.

**Comment by Garamotte** [comment]
@sbidoul Browsing the history in the 8.0 branch, the pinning seems to come from https://github.com/OCA/partner-contact/pull/216/commits/5438339dfbc0265b63c136a1f249d0723ee2ed33 (included in https://github.com/OCA/partner-contact/pull/216), and I think this is related to https://travis-ci.org/OCA/partner-contact/jobs/98053404#L666-L670

IMO, this is not relevant anymore.

**Comment by igallart** [comment]
I think like @sbidoul, updated at the last version and fixed if is needed

**Comment by pedrobaeza** [comment]
Please make the PR

**Comment by igallart** [comment]
https://github.com/OCA/partner-contact/pull/602
