### ISSUE TITLE
11.0 backup access denied 

### ISSUE THREAD

**Issue by abdallamhafeez** [OCA/server-tools#1310]
Hi
I have issue when take backup via `auto_backup` and make option `list_db = False` appear error in log `
odoo.exceptions.AccessDenied: Access denied` and backup file created with zero size

**Comment by jcarlosmontoya** [comment]
Hello, this module does not work with list_db = False config parameter

![image](https://user-images.githubusercontent.com/7680456/64592565-93432e80-d3ac-11e9-95e3-45e48ad47783.png)

**Comment by kos94ok-3D** [comment]
Related: #1664
