### ISSUE TITLE
Auto backup folder - problem when database is duplicated

### ISSUE THREAD

**Issue by zbik2607** [OCA/server-tools#1311]
After duplicate the database, the backup folder still remains the same.
In this way, backup of the duplicated database is saved at the same time and in the same place as the backup source base.

**Comment by RoelAdriaans** [comment]
There is no way to see when a database is duplicated, I think.
You have the same issue with fetchmail; the first database that fetches the email gets it. 

The only way to fix this is to include the name of the database in the filename at this point: https://github.com/OCA/server-tools/blob/11.0/auto_backup/models/db_backup.py#L259

**Comment by zbik2607** [comment]
Yes, database name should be added to the filename or ... separate folder with new name of database
