### ISSUE TITLE
Auto Backup is very slow with SFTP transfer

### ISSUE THREAD

**Issue by TimLai125** [OCA/server-tools#1315]
**Impacted versions:**
10.0c but other versions should also have this issue.
Auto Backup Module version: 10.0.1.0.2

**Steps to reproduce:**
1. Create an "Automated Backups" record and select "Remote SFTP server" as the "Method"
2. Execute the Backup

**Current behavior:**
The transfer speed of the backup file is very slow. It takes 37 minutes to transfer a 208MB file (~96 KB/S)
![image](https://user-images.githubusercontent.com/27185427/42795237-dc080de4-89b5-11e8-9682-7c031b6d2b78.png)

While we have a server with 700MB dump file which means it will roughly takes 125 minutes to complete the transfer.

**Expected behavior:**
We expected that we should have a speed that is comparable with the `rync` command, i.e. 
```
sent 8,343,006 bytes  received 35 bytes  618,003.04 bytes/sec
total size is 52,972,996  speedup is 6.35
```

**Comment by TimLai125** [comment]
Hi @Yenthe666, Maybe you can give us some advice on this?
I am not sure whether this is the reason, ref: https://stackoverflow.com/a/28584857. I will give this a try after the backup is finished.

**Comment by Yenthe666** [comment]
Hmm, that looks very long honestly. I never tried it with Windows as I only use Linux for all customers so couldn't tell you why directly.

**Comment by TimLai125** [comment]
> I never tried it with Windows as I only use Linux for all customers so couldn't tell you why directly.

Here we use linux as well (the screenshot is taken from WinSCP).

**Comment by Yenthe666** [comment]
@TimLai125 so this is from a Linux to a Linux? Is there a good internet connection between both servers at all times?

**Comment by TimLai125** [comment]
@Yenthe666 Yes, it is from a Linux to Linux and I believe there is a good connection. Since I tried to use `rsync` to perform the file transfer and the speed is fastter, i.e. 618,003.04 bytes/sec (600kb/s)

**Comment by elicoidal** [comment]
@TimLai125 Looks to me a transport protocol question more than a Odoo question :wink:

**Comment by elicoidal** [comment]
did you test sftp from server to server (not using Odoo)?

**Comment by pedrobaeza** [comment]
Yes, has nothing to do with Odoo. Maybe Python libraries, but more the protocol used.

**Comment by TimLai125** [comment]
Hi @elicoidal , yes, I test the SFTP from server to server without using the auto_backup module, the speed is much faster.
