### ISSUE TITLE
SQL Export, How can I send parameters?

### ISSUE THREAD

**Issue by GrupoAlvamex** [OCA/server-tools#1321]
Hello @florian-dacosta 

Could you help me to use SQL Export module?   How can I send parameters and replace in query?

Thank you!!

**Comment by zzwxrchi** [comment]
Create variables and sql query by order.
Example:
1.
Create Variables in Dashboards > Dashboards > Sql Export Variables > Create
  Field Name: x_Pname
  Field Label: Pname
  Field Type: text
  Model: Allow the user to save the file with sql request's data
  Required: Yes

2.
Created sql query in Dashboards > Dashboards > Sql Export > Create
  Name: Test Select
  File Format: CSV
  Copy Options: CSV HEADER DELIMITER ';'
  Encoding: utf-8
  SQL Request
    Select * from res_partner where name = %(x_Pname)s

  Parameters
    x_Pname

3.
Save > Validate SQL Expression > Execute Query
  One dialogue will by open to enter value of xPname and create CSV file to download.

**Comment by ivanporras** [comment]
what about many2one?
