### ISSUE TITLE
Declaration about dbfilter_from_header module?

### ISSUE THREAD

**Issue by minaeid90** [OCA/server-tools#1342]
In configuration part in readme of dbfilter_fom_header module, I don't understand what should I do to send database in the header of the request?

**Comment by pedrobaeza** [comment]
??

**Comment by minaeid90** [comment]
sorry I forgot to add description to the issue

**Comment by pedrobaeza** [comment]
Any way, questions should be directed to mailing lists or forums, not to the issue tracker.

**Comment by carvierdotdev** [comment]
> Any way, questions should be directed to mailing lists or forums, not to the issue tracker.

Could you please provide the links to 'mailing lists or forums'. I'm stuck in the documentation of dbfilter_from_header module. I'm not finding anything here.

Thank you in advance @pedrobaeza

**Comment by pedrobaeza** [comment]
Forums: https://www.odoo.com/forum
Mailing lists: https://www.odoo.com/groups
