### ISSUE TITLE
Log remote ip when behind remote proxy

### ISSUE THREAD

**Issue by ananiasfilho** [OCA/server-tools#1356]
We have nginx and apache as Reverse proxy to odoo 8 and use auth_brute_force module.
My environment:

Nginx reverse proxy: 192.168.0.1
Odoo: 192.168.0.2 - Version 8

 I have set right headers, but module just get Proxy ip address.
`       	# set headers
        	proxy_set_header    X-Real-IP       $remote_addr;
        	proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
   		proxy_set_header X-Forwarded-Proto $scheme;
    		proxy_set_header Host $host;
`
And log is:
` WARNING kmee openerp.addons.auth_brute_force.controllers.controllers: Authentication failed from remote '192.168.0.1'. Login tried : 'ananias'. Attempt 5 / 10.
`
I checked file code server-tools/auth_brute_force/controllers/controllers.py 
https://github.com/OCA/server-tools/blob/8.0/auth_brute_force/controllers/controllers.py#L37

`            remote = request.httprequest.remote_addr
`
and changed to:

```
            if "HTTP_X_FORWARDED_FOR" in request.httprequest.environ:
                # Virtual host        
                 remote = request.httprequest.environ["HTTP_X_FORWARDED_FOR"]
            elif "HTTP_HOST" in request.httprequest.environ:
                # Non-virtualhost
                remote = request.httprequest.environ["REMOTE_ADDR"]

```
Now, module show right IP (from x-forwarded-for).

`WARNING kmee openerp.addons.auth_brute_force.controllers.controllers: Authentication failed from remote '191.13.63.3'. Login tried : 'ananias'. Attempt 6 / 10.`

Its the right solution or need something to do on nginx or odoo config without change controller.py?
Thank you!

**Comment by ananiasfilho** [comment]
More informations:
Its a tcpdump output with more few informations as Headers.
```

POST /web/login HTTP/1.0
X-Real-IP: 191.13.63.3
X-Forwarded-For: 191.13.63.3
X-Forwarded-Proto: https
Host: odoo.kmee.local
Connection: close
Content-Length: 61
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Origin: https://odoo.kmee.local
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://odoo.kmee.local/web/login
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,de;q=0.8,es;q=0.7

```

**Comment by yajo** [comment]
You probably have an older, buggy, werkzeug package. See https://github.com/odoo/odoo/issues/18052#issuecomment-364703091.

Thanks!

**Comment by ananiasfilho** [comment]
Yajo, just to know. My issue is not with odoo logs. Its on auth_brute_force module.
 
Odoo logs show ip right! just the auth_brute_force_module log wrong IP.
```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import werkzeug
>>> werkzeug.__version__
'0.10.4'
>>> 

```
