### ISSUE TITLE
[10.0] Mass Editing not showing action for Product

### ISSUE THREAD

**Issue by elevationO** [OCA/server-tools#1366]
I have confirmed the issue in runbot.

I can create a new mass editing item in settings, add the product model, select fields and add sidebar button but nothing shows in the action button on the products module.

I have tried both product and product template.

Thanks in advance.

**Comment by pedrobaeza** [comment]
I can confirm it's working. I think you haven't refreshed the browser

**Comment by elevationO** [comment]
Thanks.  After refresh the Product Template one I created is showing.

Also thanks for the very quick response!
