### ISSUE TITLE
[11.0] database_cleanup fields for columns not removed

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/server-tools#1396]
When using the module database_cleanup to purge orphaned columns, the corresponding fields in ir.model.fields are not removed.

While searching fields in the frontend the user is still able to find orphaned fields/columns.

**Comment by pedrobaeza** [comment]
AFAIK, they are 2 different purges in their corresponding menu entries. @hbrunn can you confirm?

**Comment by hbrunn** [comment]
no, there indeed can be cases where the above happens, so a field is not in the ORM (that's what the orphaned columns cleanup looks at), but still in `ir_model_fields`.  It would make sense to add a `Purge fields` menu entry

**Comment by CasVissers-360ERP** [comment]
@astirpe @hbrunn Is this something which might be fixed? It can be very confusing.

**Comment by CasVissers-360ERP** [comment]
Fixed by #2905
