### ISSUE TITLE
Q: new auth module on v10 -> go for OCA/server-auth?

### ISSUE THREAD

**Issue by simahawk** [OCA/server-tools#1398]
What's the policy is this case?

Being a new module it feels right to put it into server-auth (opt 1).
Still, probably for the sake keeping everything homogeneous we should put it here in 10.0 (opt 2).

Cast your votes! :)

**Comment by pedrobaeza** [comment]
If we can classify it correctly since beginning, I would say to create branch 10.0 on OCA/server-auth and put it there.

**Comment by simahawk** [comment]
and maybe we can mention that other auth modules are hosted on server-tools#10.0 in the main README

**Comment by gurneyalex** [comment]
@simahawk we are going to need this in 8.0 and 9.0 too.

**Comment by simahawk** [comment]
:sob: :sob: :sob: :sob:

**Comment by pedrobaeza** [comment]
Can this be closed?
