### ISSUE TITLE
[RFC] database_cleanup: Deprecate identifier_adapter code

### ISSUE THREAD

**Issue by moylop260** [OCA/server-tools#1426]
The following code could be replaced:
 - https://github.com/OCA/server-tools/blob/11.0/database_cleanup/identifier_adapter.py

by
```python
from psycopg2 import sql

cur.execute(
    sql.SQL("insert into {} values (%s, %s)")
        .format(sql.Identifier('my_table')),
    [10, 20])
```
http://initd.org/psycopg/docs/sql.html#module-psycopg2.sql

**Comment by pedrobaeza** [comment]
Isn't better to make the PR directly?

**Comment by moylop260** [comment]
Yes, even it’s better the PR
Help wanted
Do you want create it?

**Comment by pedrobaeza** [comment]
I'm not sure what you are trying to achieve, so I'm not the more suitable for this
