### ISSUE TITLE
refactoring module_auto_update

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-tools#1429]
Hi, 

For some projects, I have to generate a hash of modules, to ensure that code did not changed. (It's about certification process, like, for exemple, in France, the connexion between point of sale and scale).

For that purpose, I have to compute hash, based on source code (.py, .xml, but .js too). All the code to compute this hash is in the module ``module_auto_update``, so I propose : 

- to create a new generic module in server tools named module_hash, that provides all the algorigthm, currently in the file ``addon_hash``
https://github.com/OCA/server-tools/blob/12.0/module_auto_update/addon_hash.py
- to make ``module_auto_update`` depends on this new module.

Are you agre with that proposal ?

CC : maintainer : @sbidoul

**Comment by legalsylvain** [comment]
Extra question : for the time being, seems that 

- if you add / change test files. (``./tests/*.py`` or ``demo/*.xml``), the module_to_update consider the module as 'to be updated'. is it a desired behaviour ?

https://github.com/OCA/server-tools/blob/12.0/module_auto_update/models/module.py#L19

**Comment by pedrobaeza** [comment]
The problem here is the same problem when the other time it was factorized: you are going to add an extra dependency for current systems, and this is going to break them. Why not simply depend on this module? It's harmless if you don't trigger the update through one of the mechanism.

**Comment by legalsylvain** [comment]
Hi @pedrobaeza : thanks for your answer.

> Why not simply depend on this module? It's harmless if you don't trigger the update through one of the mechanism.

because it's an other feature. (computing hash for certification process). So, I don't see as a good idea to force users that want the certification module, to install a module they (maybe) don't want. (even if it is disabled by default and harmless).

> you are going to add an extra dependency for current systems, and this is going to break them

I don't understand why adding dependency will break current systems. Could you be more precise ? what is the "other time" ? Maybe I missed something.
But anyway, if it's not possible in stable version, we can imagine to create the new module for 12 version, and to mention in the roadmap of the module_auto_update that it should depends on the new generic module in V13.

**Comment by pedrobaeza** [comment]
Your idea is to split `module_auto_update` in 2 modules: `addon_hash` (I prefer `module_hash` any way), and `module_auto_update`, and make `module_auto_update` dependent on the first one. Current systems will break when updating as the new module is not installed (and even maybe not available).

Although I don't like to have to install 2 modules for the feature I use (auto-update), something tolerable can be:

* Extract hash feature from `module_auto_update` in `module_hash`, but keep this feature inside the module for versions <= 12.
* For version 13, rip out that feature, and make `module_auto_update` to depend on `module_hash`.

Is that acceptable for you?

P.S.: I mean by the other time when @sbidoul refactor this module as well from our first version.

**Comment by legalsylvain** [comment]
> (I prefer module_hash any way)

Yes. (Actually, I was proposing that name)

> Current systems will break when updating as the new module is not installed

I don't face this trouble. if i update a module A that depends newly from B that is not installed, the module B is installed automatically. Is not it ?

> (and even maybe not available)

Indeed, this point depends on deployment mechanism, but some of them are not resilient to adding new dependencies in a stable version. So I'm fully agree with you on that point. :+1: 

> Although I don't like to have to install 2 modules for the feature I use (auto-update),

Humm. That's not the design I promote. I like factorization ! For that purpose, I regularly propose abstract modules reused in many modules. [sql_request_abstract](https://github.com/OCA/server-tools/tree/11.0/sql_request_abstract), [barcode_generator_abstract](https://github.com/OCA/stock-logistics-barcode/tree/11.0/barcodes_generator_abstract)
but it's maybe a little a matter of taste. I like mixin.

> For version 13, rip out that feature, and make module_auto_update to depend on module_hash. Is that acceptable for you?

I agree ! good compromise. Thanks for that discussion.

**Comment by sbidoul** [comment]
> ./tests/*.py or demo/*.xml

@legalsylvain it's a safety-first approach, as it is not inconceivable that people would put database-changing stuff in these directories (although not advisable of course).

About splitting this module, well I don't remember the details but adding a dependency to it broke the auto update process. Actually it's another expression of this module failing to update correctly in various corner cases (such as updating a module that adds a field to res.users or res.partner). So I think I'll move the whole logic of this module to `click-odoo-upgrade` where it can work with a regular odoo `-u`.

So if we want to share the hashing algorithm it would need to go in a regular python package and not an Odoo addon. I'm not sure it's worth it though, it's only a few lines of code after all.

**Comment by sbidoul** [comment]
Ok, I did it: https://github.com/acsone/click-odoo-contrib/pull/27

It will be much more reliable without the need of an installed addon.

**Comment by yajo** [comment]
Interesting approach, @sbidoul, thanks!



> > For version 13, rip out that feature, and make module_auto_update to depend on module_hash. Is that acceptable for you?
> 
> I agree ! good compromise. Thanks for that discussion.

If this is good for you, I guess we can close this now. Thanks!
