### ISSUE TITLE
Mass Edit remove vendor

### ISSUE THREAD

**Issue by jayo2004** [OCA/server-tools#1432]
I am using Odoo 10. I need to remove and add new vendor to multiple products. The Model I am using is Product Template. I can Add vendors to products but I cannot remove Vendors. No errors just vendoe does not remove.

**Comment by pedrobaeza** [comment]
It's a one2many, so it's logical. Work at product.supplierinfo level with a module like `product_by_supplier`.

**Comment by jayo2004** [comment]
I installed product_by_supplier but sure what its suppose to do? Will it allow to mass change vendor?

**Comment by pedrobaeza** [comment]
Filter and remove lines you don't want. It's not mass-update. It's mass removal.
