### ISSUE TITLE
[9.0] [auth_admin_passkey] Error View inheritance may not use attribute 'string' as a selector.

### ISSUE THREAD

**Issue by alecvinent** [OCA/server-tools#1444]
On installing auth_admin_passkey for 9.0 I'm getting this error:

> Error details: View inheritance may not use attribute 'string' as a selector.

![auth_admin_passkey - error](https://user-images.githubusercontent.com/29969428/49611099-8d787280-f96e-11e8-8d9e-e190b7160b49.png)

**Comment by pedrobaeza** [comment]
Module is not migrated to this version, so it's normal that errors appear. That's why `installable` is set to False.
