### ISSUE TITLE
[11.0][database_cleanup] cannot drop inherited column

### ISSUE THREAD

**Issue by dcorio** [OCA/server-tools#1453]
I tried to run database_cleanup over a database migrated to 11.0 with openupgrade and getting this error:
psycopg2.ProgrammingError: cannot drop inherited column "openupgrade_legacy_11_0_usage"

Is this something that needs to be solved on the openupgrade's side?

Thanks

**Comment by pedrobaeza** [comment]
@dcorio there are several constraints that can prevent the module to drop the column, and that's not enforced for DB integrity. For example, if you a foreign key to other existing table with data.

@hbrunn what's your opinion on this?

**Comment by hbrunn** [comment]
I made it a habit to ignore bugreports which don't contain a proper backtrace and this way let me beg for the information necessary to say anything at all

**Comment by maisim** [comment]
database_cleanup try to drop  "openupgrade_legacy_11_0_usage" column on ir_act_server table
but ir_act_server table inherit this column from ir_actions so :
`ALTER TABLE ir_actions DROP COLUMN "openupgrade_legacy_11_0_usage";`
