### ISSUE TITLE
[10.0] Module onchange_helper - dict returned have wrong values to o2m fields 

### ISSUE THREAD

**Issue by mbcosta** [OCA/server-tools#1457]
Hi all
I am working in the PR https://github.com/OCA/account-invoicing/pull/320 , to create invoice from picking and would like to use the module onchange_helper to filled the invoice lines, but I noticed that the dictionary return have wrong values to o2m fields. When called the method:

                vals = invoice_id.play_onchanges(
                    {'picking_id': move.picking_id.id},
                    ['picking_id'],
                )

the dict returned is

{'tax_line_ids': [(5,), (0, 0, {'account_id': (14, u'111200 Tax Received'), 'sequence': 1, 'manual': False, 'name': u'Tax 15.00%', 'currency_id': (3, u'USD'), 'amount': 296.40000000000003, 'account_analytic_id': False, 'tax_id': (1, u'Tax 15.00%')})], 'invoice_line_ids': [(5,), (0, 0, {'uom_id': (1, u'Unit(s)'), 'account_id': (5, u'101120 Stock Interim Account (Received)'), 'analytic_tag_ids': [(5,)], 'move_line_id': (38, u'Test - account_invoice_from_picking/E-COM05: Stock>Customers'), 'price_unit': 247.0, 'sequence': 0, 'price_subtotal': 1976.0, 'company_id': (1, u'YourCompany'), 'currency_id': (3, u'USD'), 'discount': 0.0, 'product_id': (14, u'[E-COM05] Bose Mini Bluetooth Speaker'), 'account_analytic_id': False, 'invoice_line_tax_ids': [(5,), (4, 1)], 'quantity': 8.0, 'picking_id': (28, u'WH/OUT/00014'), 'name': u'Bose Mini Bluetooth Speaker'})], 'picking_id': 28}

The fields o2m need to be id not a list (  'currency_id': (3, u'USD')  ), if you try to write the values in this way you get error message, the dict should be like this 

{'tax_line_ids': [(5,), (0, 0, {'account_id': 14, 'sequence': 1, 'manual': False, 'name': u'Tax 15.00%', 'currency_id': 3, 'amount': 296.40000000000003, 'account_analytic_id': False, 'tax_id': 1})], 'invoice_line_ids': [(5,), (0, 0, {'uom_id': 1, 'account_id': 5, 'analytic_tag_ids': [(5,)], 'move_line_id': 38, 'price_unit': 247.0, 'sequence': 0, 'price_subtotal': 1976.0, 'company_id': 1, 'currency_id': 3, 'discount': 0.0, 'product_id': 14, 'account_analytic_id': False, 'invoice_line_tax_ids': [(5,), (4, 1)], 'quantity': 8.0, 'picking_id': 28, 'name': u'Bose Mini Bluetooth Speaker'})], 'picking_id': 28}

Maybe there is something I'm doing wrong. If it's a problem I can make a PR to try to fix it.

cc @rvalyi @renatonlima

**Comment by rvalyi** [comment]
Hello @mbcosta, according to @florian-dacosta this bug wouldn't be surprising as they tested only simples cases and none with an on_change returning o2m fields. So probably you should test if the field is a o2m and if it is you should kind of call recursively a convert function (using the current code) that would clean up the dicts of such o2m.
