### ISSUE TITLE
Module to manage user roles

### ISSUE THREAD

**Issue by sebalix** [OCA/server-tools#146]
Hi,

As a standard group is a notion a bit too technical sometimes, we developed a module to manage functional roles. A role is just an aggregation of groups. It helps us to manage a lot of user accounts over time without dealing with a collection of technical groups or "user template" account to duplicate when we need to create a new one (not really maintainable).
The code and description is hosted here: https://github.com/osiell/base_user_role/

I have not encountered similar modules, so I'm asking:
- is this module irrelevant? (we're missing a point or something within the standard functionalities)
- if not, is it interesting to maintain it in OCA? (in this repo I suppose)

Regards,

**Comment by matthieuchoplin** [comment]
Hi,

Maybe this module could do what you want: https://github.com/Smile-SA/odoo_addons/tree/8.0/smile_access_control

**Comment by sebalix** [comment]
Hi,
Thank you for sharing your work, this is exactly this kind of functionality we miss with Odoo.
I just tested your module, it works great! Sharing user fields is really useful (groups & home action especially).

I only miss one feature: apply several profiles on a user. I mean, a person could have many jobs in a company, each job giving access to menus/actions and so on. This combination of profiles can not really interpreted as a new profile to be linked to the relevant users I think (and it's not the purpose, as we want to combine them sometimes).

Do you plan to support this?
Your private/public fields feature is really interesting, maybe I could implement it in our own module instead.

**Comment by matthieuchoplin** [comment]
I am glad you find this module interesting. I think it is better to speak to @corentinpb about it as he is the main maintainer.

**Comment by yelizariev** [comment]
I can suggest my module 
https://apps.odoo.com/apps/modules/8.0/access_base/

It uses more simple approach. It just creates special category "Custom User Groups" and puts access groups of that category to the top of "Access Rights" tab of user form. 
So you create a group that is collection of a technical groups. And you can use that group as a role.
You can apply such role to your test user to check everything.
It allows to apply several roles for users.

**Comment by sebalix** [comment]
Your module is very similar to ours in fact. From what I see, the differences are:
- you always have the possibility to update groups of a user manually (a matter of taste, starting from several tens of users to manage we prefer to disallow this possibility, but this kind of behaviour could be optional),
- from your README you say _"Please note, that if you make changes in custom groups, then you have to repeat process of applying groups for each related users."_, is it still true or intented to work this way? This is one of our constraint to update user roles from time to time (as we develop features for our customers, sometimes several years after the first deployment) and the related users must be automatically updated.

In the meantime I improve our module (not pushed yet):
- a role inherits from `res.groups`, so when creating a role an associated group is automatically created, on which rules, menus and access rights can be linked, making the role just a convenient layer to manage only groups,
- the benefits to have a dedicated data model to represent groups is to separate concepts, and allowing in the future to define reports on it (exporting roles/groups/users/menus? on a Excel sheet to make the discussion easier during customers meetings)

**Comment by yelizariev** [comment]
@sebalix Thank you for review.

Note about non-automatical update is still true. Because as you mentioned it is posible to update users groups manually. So, if you delete some technical group from custom group, then that group would be kept in related users, because there is no way to figure out is it was added by inheritance or manually as a extra access to that user.

But you are right about the issue about automatic updates for tens users. Posible solution for my module is to add button "Update access rights according to custom groups" to user form and to "More" menu of user tree view.

> the benefits to have a dedicated data model to represent groups is to separate concepts, and allowing in the future to define reports on it (exporting roles/groups/users/menus? on a Excel sheet to make the discussion easier during customers meetings)

I think the same is possible for res.group. Just export custom groups only.

**Comment by pedrobaeza** [comment]
The modules is proposed, so I close.
