### ISSUE TITLE
[Bug] mass_editing - Search in ir.model.fields not working

### ISSUE THREAD

**Issue by OSguard** [OCA/server-tools#15]
I setup the mass_editing for res.partner then i go to:
Settings -> Technical -> Database Structure -> Fields
and go to the Filter with ('model_id','=',61) where 61 is the id of res.partner in res.model. By typ "res.partner" and select "Partner" from the suggestion.

Then i get the following error:
File "[..]/mass_editing/mass_editing.py", line 34, in search
    model_domain += [('model_id', 'in', map(int, domain[2][1:-1].split(',')))]
TypeError: 'int' object has no attribute '**getitem**'

**Comment by bwrsandman** [comment]
His @OSguard, could you post more of the traceback?
I would like to know what code calls `search()` in this instance.

It sounds like search was called with an int in place of the `domain` parameter.

**Comment by eLBati** [comment]
More info at https://bugs.launchpad.net/server-env-tools/+bug/1207671

**Comment by OSguard** [comment]
thanks is the same bug. i should check with google next time first.

**Comment by bwrsandman** [comment]
``` python
            if domain[0] == 'model_id' and domain[2]\
                    and type(domain[2]) != list:
                model_domain += [(
                    'model_id', 'in', map(int, domain[2][1:-1].split(',')))]
            else:
                model_domain.append(domain)
```

`type(domain[2]) != list` followed by `domain[2][1:-1]`
I guess it makes an assumption that `domain[2]` is a `str`, but in some cases, it's an `int`.

Is it possible that `domain[:3] == ('model_id', '=', some_int)`?
**EDIT**: just read the example and yes it is.

A saner way of checking would be to replace `and type(domain[2]) != list` by `and type(domain[2]) is str`

**Comment by bwrsandman** [comment]
Damnit, sorry. I commited directly instead of a PR because I have write access...

**Comment by bwrsandman** [comment]
There. Two PRs which should solve the issue, though I didn't test.
