### ISSUE TITLE
Annoying logs while using the shell

### ISSUE THREAD

**Issue by amrnegm** [OCA/server-tools#150]
I get interrupted while writing in the shell by the following logs:
openerp.addons.hw_escpos.controllers.main: ESC/POS Device Disconnected: Printer Not Found
openerp.addons.hw_escpos.controllers.main: disconnected : Printer Not Found

**Comment by dreispt** [comment]
I had a hard time installing hw_escpos, so I couldn't test the fix.
Can you try it?
