### ISSUE TITLE
[RFC] base_view_inheritance_extension: extend attrs domain

### ISSUE THREAD

**Issue by sbidoul** [OCA/server-tools#1516]
Would it make sens to make `base_inheritance_extension` aware of domain attributes. Something link this:

```xml
<attribute name="attrs" operation="domain_or" key="readonly">
    [(some domain)]
</attribute>
```

```xml
<attribute name="attrs" operation="domain_and" key="readonly">
    [(some domain)]
</attribute>
```

**Comment by pedrobaeza** [comment]
You have something similar already with the `list_add` and `list_remove` commands.

See also https://github.com/odoo/odoo/pull/26607 for my proposal in core.

**Comment by sbidoul** [comment]
@pedrobaeza I don't see how to update the readonly key inside the attrs dict with list_add. Moreover, supporting OR with list_add is not possible. Do I miss something?

**Comment by pedrobaeza** [comment]
You're right, for `attrs`, which is a dictionary with a list as value is not possible. A very specific case, but it would be better talking about inheritance compatibility. Normally people replace full `attrs` attribute.

**Comment by hbrunn** [comment]
that's what I meant with the `json_dict` operation from the roadmap, but the way I see it you would overwrite the key mentioned. The code would be more or less the same as for `python_dict`.

I don't think it's worth trying to allow logical operations here, because this will be unstable (as in depending on override order)

**Comment by sbidoul** [comment]
> because this will be unstable (as in depending on override order)

@hbrunn Is it more unstable than full overwrite?

**Comment by hbrunn** [comment]
well, a full overwrite give you something that works from the point of view of some module. `AND`ing two mutually exclusive conditions from two different modules gives you something that never works as expected. Both are bad, I agree, my argument is just that you'd spend time on something that still doesn't make modules play nice together
