### ISSUE TITLE
[8.0] logging_json: error on load

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/server-tools#1541]
When `jsonlogger` is [set to None](https://github.com/OCA/server-tools/blob/8.0/logging_json/json_log.py#L22), [this line](https://github.com/OCA/server-tools/blob/8.0/logging_json/json_log.py#L58) gives the following error:

```
AttributeError: 'NoneType' object has no attribute 'JsonFormatter'
```

**Comment by pedrobaeza** [comment]
That's logic, because you don't have the library, but that's why you have a logger line for knowing that the library is missing. It can be improved avoiding that, but I recommend you simply to not put full repository in that case in the addons path.

**Comment by thomaspaulb** [comment]
Okay the logger line is acceptable but an installation breaking on a missing package is not.. I thought OCA practice was to use try...catch statements to avoid anything breaking. "server-tools" is something almost everybody has in their build by default.

Anyway for me I have just added the package.. we could leave the issue open in case anyone wants to go and code a "try" statement. Or close it and people running into the same will know what to do.

**Comment by pedrobaeza** [comment]
The `try` is there. The problem is that the imported thing is a class, and it's used for inheriting, so a replacing class should be provided (something like object), and on a Python submodule it's not possible, so the code should be rewritten for not using that import and use a more specific one.

**Comment by hbrunn** [comment]
just assigning a mock object would work

**Comment by thomaspaulb** [comment]
Mock object would work but Pedro's suggestion seems more neat.. what do you think
