### ISSUE TITLE
[8.0] ImportError: No module named server_environment_files

### ISSUE THREAD

**Issue by sergiocorato** [OCA/server-tools#1546]
The last commits on repo re-create the issue on server_environment_files import, the problem is not present at 5ec40c3e47e8ab0fa090b4f51237a8673ce11d85

Error is ```ImportError: No module named server_environment_files``` as #89

**Comment by sergiocorato** [comment]
@pedrobaeza I didn't find a fast solution, some tips?

**Comment by pedrobaeza** [comment]
Sorry, but no, but why you don't simply put needed addons and not full directory to your addons path?

**Comment by thomaspaulb** [comment]
Am also getting the same issue here, will submit a fix.

**Comment by thomaspaulb** [comment]
@pedrobaeza For us that is difficult, we have not moved to git-aggregator yet but are still on Anybox buildout

**Comment by pedrobaeza** [comment]
Ok, @thomaspaulb that hurts to be heard :stuck_out_tongue_closed_eyes:

Move directly to Doodba (https://github.com/Tecnativa/doodba). You won't regret!

**Comment by thomaspaulb** [comment]
Yes yes, will think about it, but you know how the README says it's highly opinionated, so it affects my stubborn character to suddenly move to it and get Docker as a free present :-)

**Comment by pedrobaeza** [comment]
Well, opinionated doesn't mean inflexible. But the opinionated part is our 8 years accumulated experience implementing Odoo/OpenERP, so you will appreciate the design decisions we have taken.

**Comment by sergiocorato** [comment]
@pedrobaeza very good, this is for old installation that I don't touch

**Comment by pedrobaeza** [comment]
Yes, it was just an off-topic/advertisement, hehe

**Comment by thomaspaulb** [comment]
I appreciate all of it, if there was an "odba" version without Docker i would have probably already switched. Anyway, we are polluting this thread, you are utterly right, but for legacy reasons maybe OCA should also try to support including the whole `server_tools` repo.

Funnily, I just realized [one of your own commits](https://github.com/OCA/server-tools/commit/f0b86820008c8c3bdb2c177eb0a8bb9b3a8c9e11) did the same for 9.0.

So i backported that one and its parent to 8.0: https://github.com/OCA/server-tools/pull/1548

**Comment by pedrobaeza** [comment]
Yes, indeed I'm polluting this, so sorry for that, but all of this is because I have walked through this path, and that patch is because I did the same deployment techniques in the past with that problems, and now I have totally forgotten these things with new method. No more comments by my part on this. We can discuss in other part if you have interest in it.

**Comment by sergiocorato** [comment]
> Yes, it was just an off-topic/advertisement, hehe

:laughing:
