### ISSUE TITLE
Error in server_environment module while loading due an enforce of the usage of a non standard config option 

### ISSUE THREAD

**Issue by aek** [OCA/server-tools#1549]
The module server_environment is introducing a non consistent behavior into this repo that lead to this error already reported at the issue #690 
I don't think that a module should enforce anything like this over a non-standard config option. Also this error is happening at the Odoo load time because it's not checking if the module is installed or not. 
I think that modules like this should provide the functionality to be used when the config option is setted but leaving a clear path to the standard behavior if the config option is not present. Meaning that the features of this modules could just be ignored if the config option is not present at the Odoo config dict. Also they should be checked somehow per database to be sure that the module is installed or not because Odoo will load the __init__.py of the module always if the module is present in the addons_path

**Comment by gustavovalverde** [comment]
Just stumbled on this @lasley. This is causing a 500 Internal Server Error even when the module is not installed. Enforcing to set this parameter even if not needed, and just because the module is part of this repo. cc: @pedrobaeza
