### ISSUE TITLE
[12.0]excel_import_export_demo Can't download import xlsx template

### ISSUE THREAD

**Issue by youring** [OCA/server-tools#1574]
XLSX template not clickable for download. Step to reproduce on [rubot](http://3369151-12-0-6b6f14.runbot2-2.odoo-community.org/web?debug=1#id=21&action=257&model=sale.order&view_type=form&menu_id=138)
1. create a blank sale order, with customer selected( ready to save and trigger import action)
2. click Action, click Import Excel, notice the 'stop' sign in the popup.
![image](https://user-images.githubusercontent.com/4132418/57397605-afb53b80-71ff-11e9-8eb8-7ce9fa4d8b81.png)

ping @kittiu

**Comment by kittiu** [comment]
Thank you for reporting, I will take a look.

**Comment by kittiu** [comment]
On the wizard, we show the link to the download file by,
```
                            <field name="fname" invisible="1"/>
                            <field name="datas" filename="fname"/>
```
This was working on older version of Odoo (i.e., v8). But now it is not working in v12 (seem that framework itself block the link if wizard has no ID yet).

Meanwhile, I post it here to see if anyone know how to fix in correct way. 

Anyone know how to work with this Binary field on Wizard mode in v12?

**Comment by youring** [comment]
Hi Kittui, Maybe an extra Download button.
FYI https://www.odoo.com/fr_FR/forum/aide-1/question/binary-field-in-custom-wizard-can-t-be-downloaded-click-blocked-149149

**Comment by kittiu** [comment]
Oh thanks @youring we will check..

**Comment by kittiu** [comment]
@youring for some reason, I tested with recent odoo download and it works now. I think problem is fixed in core Odoo. Can you test with latest version of Odoo again, and let me know the result.

**Comment by youring** [comment]
Tested with latest commit https://github.com/odoo/odoo/commit/32603da5ba4ac601329561b7c107ec79a1f6a9eb
in two cases:
1. Source install on virtual env based on latest requirements.txt on Debian 9
2. Windows exe install

Not work either.
@kittiu Can you check your envirement again? Thanks.

**Comment by kittiu** [comment]
@youring here now I fixed it. Clicking the link first to get to download file.
https://github.com/OCA/server-tools/pull/1612

![image](https://user-images.githubusercontent.com/1973598/59758732-c946aa00-92b8-11e9-8c8b-94280b92b00b.png)

**Comment by youring** [comment]
Works like a charm! Hats off for your speed.
