### ISSUE TITLE
database cleanup delete views and fields created by odoo studion!

### ISSUE THREAD

**Issue by m3asmi** [OCA/server-tools#1580]
I installed the module in odoo v10 then I cleaned the database after that I found out that the fields and views created with odoo studio not existing anymore!

**Comment by pedrobaeza** [comment]
It can be, as the module is not intended to work with it as was created before that thing was born. You can add a PR for including a warning in the known issues part of the README.

I run away from Studio (but that's my personal opinion).

**Comment by sswapnesh** [comment]
Fixed in https://github.com/OCA/server-tools/pull/1632
