### ISSUE TITLE
Error when rule purchase order

### ISSUE THREAD

**Issue by jlsotomed** [OCA/server-tools#1588]
Good morning,

When I create a rule en auditlog for Purchase Order(it is saved without any problem), Then I get an error message when I try to create a new purchase order, it works well with other modules(Partner, Management).
![image](https://user-images.githubusercontent.com/51153923/58540619-052aaa00-81fa-11e9-9557-146fa1dcb8a0.png) if I delete the purchase order rule, it start working well again(I can create PO without any problem). Do you know what could be the problem?

Thanks in advance

**Comment by pedrobaeza** [comment]
Put the rule you have configured for trying to reproduce the problem.

**Comment by sebalix** [comment]
@jlsotomed I tried to reproduce your issue by creating a "full log" rule on `purchase.order` with the last `auditlog` version for Odoo 10 and all was working fine, no issue to create several orders one after the other.
Is the `_compute_is_group_admin` part of your code? I was unable to find it in the standard.

However, there is some pending fixes/changes regarding this part of the `auditlog` code for Odoo 11 (https://github.com/OCA/server-tools/pull/1686) and 12 (https://github.com/OCA/server-tools/pull/1688), we should backport it on Odoo 10 as well, and if ever it is related it could fix your issue.
