### ISSUE TITLE
[11.0] module_auto_update recreates menu items in restored db

### ISSUE THREAD

**Issue by zachwaite** [OCA/server-tools#1595]
To recreate: 
- Delete the home page from the navbar using the website frontend menu manager popup.
- Take a backup of the database, then restore into a new, but identical environment
- From the shell run env['ir.module.module'].upgrade_changed_checksum()

Note that the menu for home is recreated.

I'm looking for a way to preserve the menu layout without manually fiddling with menus when restoring.

**Comment by pedrobaeza** [comment]
This is not something of the module, but how Odoo works with updates and the several mechanisms (forcrecreate, noupdate, etc). You must use another technique for "hiding" the home page navbar.

**Comment by zachwaite** [comment]
Fair enough. Thanks!
