### ISSUE TITLE
how to install server tools for odoo 12

### ISSUE THREAD

**Issue by movahhed** [OCA/server-tools#1634]
hi dear how to install srver tools for odoo 12?

**Comment by pedrobaeza** [comment]
The same as you install other third party module. If you don't know it, please go to forums or mailing lists to ask.

**Comment by movahhed** [comment]
ok thanks
how install requirement.txt?

**Comment by movahhed** [comment]
i have odoo 12 into ubunto 18.04 lts

**Comment by pedrobaeza** [comment]
As said, you should do these questions on forums or mailing lists.

**Comment by movahhed** [comment]
where ? please send address

**Comment by pedrobaeza** [comment]
Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
