### ISSUE TITLE
excel_import_export relationship to report_xlsx

### ISSUE THREAD

**Issue by sbidoul** [OCA/server-tools#1658]
@kittiu I notice `excel_import_export` can also be used to create reports.
Would it make sence to make it depend on `report_xlsx` (from the reporting engine repo), to share the report type and some common logic?

**Comment by kittiu** [comment]
The method is quite different in the way excel os created. But i di try to propose the addon as discuss here.
https://github.com/OCA/reporting-engine/pull/313
Let me know if you have more comments, I am willing to do just worry it will make things more confused.
