### ISSUE TITLE
excel_import_export will this be migrated to v10.0 and v11.0?

### ISSUE THREAD

**Issue by smartapp-ep** [OCA/server-tools#1666]
query regarding module excel_import_export 

firstly, a big thank you for such a great module. 

1. is migration in the road map?
2. if not, could you please briefly advise what efforts is involved to do this?

many thanks

**Comment by kittiu** [comment]
@smartapp-ep no, port to v11 or v10 is not on our plan.
But we plan to migrate to v13 once it is out (python3).

However, this module is very independent (no addons dependency), you may try it with small fixes (If I not wrong, 2.7 and 3 just use different way to iterate for loop). If you can try with v11, and make a PR, I can help test / review :)

**Comment by kittiu** [comment]
@smartapp-ep I just see v11 is also python3, and so I already back port it.
https://github.com/OCA/server-tools/pull/1671
Would you review and test it? There are quite a number of changes from 12 to 11, so, your test will be helpful.

@pedrobaeza my first time to back port. I just do it as a new ADD, correct?

**Comment by pedrobaeza** [comment]
You have to use https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 for bringing commit history (or 12.0), but switching branches for doing the reverse.

**Comment by kittiu** [comment]
Ok. So I branch out of 12.0 to [11.0][MIG]?

**Comment by pedrobaeza** [comment]
The one that is most similar to 10.0 in code. I presume both are very similar, so take 12.0 as the original one. The idea is to get a separate commit for specific 10.0 changes needed for making it run in that version.

**Comment by kittiu** [comment]
@pedrobaeza thank you!
Redo -- https://github.com/OCA/server-tools/pull/1672
