### ISSUE TITLE
[11.0] BUG: Auditlog - related fields are not stored (with store=True)

### ISSUE THREAD

**Issue by vbezl** [OCA/server-tools#1676]
If I create a rule with Type="Full log" - some related fields are not stored to database (with store=True of course!) - they have null values instead.
If I use "Fast log" instead - they are stored just fine.
Anyone can help? (it took me a lot of time while I found that it was because of auditlog module!)
Thanks!

**Comment by sebalix** [comment]
It is the same issue that https://github.com/OCA/server-tools/issues/1134 (not clear here but the field in this issue is a related/computed one with `store=True`).
You can test this PR https://github.com/OCA/server-tools/pull/1686, it should fix your issue.
