### ISSUE TITLE
Where to place a module that adds groups on ir.values?

### ISSUE THREAD

**Issue by baimont** [OCA/server-tools#1734]
Hello,

I have a generic module originally developed by apineux that overwrites get_actions() on ir.values to add a Many2many groups_id, allowing to prevent users to see ir.values if not belonging to one of its group (if groups_id defined on ir.values). It was needed for me to hide some actions in the actions list.
I was wondering if server-tools would be the appropriate repo to propose this new module?

**Comment by legalsylvain** [comment]
Yes, server-tools is a good repository for such module.

**Comment by baimont** [comment]
> Yes, server-tools is a good repository for such module.

https://github.com/OCA/server-tools/pull/1735
