### ISSUE TITLE
records archiver lifespan example contacts

### ISSUE THREAD

**Issue by codeagencybe** [OCA/server-tools#1737]
Hello,

Can somebody help me on the records archive app please? 
I'm trying to auto archive old records for contacts, sale orders and pickings. 
I'm trying the contacts first, but nothing is happening. I set the lifespan to 6 months, state is empty as contacts done have a state like done or cancel.
Perhaps I need to enter something different here? 

And how to auto archive sale orders and pickings? Those models are not showing up in the dropdown. If somebody can point me in the right direction please with an example.

Thanks.

**Comment by guewen** [comment]
> And how to auto archive sale orders and pickings? Those models are not showing up in the dropdown.

These models do not have an `active` field. If you want to archive them, you'll need to add the field.

For the contacts, check that the cron "Records Archiver" is running. And look if you have some "Archiver error" in the logs.
Note that the lifespan is based on the `write_date`, so if something frequently updates records, they will not be archived.
