### ISSUE TITLE
base_fontawesome [v12.0]: fa-mastodon is not working

### ISSUE THREAD

**Issue by sudhir-erpharbor** [OCA/server-tools#1761]
I am looking for fa-mastodon icon on website but it is not working as you can see in the screenshot.

I tried it on runbot also and is not working on runbot also. Is there anything I need to install like extra fonts or something else?
@simahawk @etobella @pedrobaeza 
![font_mastodon](https://user-images.githubusercontent.com/7952467/73062162-c00e6300-3ec1-11ea-9f46-752d107741fa.png)

**Comment by etobella** [comment]
The current version of fontawesome of this module is  5.7.1 
but, the mastodon icon was introduced on 5.8.0

An upgrade of the module is necessary in order to introduce this icons.

**Comment by sudhir-erpharbor** [comment]
@etobella But in the [all.css](https://github.com/OCA/server-tools/blob/12.0/base_fontawesome/static/lib/fontawesome-5.7.1/css/all.css#L2467) I can see the style for this font.

How do we upgrade it? Can you please do that?

**Comment by sudhir-erpharbor** [comment]
Sorry guys for the noise. It's working with fab.

"fab fa-2x fa-mastodon" is working for the icon.
![fa_mastodon](https://user-images.githubusercontent.com/7952467/73075073-1b9c1900-3ee1-11ea-8180-4b1394dd6d3a.png)
