### ISSUE TITLE
10.0 Error Installing odoo10-addons-oca-server-tools

### ISSUE THREAD

**Issue by rauldb-br** [OCA/server-tools#1790]
Hi,
I have already install all the requirements and when i run : 

pip install odoo10-addons-oca-server-tools

i have these error : 

ERROR: Could not find a version that satisfies the requirement odoo10-addons-oca-server-tools (from versions: none)
ERROR: No matching distribution found for odoo10-addons-oca-server-tools

I dont know what to try.
A lot of thx peolpe.

**Comment by pedrobaeza** [comment]
server-tools is a repository, not a module. You must install a specific module.

**Comment by rauldb-br** [comment]
Thanks, i am new on this.
One question, EDI 10.0 is also a repository? i have the same error.
Thanks for the help.

**Comment by pedrobaeza** [comment]
Yes
