### ISSUE TITLE
version 10.0 not supported?

### ISSUE THREAD

**Issue by rsulym** [OCA/server-tools#1803]
hi, i'm wondering why there is no version for odoo10 while it is for 9 and 11? 
is there any obstacles with porting it exact for 10?

**Comment by rousseldenis** [comment]
@rsulym Could you please provide which module you are talking about ?

**Comment by StefanRijnhart** [comment]
@rsulym closing this because there was no response from your side. Please reopen the issue mentioning the name of the module if you like.
