### ISSUE TITLE
shell not running

### ISSUE THREAD

**Issue by AndreiHondrari** [OCA/server-tools#183]
I have tried `odoo.py shell -d <my_db_name>` and it doesn't do anything it just exits to bash.

**Comment by pedrobaeza** [comment]
Hi, how did you fix it?

**Comment by AndreiHondrari** [comment]
I executed it as `odoo.py --addons-path=<myaddonspath_where_shell_is> shell -d <mydbname>` it seems to work this way but I think I must add all the addons paths to fully work.

**Comment by pedrobaeza** [comment]
OK, it's for documenting purposes for other people with the same problem.

Thanks.
