### ISSUE TITLE
[12.0] Is there an addon to upload ir_attachment to AWS S3?

### ISSUE THREAD

**Issue by victoralmau** [OCA/server-tools#1864]
We have developed an addon called: **ir_attachment_s3** that through a cron (so as not to delay the process itself) quite frequently, of all the ir_attachment that exist of binary type (stored on the server) uploads them to AWS S3 (https://aws.amazon.com/s3/?nc1=h_ls) to a specific bucket such that they are stored as follows:
- bucket_name/model_name/model_id.format

Once the file is uploaded, the registry is replaced to save it as url with the path to the file.

This process also works when a file is deleted (it is also deleted from S3).

I think this functionality is useful as it frees up the server space. Before adding functionality to the community, I wanted to know if something similar already exists.

**Comment by pedrobaeza** [comment]
There's https://github.com/OCA/storage/tree/12.0/storage_backend_s3, but it's a bit coupled with other modules. Anyway, with the recently added DMS, I would wait for a general strategy on document storage.

**Comment by victoralmau** [comment]
Ok, I had seen the OCA / storage topic and I think it is something very very interesting.
As you say perhaps the best thing is to wait a little to see how that topic grows.
