### ISSUE TITLE
[AUDIT LOG] : DELETE LOGS PERIODICALLY

### ISSUE THREAD

**Issue by ccparrekh** [OCA/server-tools#187]
module: auditlog
version: 8.0

**Steps to reproduce**
- There Should Be an option to delete logs periodically i.e From Date to To Date.
  so that the unnecessary burden on Database can be reduced.

**Current behavior**
- There is no such functionality

**Expected behavior**
--> Reporting -> Delete Logs
Input  : From Date : 01/MAY/2015 to 31/MAY/2015
Click on Show : Get No of Records:
Click on Delete : Ask for Confirmation & Delete Entries.

**Comment by sebalix** [comment]
What about an `ir.cron` task which deletes logs older than X months (say 6 by default, or maybe disabled with 0)?
Deleting logs manually is always available in the tree view by searching them (filtered by dates, data model or users if needed).

**Comment by dreispt** [comment]
:+1: for the cron task, created with `noupdate="1"`

**Comment by sebalix** [comment]
This issue can be closed.
