### ISSUE TITLE
[RFC] enhancement of base_name_search_improved

### ISSUE THREAD

**Issue by kittiu** [OCA/server-tools#1870]
@dreispt I saw this wonderful module, and would like to extend its feature to search across multi lang.
As non English users, when using multiple language, it is quite necessary to do name search by local language, even we are on English context.

Should this be included, or as another module.
WDYT?

**Comment by dreispt** [comment]
Hello, I think it is a good feature.
It should be made optional, because it has a performance impact.
Probably it will be wiser to implement it in a new module. You're welcome to copy all you might need from the existing one.

**Comment by kittiu** [comment]
@dreispt So I might do it as an independent module, i.e., base_name_search_mult_lang. But ensure it can work together.
Thank you,

**Comment by kittiu** [comment]
PR: https://github.com/OCA/server-tools/pull/1873
