### ISSUE TITLE
[RFC] Enhancement to base_tier_validation

### ISSUE THREAD

**Issue by kittiu** [OCA/server-tools#1880]
We have the need to find a more flexible approval workflows engine. I want to try by extending this base_tier_validation first.

For example,

- [ ] Tier that does not require approval, but execute some action (i.e., python, write to model, send mail to multiple users), then by pass to the next step (by sequence)
- [ ] In addition to "Validate" and "Reject", i..e, now in step2, click "Request 2nd Opinion", and choose user, will insert new step2.1 in the table. Once the user validate it, will be back to step2 again to continue.
- [ ] Ability to undo the decision, if the next approver not yet validate.
- [ ] Document sub-state, i.e., can show on the report
- [ ] More status reports about the approvals.
- [ ] Audit trails, even if the flow is restarted.
- [ ] etc...

Sorry, it is still arbitrary ideas. But roughly, a more flexibility version of approval workflow.

I am not sure this should be proposed as separated module(s) to avoid making this module too complex for most case. Or propose it right in (to avoid difficulties).

cc @LoisRForgeFlow

**Comment by pedrobaeza** [comment]
Propose each one in a separate PR for discussing them.

For the first one, I think that should be automated actions, not something here in tier validation.

For the second, an "Escalate" option seems OK for me to be included here. It shouldn't act as a new tier, but a switch of responsible in current tier.

**Comment by kittiu** [comment]
Wrong repo, moved to https://github.com/OCA/server-ux/issues/192
