### ISSUE TITLE
when i try to install

### ISSUE THREAD

**Issue by Mamchaoui** [OCA/server-tools#1882]
this is the error that come when i try to install it , even i install the missing dependecy

Odoo Server Error - Warning
Impossible d'installer le module "auto_backup" à cause d'une dépendance externe non trouvée : No module named pysftp

**Comment by pedrobaeza** [comment]
You need that Python library.

**Comment by Mamchaoui** [comment]
i already install the python dependecy sir , but it don't work i don't know why!!!! ??

#odoo12 #windows10 #community

![Capture](https://user-images.githubusercontent.com/30203788/89909440-59e3f600-dbef-11ea-83ba-61b7ddd0f18f.PNG)

**Comment by pedrobaeza** [comment]
I don't think so, as if not, it won't complaint. In Windows, Python is embedded in Odoo folder. Anyway, this is out of scope of this issue tracker, so for further assistance, you should go to Odoo forums.
