### ISSUE TITLE
Call Function in Model to generate Excell

### ISSUE THREAD

**Issue by basri08** [OCA/server-tools#1884]
Hii Sir, 

i want to ask about how to use function in model to generate excel?. i have a function _sn_report() that call _recursive_task() function to generate pdf report. so i want to use them to generate excel report. have you solution for me ,sir? i need your help sir, thank you.
my attachments are function in model, i call it in views, and the report pdf.
![image (1)](https://user-images.githubusercontent.com/43989055/90304306-898d4980-dee0-11ea-8edd-4a6599176513.png)

**Comment by pedrobaeza** [comment]
Please do questions on forums. Here is for issues with the modules code.
