### ISSUE TITLE
[12.0] Missing oca_dependencies.txt?

### ISSUE THREAD

**Issue by BT-rmartin** [OCA/server-tools#1902]
I have seen this dependency in this module.
https://github.com/OCA/server-tools/blob/08ca4247175cda0a4a77d8919a7f43b285be735a/attachment_synchronize/__manifest__.py#L16

Wouldn't be necessary to add an oca_dependencies.txt file with the dependency to storage?

**Comment by legalsylvain** [comment]
Indeed. Could you make a PR ?
Thanks.

**Comment by BT-rmartin** [comment]
@legalsylvain PR created. Could you please push it to merge it asap? Thanks

**Comment by BT-rmartin** [comment]
Already merged in #1903
