### ISSUE TITLE
[12.0] scheduler_error_mailer: Email has never been succeeded to retrieve error message

### ISSUE THREAD

**Issue by novawish** [OCA/server-tools#1927]
Hi all,
As mentioned in the title, I am feeling kinda strange that nobody has ever had the same issue.
In the error email, the message is rendered by calling attribute `value` of object `job_exception`:
`${ctx.get('job_exception') and ctx.get('job_exception').value or 'Failed to get the error message from the context.'}`

Meanwhile in the Odoo core function `_handle_callback_exception`. The `job_exception` is supposed to be an **Exception** object. And it does not have `value` attribute, means it has never been working the entire time.
![image](https://user-images.githubusercontent.com/31387997/98834027-03c95d80-243f-11eb-87bc-e0ada152f348.png)

My current solution is just simply cast the `job_exception` to string (`str(job_exception)`). If anybody has different idea, feel free to give your opinion.

**Comment by victoralmau** [comment]
Hi, it's solved on 12.0 https://github.com/OCA/server-tools/pull/2262
