### ISSUE TITLE
[13.0] Enterprise Edition - auditlog messes with tokens assigned during RESET PASSWORD workflow

### ISSUE THREAD

**Issue by ray-odoo** [OCA/server-tools#1980]
Odoo Support resolved a token issue by uninstalling this module, you can see a video they sent to a Customer:

(video now removed since the issue has been replicated - it contains Odoo customer information)

I don't have any other details, just reporting in case it helps others.

The user is told "Invalid signup token" when visiting the URL sent to them during the process of clicking RESET PASSWORD which takes them to web/reset_password?

No issues after the module is uninstalled.

Odoo Ticket #2416144

**Comment by pedrobaeza** [comment]
Thanks for telling, Ray.

@sebalix @hbrunn you are 2 of the usual maintainers of such module, isn't it?

**Comment by sebalix** [comment]
Hi, thanks for the report. I tested the following scenarios on Odoo 13.0:

`audilog` installed without any configuration:

```
previous token = uAuHRfH7VlWLinn31Vi5
current token  = gxExrHKyPph6qfC7w0Xv
token in email = gxExrHKyPph6qfC7w0Xv
```

Full log create/write/unlink/read enabled on `res.users`:

```
previous token = ZZKuH96tZUK0qAfKTOYC
current token  = OZSiJ8BvAoq8FTNWyvjW
token in email = OZSiJ8BvAoq8FTNWyvjW
```

Full log create/write/unlink/read enabled on `mail.mail`:

```
previous token = aLAk6dJPfQnAnXf19bu1
current token  = 2zgSlslQUyD7FNqntJR8
token in email = 2zgSlslQUyD7FNqntJR8
```

Full log create/write/unlink/read enabled on `res.partner`:

```
previous token = 7Xk4M8C1ukiIpv3XhfWl
current token  = JqL0GBzqOEUlryr183on
token in email = 7Xk4M8C1ukiIpv3XhfWl
```
So I suppose it's related to the `signup_prepare` method on `res.partner`, I could check that later.

EDIT: the issue doesn't occur with a `fast` rule, only with `full`.

**Comment by ray-odoo** [comment]
Thanks for testing!   This looks like the Customer can still use the module if they don't have a full log setup on res.partner.

**Comment by Esalpi** [comment]
Hi,  i tested this core change, adding api.depends:

@api.depends('signup_token', 'signup_expiration')
def _compute_signup_url(self):

... in auth_signup/models/res_partner

With this modification it works fine.

The problem is in the function def write_full (self, vals, ** kwargs)
.. in role.py, when it reads the old values: the system recomputes the fields, then it no longer updates when it writes the record definitively

Now I don't understand if the bug is in the core or in the plugin.

**Comment by pnajman-modoolar** [comment]
Hi just went through the debuging session and wanted to report this issue :)
Anyhow, I came to the same conclusion as @Esalpi

IMHO this is bug in the auditlog module.
