### ISSUE TITLE
[12.0] auditlog: Access error when creating full log

### ISSUE THREAD

**Issue by TimLai125** [OCA/server-tools#1984]
Steps to reproduce:
1. Create an auditlog rule to `sale.order.line` with "Full Log" and log all the changes.
2. Create an user which only has the "Sale: User: Own Documents Only" group.
3. Login with the user and create a sale order with some order lines.

Current behavior:
Access error when user tries to save the sale order.
![image](https://user-images.githubusercontent.com/27185427/104016208-d4419200-51f0-11eb-8871-fb0c47c3a85f.png)

**Comment by atchuthan** [comment]
PR merged, we could close this issue.
