### ISSUE TITLE
RFC: Profiler refactor

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/server-tools#1989]
In #1986 I add a new way of profiling 'per user session per HTTP request'.

I want to change more things about the current 'profiler' module, for example:

1. Now we integrate with `pgbadger` and get slow queries from the Postgres log file. But I can also monkey patch `self.env.cr.execute` and get queries from there, timing them, and generating a logfile that can be downloaded and read by pgBadger. In that way we dont need to depend on Postgres logging settings, we generate our own logging. And we dont need pgBadger on host machine.
2. The original way of profiler works only for `workers=0` but, if I switch on a profiler for each available worker and there are for example 12 workers, I can generate 12 cprofile files and make them available for download. That is better than "restart Odoo with workers=0" message.
3. I want to add 'Profiler' security group so that any users added to there can start/stop a profiling session by a button in the top statusbar. They can use this in production and "record" slow actions that they are doing, for later analysis by programmers.

@moylop260 Can I ask for your opinion on these ideas?

**Comment by moylop260** [comment]
Hi @thomaspaulb 

It looks good to me

Currently we are using directly py-spy and postgresql.log but your idea looks good to me.

**Comment by thomaspaulb** [comment]
More ideas that came up:

- Let users send "stats" file over by email after a profiler session
- Integrated visualization so that users/clients who dont have command line fu can also visualize the stats file

**Comment by thomaspaulb** [comment]
These are cool ideas, but I'm not going to implement them any time soon - closing this.
