### ISSUE TITLE
Update Sentry SDK

### ISSUE THREAD

**Issue by themreza** [OCA/server-tools#2003]
We're using the Sentry integration module on Odoo 13.0 CE and it works fine.

However, we received an email from Sentry indicating the SDK may be updated to capture more data.

Is the current module easy to upgrade or is it a custom implementation?

![image](https://user-images.githubusercontent.com/5465057/106001409-36830980-60b0-11eb-83b5-01e74c7da5e5.png)

**Comment by hoangtrann** [comment]
There are some PRs to replace `raven` with `sentry_sdk`, you can check #1942
