### ISSUE TITLE
[10.0] auth_brute_force: incompatible with OAuth

### ISSUE THREAD

**Issue by TimLai125** [OCA/server-tools#2023]
**Steps to reproduce:**
1. Set up and allow Google OAuth2
2. Reset user's password with Google login
3. Use the "Log in with Google" to login

**Current behavior:**
Even for a successful login, the "Authentication Attempts" record shows "Failed"
Users who use "Log in with Google" to login, users can even log in even the user and IP address enter "Banned" state.

**Expected behavior:**
The "Authentication Attempts" record should show "Successful", the user should not be able to log in once he/she is banned.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/27185427/108067040-26e95600-709b-11eb-8cff-369dd8d58ad5.png)

**Comment by TimLai125** [comment]
@Yajo @legalsylvain any comments on this issue?

**Comment by legalsylvain** [comment]
Sorry. I dont use google oauth.

**Comment by yajo** [comment]
Sorry, I also don't use this module anymore... nor Odoo v10.
