### ISSUE TITLE
[14.0] apps.odoo.com status

### ISSUE THREAD

**Issue by simahawk** [OCA/server-tools#2134]
```
Module base_jsonify already exists for another serie. Please select a free module name or use the right user account.
Module onchange_helper already exists for another serie. Please select a free module name or use the right user account.
```
Indeed base_jsonify seems published only for v8 https://apps.odoo.com/apps/modules/8.0/base_jsonify same for https://apps.odoo.com/apps/modules/8.0/onchange_helper/
but seems not to be in control of OCA and that's why we cannot publish it for other versions.

@sebastienbeau @bguillot @hparfr  can you check?

**Comment by hparfr** [comment]
@bealdav can you please check ?

**Comment by simahawk** [comment]
Current status

Module onchange_helper already exists for another serie. Please select a free module name or use the right user account.
Module auto_backup for series 14.0 belongs to another repository. Please select a free module name or user the right user account.
Module base_jsonify already exists for another serie. Please select a free module name or use the right user account.

@hparfr @bealdav @sebastienbeau we should do something, especially because these modules might be used as base modules for other modules and this state blocks their publishing on the apps store for all them (eg: shopfloor*).

**Comment by hparfr** [comment]
ping @rvalyi

**Comment by simahawk** [comment]
@sebastienbeau @rvalyi piiiiiing :)

The module is already published here https://apps.odoo.com/apps/modules/8.0/base_jsonify/ and maybe you registered it manually?

In any case, I'm considering to move `base_jsonify` code to `jsonify_base` and make `base_jsonify` depend on this to preserve v13 and v14. Then in v15 we should kill `base_jsonify`.

**Comment by sebastienbeau** [comment]
@rvalyi can you remove it ?

**Comment by rvalyi** [comment]
> @rvalyi can you remove it ?

I answered your email, it seems I have no control over the module in the appstore sadly.

**Comment by sebastienbeau** [comment]
I found the right person, it was linked to david account.
The apps have been removed

**Comment by sebastienbeau** [comment]
can you try to publish the oca version ?

**Comment by simahawk** [comment]
still getting the same error "Module base_jsonify already exists for another serie. Please select a free module name or use the right user account." :sob:

**Comment by bealdav** [comment]
It requires 24h to be taken in account I suppose

**Comment by simahawk** [comment]
nada, the error is still there :sob: 

I'll try to get in touch w/ someone at Odoo SA.

**Comment by simahawk** [comment]
@bealdav sounds this is not moving anywhere. For `base_jsonify` I'd opt for renaming the module (eg: jsonifier).
To make a test w/ the apps store I have created an empty module to just try it out then I can move all the logic from base_jsonify to it and make it dependent on this new module. Example https://github.com/OCA/server-tools/compare/14.0...camptocamp:14-add-jsonifier?expand=1
If it's ok for you I'll go ahead.
CC @sebastienbeau

**Comment by sebastienbeau** [comment]
@simahawk crazy to have to rename a module, but if it's the only solution to solve it from odoo SA let's do it

**Comment by simahawk** [comment]
@sebastienbeau OTOH I find `jsonifier` more captivating :stuck_out_tongue_winking_eye:

**Comment by simahawk** [comment]
et voilá https://apps.odoo.com/apps/modules/14.0/jsonifier/

**Comment by simahawk** [comment]
There you go https://github.com/OCA/server-tools/pull/2327
