### ISSUE TITLE
About module auth_brute_force

### ISSUE THREAD

**Issue by rquevedo** [OCA/server-tools#2159]
Hi folks,
Anyone can tell me why this module "auth_brute_force" get stuck in v10? I need something like that in v13 and in can do the migration but before, i want to ask here to avoid migrate if functionality has been covered by odoo or other module in any way.
Thanks in advance,

**Comment by pedrobaeza** [comment]
There's a cooldown feature now native in Odoo, so no sense duplicated feature.
