### ISSUE TITLE
[14.0] MAKEPOT loop

### ISSUE THREAD

**Issue by lmignon** [OCA/server-tools#2191]
Since 2 jobs are declared into travis with MAKPOT=1, The result of generated pot diverge than the one from oca_transbot. Indeed, `base_changeset`, `base_autovacuum_message_attachment` and `base_name_search_improved`  introduces new fields on "base". As consequence, once installed, all the generated pot file will contains these fields. Pot are generated a first time for a restricted list of addons excluding these base addons, a second time for all the others addons and a third time by oca_transbot on a db will all the addons installed. As result, files generated by transbot are always different than the files generated by the first travis job on restricted list of addons.

**Comment by MiquelRForgeFlow** [comment]
@sbidoul

In branch 14.0 we have now a very long list of .pot updates:
![Selection_030](https://user-images.githubusercontent.com/25005517/140943564-dba43596-f434-4667-bdca-1be5fabc1cc8.png)

**Comment by pedrobaeza** [comment]
Can all modules be compatibilized for not requiring several builds?

**Comment by LoisRForgeFlow** [comment]
> Can all modules be compatibilized for not requiring several builds?

That would be ideal but sometimes unfeasible? 

Why don't we generate the pot in the last job with all addons and that's it? (this is putting MAKPOT=0, to the 2 travis jobs mentioned)

**Comment by sbidoul** [comment]
I dont' follow @lmignon's explanation. It seems that the .pot export is different from one run to the other ?

Maybe it's because `fetchmail_notify_error_to_sender` is installed in both travis jobs ? You can trying adding it to the rebel modules group.

**Comment by lmignon** [comment]
@sbidoul `fetchmail_notify_error_to_sender` is installed only in the first travis job. Since it add fields to base, all the others pot files from this first travis job will include these fields.  (But not pot files from the second travis job). Unfortunately transbot generate the pot files with all the repo addons installed. That means that pot files from the second travis job are updated with fields from `fetchmail_notify_error_to_sender`

**Comment by sbidoul** [comment]
I don't think the explanation is related to transbot (i.e. weblate), because all commits come from oca-travis (i.e. the makepot part of mqt in travis).

IIUC, fetchmail_notify_error_to_sender*_test* is installed in the first job, which pulls fetchmail_notify_error_to_sender as a dependency. And fetchmail_notify_error_to_sender is pulled as part of the second job. That's why I suggest adding fetchmail_notify_error_to_sender to the rebel modules group.
