### ISSUE TITLE
[ROADMAP] Configurable record display names

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#227]
# Purpose

Allow for non-technical configuration of record display names (`name_get()`)
A non-programmer can configure record display names buy adding a key in the system parameters table.

For example, setting `name_get.hr.employee` to `[%(code)s] %(name)]` would be enough to make employees to be displayes as `[0105] John Smith`.

**Comment by pedrobaeza** [comment]
Closing without feedback.
