### ISSUE TITLE
Auditlog does not work well in multi workers mode

### ISSUE THREAD

**Issue by sighefio** [OCA/server-tools#2288]
Audit Log rule does not applied in every worker in odoo worker mode

## Module
Audit Log

## Describe the bug
Logs are missing when I run odoo with worker mode on the first setting rule.(To work well, it needs to restart odoo server after setting rule)

## To Reproduce
13.0 (I think it is in every version) workers=5

1.Restart the odoo server with multi worker mode(more workers will make you to see the bug well).
2.Fresh install the auditlog module and set rule.
3.Then change the records(for example Contact that you choose in your rule). You will see some logs are missing but it works well after restarting the odoo server

**Expected behavior**
After setting rule, I don't want to restart odoo server to work well.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by lorenzomorandini** [comment]
@Laau-Kaung I'm facing the same problem.. did you ever solve it?

**Comment by mgielissen** [comment]
Same problem, Odoo needs restart after changing rules.
