### ISSUE TITLE
Create 8.0 branch and set as default

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#23]

**Comment by bwrsandman** [comment]
I have added a checklist here https://docs.google.com/spreadsheets/d/1CfGY7rc60jnpAWvMfNf0pI7fBDAlumwI2jx6f_RJ4_4/edit?pli=1#gid=0

(Number 10)

**Comment by pedrobaeza** [comment]
@gurneyalex Please, when you can, perform this task. There is only 1 PR against master, #34, that can be made again. Remember to change branch in tests.

Thanks.
