### ISSUE TITLE
ImportError: No module named ldap.filter

### ISSUE THREAD

**Issue by moylop260** [OCA/server-tools#233]
File "/home/travis/server-tools/users_ldap_populate/model/users_ldap.py", line 23, in <module>
    from ldap.filter import filter_format
ImportError: No module named ldap.filter

**Comment by yvaucher** [comment]
this should resolve it: https://github.com/OCA/server-tools/pull/232

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/server-tools/pull/232
