### ISSUE TITLE
[14.0] base_custom_info: contacts action buttons poor performance when a template is selected

### ISSUE THREAD

**Issue by dalonsod** [OCA/server-tools#2330]
Hello,
I've recently noticed an annoying performance issue when `base_custom_info` is installed and used in a contact.

## Module
`base_custom_info`

## Describe the bug
When a custom info template is selected for a contact, every action button related to it (like his sales or purchases) takes a lot of time displaying results. When the template is unset, good performance goes back.

## To Reproduce
**Affected versions**: v14 at least

Steps to reproduce the behavior (tested in Firefox and Chrome):
1. Select a contact.
2. Select a Custom Information template for it.
3. For the contact, click in e.g. Purchases => a lot of "Loading" messages appear, and finally Purchases is loaded several seconds later, even for a very small amount of purchases.
4. Remove the template and try again => selecting Purchase (or other) is as fast as expected again.

**Expected behavior**
Filling a Custom Information template should not affect other Contacts action.

**Additional context**
Tested on v14 runboat.

@kittiu @etobella @pedrobaeza have you noticed this issue using this addon?

**Comment by vmcr** [comment]
This is happening also in v13 with product.template

**Comment by etobella** [comment]
Thanks @dalonsod I found the bug and a way to fix it. PR is coming ASAP

**Comment by vmcr** [comment]
> Thanks @dalonsod I found the bug and a way to fix it. PR is coming ASAP

Is It comming for v13 too? Thanks!

**Comment by etobella** [comment]
First, we should see if it is reviewed and merged, isn't it?

**Comment by vmcr** [comment]
Sure! As the original issue was for v14 I didn't know if the fix would be applied retroactively. Sorry for the Rush!
