### ISSUE TITLE
[15.0] migrate module_change_auto_install to 15.0

### ISSUE THREAD

**Issue by kafai-lam** [OCA/server-tools#2400]
I find that module `module_change_auto_install` works perfectly (for me at least) in odoo 15.0

Is there any concern to move it to branch 15.0?

**Comment by legalsylvain** [comment]
Hi. feel free to propose a PR. I'll review it with pleasure.
kind regards.

**Comment by StefanRijnhart** [comment]
Closing issue as there is a PR. Thank you for the PR!
