### ISSUE TITLE
Change license of `onchange_helper` to LGPL

### ISSUE THREAD

**Issue by sbidoul** [OCA/server-tools#2542]
Hi,

`onchange_helper` is currently AGPL.

Since it is a low level technical module, often used together with component and connector which are LGPL, and useful to in bridging enterprise modules too, we would like to change it to LGPL.

As authors and contributors, do you have any objection to that @kevinkhao @florian-dacosta @alexis-via @astirpe @sbejaoui @sebastienbeau @bguillot @rousseldenis ?

**Comment by sbidoul** [comment]
cc/ @xavier-bouquiaux

**Comment by astirpe** [comment]
:+1: 
No objection!

**Comment by sbidoul** [comment]
@xavier-bouquiaux can you prepare the PR for this?
