### ISSUE TITLE
[15.0] fetchmail_notify_error_to_sender: mail template not migrated as should be

### ISSUE THREAD

**Issue by mof-landoo** [OCA/server-tools#2581]
We've seen that mail template of this module has not been migrated to v15.0 (`{{}}`)It's as the old format (`${}`) 

@JasminSForgeFlow @MiquelRForgeFlow @LoisRForgeFlow Can you check this please? 

Kind regards

**Comment by JordiBForgeFlow** [comment]
@mof-landoo fell free to propose a pull request with the fixes.

**Comment by chusamo** [comment]
I thnk this issue should be closed since the FIX PR is merged
