### ISSUE TITLE
Not always an record will be created - situation not duplicatable.

### ISSUE THREAD

**Issue by krijn1981** [OCA/server-tools#2713]
module: auditlog
version: 16.0

**Steps to reproduce**
- ...
No direct steps to reproduce

**Current behavior**
Sometimes the record will not create a record in table.
The developers telling us the problem is related with special workers.

**Expected behavior**

**Comment by legalsylvain** [comment]
Hi @krijn1981. Thanks for reporting.
Unfortunately, it seems difficult to investigate this outcome with such a vague description.

Feel free to describe the problem further and reopen the issue once you have done so.

Regards.
