### ISSUE TITLE
[16] base_sequence_default - Improve readme

### ISSUE THREAD

**Issue by Gelojr** [OCA/server-tools#2769]
**Is your feature request related to a problem?**
Add more information to the module readme to clarify its use and configuration.

**Describe the solution you'd like**
Modify the current Readme to include the following suggested changes

**Describe alternatives you've considered**
## Default Fields with Sequence
This module extends the standard functionality to create a sequence. The sequence will be added to the character type field of the selected template.

[Configuration]
1. Enable developer mode.
2. Go to the form view of the model to which you want to add the new sequential default value.
3. Hover over the field to which you want to add the sequential default value. A tooltip with more info will appear.
4. Make sure the tooltip says Type: char. Only those fields will work.
5. Take note of the Object and Field.
6. Go to Settings > Technical > Sequences & Identifiers > Sequences.
7. Create one sequence with code named after this pattern: `base_sequence_default.{object}.fields.{field}`. E.g.: `base_sequence_default.res.partner.fields.ref` to add a default sequenced reference for new partners. Do not use {} when adding the model and field name to the pattern
![image](https://github.com/OCA/server-tools/assets/147538094/ebf4be69-85d4-4c28-a3ec-bbe930fd53cf)
8. Configure the sequence at will.
![image](https://github.com/OCA/server-tools/assets/147538094/e3eb311b-738f-4fce-9af5-a1b592908704)

[Usage]
To use this module, it is necessary to:
1. Follow the configuration instructions.
2. Create a record of the model you configured.
3. Leave empty the fields where you configured a sequence. If they are required fields, set value to "-" to trigger the automatic sequence on creation.
4. Check that the field defined in the sequence is set to the next value in the sequence.
![image](https://github.com/OCA/server-tools/assets/147538094/82698762-6ac2-4ac0-89ba-7c9b32ea5909)

@moduon MT-4324 @yajo

**Comment by yajo** [comment]
Fix in #2770
