### ISSUE TITLE
problème d'installation module auditlog

### ISSUE THREAD

**Issue by Imedhorra** [OCA/server-tools#2783]
S'il vous plaît, je ne parviens pas à installer un module auditlog, car ce message d'erreur apparaît à chaque fois.

![auditlog eurreur](https://github.com/OCA/server-tools/assets/85850407/8582392c-619a-413a-a93e-c9ba273ea877)
module: auditlog
version: 14.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by legalsylvain** [comment]
You can not install oca modules via import feature. You should install via classic way.

Note : reporting issue should be done in english.

Kind regards.
