### ISSUE TITLE
Auditlog does not log changes to Reordering Rules if user does not hit "enter" or click "Save".

### ISSUE THREAD

**Issue by tci-jeremiah-dyck** [OCA/server-tools#2832]
module: auditlog
version: 16.0

**Steps to reproduce**
- ...Configure rule to log changes made to model stock.warehouse.orderpoint.
- Make changes to reordering rule, then click elsewhere on the page, or navigate to a different page. Do not click save, or hit enter.

**Current behavior**
Auditlog is only logging changes in stock.warehouse.orderpoint if the user clicks save, or hits enter.

**Expected behavior**
It should log the change when Odoo automatically saves the changes made when the user clicks elsewhere on the page, or navigates to a different page.

**Comment by AungKoKoLin1997** [comment]
@tci-jeremiah-dyck I can't reproduce this issue in runboat. Are you using the latest odoo code?
This is how I tested.
https://drive.google.com/file/d/16bol9LGzbJkpTnLtP11zfAKOfuCTTH3j/view?usp=sharing
