### ISSUE TITLE
[15.0] base_fontawesome: broken icons when updgrade

### ISSUE THREAD

**Issue by zamberjo** [OCA/server-tools#2835]
## Module
base_fontawesome

## Describe the bug
Since https://github.com/OCA/server-tools/pull/2787 there are icons that no longer display well.

## To Reproduce
Go to any form and see **Print** or **Action** button (Make sure that the latest version of the module is installed.)

For example before the upgrade 
![image](https://github.com/OCA/server-tools/assets/4418005/be0bd65e-85d2-4d09-a812-066eda757cb8)

and now
![image](https://github.com/OCA/server-tools/assets/4418005/8d35a448-8733-48be-9fab-ab48bdcb5747)

ping @gurneyalex @Abranes @ozoromo

**Comment by ozoromo** [comment]
Just created a fix PR which can be found here:
https://github.com/OCA/server-tools/pull/2836
