### ISSUE TITLE
[auth_admin_passkey] allow to use database password to log in

### ISSUE THREAD

**Issue by rvalyi** [OCA/server-tools#285]
Hello,

auth_admin_passkey rocks. But sometimes we the ERP operators don't know the encrypted admin password and it would not be a good thing this password to be sent between ERP admin and system integrator when it is changed as it might be leaked...

We also need to limit the number of secrets that may represent a security risk if they are leaked.

Now if the database server has a password set, then the ERP operator will know it and this password is already enough to compromise all the ERP data if it's used by the operator in a malicious way.

That's why I propose that this database password could be used by the ERP operator in place of the admin password. I mean both passwords would be valid and allow connecting as any user.

If you agree I can make the PR (and port this to v9). Deal accepted?
What do you think @legalsylvain ?

**Comment by pedrobaeza** [comment]
What are you thinking about? Flag a user with an operator or similar check?

**Comment by rvalyi** [comment]
@pedrobaeza my goal is to help a system integrator (like us; what I called an ERP operator) to log as a specific user, for instance to debug access right issues.

auth_admin_passkey helps but it still requires the system integrator to know the admin password or reset it; this is annoying. My proposal is that an other secret that is known already by the system integrator could be used in place of the admin password, to log as any user. Such an existing secret is the database_password from the configuration file.

Eventually I'm also open to introduce yet another optional secret via an environment variable for the people that would like this feature but don't use a Postgresql password (they probably use 'same ident' then).

**Comment by pedrobaeza** [comment]
Well, I see my proposal more flexible: you can flag the user you want as ERP operator, and thus allow to login with any user also with these users' passwords.

**Comment by rvalyi** [comment]
hum...

**Comment by rvalyi** [comment]
they kinda become sudoers of the ERP...

**Comment by rvalyi** [comment]
I like it too let's call your idea the "delegation feature". Well may be we can implement both systems. My system hardly introduce any security leak because it uses an existing secret of equivalent power.

Your system is really powerful indeed, specially if you consider two "admin" support companies for a single ERP. But it still has the requirement to store extra passwords somewhere (so possibility of leak) and it also requires the burden of populating the newly created database with these admin users.

Also there is a catch with your delegation feature: you cannot let a user flag itself as an admin. As there is still no field level security in Odoo (I believe), this means it cannot be just a flag in the res_users table, or well in any case care must be taken.

So what about implementing both features? I propose to keep it in the same module as it's really simple to implement. Like my feature is 1 or 2 lines and yours is may be 10...

**Comment by pedrobaeza** [comment]
OK for me, go ahead!

**Comment by legalsylvain** [comment]
Hi @rvalyi and @pedrobaeza,

Glad to see that this module is interesting you.
Your ideas seems very good !

Two little points.

About @rvalyi idea (use config['db_password']) what about to enable this feature, depending of a new ir_config_parameter. (There are 2 for instance [ir_config_parameter](https://github.com/OCA/server-tools/tree/9.0/auth_admin_passkey/data) ? 
- by default to false, to let admin user to enable or not this new feature ; 
- in demo data to True to let users to test more easily ; 

about @pedrobaeza idea (is_sudoer boolean), we can:
- create a new group : "auth_admin_passkey.sudoer_applicant";
- restrict access of "is_sudoer" boolean to this new group ; 
- set base.admin_user to this new group ;

What your PoV ?

Regards.

**Comment by rvalyi** [comment]
@legalsylvain yes, I agree with both ideas. I was already thinking about doing it this way in fact.

**Comment by pedrobaeza** [comment]
:+1: for me too

**Comment by gurneyalex** [comment]
@rvalyi I'm joining a bit late. I'm surprised by the proposal to use db_password as a key which is not related to odoo to start with. Why not admin_passwd or some new key in the configuration file? 

(I'm not opposed to the proposal, just wondering)

**Comment by rvalyi** [comment]
Hello @gurneyalex:
" Why not admin_passwd [...] ?"
-> because often we don't set such a password so db admin from the UI is disabled. We think it's more secure: it avoids the attack surface of a possible bug in the db mgmt controller and it avoids having an extra dangerous password that can be leaked.

"[...] or some new key in the configuration file?"
-> as much as possible we want to avoid having several passwords with a lot of power. Indeed you just multiplies the risk of one password being leaked and having the whole thing compromised.

Now depending on how you install Odoo the db_password is already here and and if the sysadmin has it it can already compromise the whole ERP, so using it as a key doesn't really increase the attack surface.

Now. some other installations don't use db_password. In that case, we could think about using an other key.

So what about changing my PR to use an other key f configured OR used the db_password if not?
Also generally it's bad to put secrets in a configuration file, and better to have them in an ENV VAR (in our case we tend to inject the db_password ENV VAR with sed before starting if you wanted to know). so instead of adding a key in the configuration file, we could allow to specify an ENV VAR to use. What about this?

**Comment by gurneyalex** [comment]
I'm not unhappy with db_password :smile_cat:, I was just inquiring to get a better idea of the rationale for the choice you made. Even for installations where db_password is not required (e.g. relying on ident authentication) providing it should do no harm. As long as the  README clearly explains this, I'm happy.

**Comment by pedrobaeza** [comment]
I close this as there's no feedback.
