### ISSUE TITLE
Separate tools into different repos

### ISSUE THREAD

**Issue by YoussefAbady** [OCA/server-tools#2855]
**Is your feature request related to a problem?**
It's very difficult to add the whole repo as a submodule due to huge size and many tools. It would be way better to have each repo in a different repo

**Describe the solution you'd like**
Separate each tool in a stand alone repo

**Comment by legalsylvain** [comment]
hi @YoussefAbady. Sorry I don't understand your point. What do you mean by "each repo in a different repo" ?

**Comment by pedrobaeza** [comment]
I suppose he's saying "each module in a different repo", and the short answer is no, but this repo is very light in size comparing with for example Odoo, and on each version, it's restarted for not dragging size burden, so what I don't get is the problem.
