### ISSUE TITLE
[AUDITLOG] and property fields

### ISSUE THREAD

**Issue by ghost** [OCA/server-tools#305]
AuditLog (branch 8.0 (5f99ef17)) did not log write in property fields in case superuser company is different from user company

property field is company dependent:

ff = fields.Many2one(
        string='Label',
        comodel_name='aaa.bbb',
        company_dependent=True
    )

---

your code:

def _make_write(self):
        """Instanciate a write method that log its calls."""
        @api.multi
        def write(self, vals, *_kwargs):
            self = self.with_context(auditlog_disabled=True)
            rule_model = self.env['auditlog.rule']
            old_values = dict(
                (d['id'], d) for d in self.sudo().read(list(self._fields)))
            result = write.origin(self, vals, *_kwargs)
            new_values = dict(
                (d['id'], d) for d in self.sudo().read(list(self._fields)))
            rule_model.sudo().create_logs(
                self.env.uid, self._name, self.ids,
                'write', old_values, new_values)
            return result
        return write

self.sudo().read - it read data for superuser and if current user company is different from superuser company new_values contains the same values for property fields

how to fix:
1 way

just use self.read

2 way (but i did not sure that this is right way)

def _make_write(self):
        """Instanciate a write method that log its calls."""
        @api.multi
        def write(self, vals, *_kwargs):
            self = self.with_context(auditlog_disabled=True)
            rule_model = self.env['auditlog.rule']
            ctx = dict(self._context)
            ctx.update(force_company=self.env.user.company_id.id)
            old_values = dict(
                (d['id'], d) for d in self.sudo().with_context(ctx).read(list(self._fields)))
            result = write.origin(self, vals, *_kwargs)
            new_values = dict(
                (d['id'], d) for d in self.sudo().with_context(ctx).read(list(self._fields)))
            print new_values
            rule_model.sudo().create_logs(
                self.env.uid, self._name, self.ids,
                'write', old_values, new_values)
            return result
        return write

**Comment by sebalix** [comment]
You are right, `sudo` only is not enough in a multi-companies environment.
About your fix, I think this should be ok:

``` python
company_id = self.env.user.company_id.id
old_values = dict(
    (d['id'], d) for d in self.sudo().with_context(
        force_company=company_id).read(list(self._fields)))
[...]
```

Do you want to make a PR for this? And maybe a unit test on this bug?

**Comment by ghost** [comment]
def _make_create(self) - has the same problem

about fix:

it seems way with with_context(force_company=company_id) is wrong

it works with property fields but not in case of one/many2many fields - sudo().read() takes linked records from all companies (i mean if *2many field contain link to records in model with multicompany rule)

may be just use self.read() ?
or here are some problem and it needs sudo() ?

**Comment by sebalix** [comment]
I put `sudo` here to bypass any potential problem with access rights to make the data snapshot, we need to be sure that removing `sudo` will not introduce a regression. Unless there is another option to fix this.
To start working on this, it would be nice to reproduce the bug with a unit test, and then find a proper fix. I'll dig this point when I have time.

**Comment by pedrobaeza** [comment]
As this is already included, I close.
