### ISSUE TITLE
[9.0] dbfilter_from_header Works without modification from 8.0 Version

### ISSUE THREAD

**Issue by lukebranch** [OCA/server-tools#319]
@pedrobaeza ,

I've been testing this module (8.0 version in 9.0 branch) and have only needed to switch it from:

'installable': False

to:

'installable': True

and the module seems to work without any issues.

Are there any plans to change this flag to allow for installation in 9.0, or does this particular module require further unit testing in order to ensure it is fully compatible?

**Comment by elicoidal** [comment]
@lukebranch Please propose a PR with the necessary modifications in README + **openerp**.py
We usually take the opportunity to cleanse to new standards when relevant (eg: headers, new API)
We can fasttrack it if necessary

**Comment by lukebranch** [comment]
@elicoidal ,

Thanks, i'll send a PR as soon as possible with the changes.
