### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by cmsalmeida** [OCA/server-tools#326]
Using the scheduler error mail, how can we get the error message to add it in mail template.

**Comment by eLBati** [comment]
Hi @cmsalmeida , it is already included. See https://github.com/OCA/server-tools/blob/8.0/scheduler_error_mailer/ir_cron_email_tpl.xml

```
<strong>
${ctx.get('job_exception') and ctx.get('job_exception').value or 'Failed to get the error message from the context.'}
</strong>
```
