### ISSUE TITLE
restricting field access per field, per record, depending on other values

### ISSUE THREAD

**Issue by hbrunn** [OCA/server-tools#332]
Hi all,

we've come far already with field access restrictions, but I'm not aware of a general and simple way to restrict access to fields based on values of the record (I'm not talking about the UI, but hard restrictions you can't circumvent).

I'm tinkering with a mixin that is supposed to make this task easy: https://gist.github.com/hbrunn/776143edc5e5f6e08367

With this, the following code is sufficient for my client to have only a couple of fields of the partner model readable/editable if the current user is not either the partner's salesperson or in the sales team assigned to the partner (the latter are custom fields):

``` python
class ResPartner(models.Model):
    _inherit = ['restrict.field.access.mixin', 'res.partner']
    _name = 'res.partner'

    @api.multi
    def _restrict_field_access_get_field_whitelist(self, action='read'):
        whitelist = [
            'name', 'parent_id', 'is_company', 'firstname', 'lastname',
            'infix', 'initials',
        ] + super(ResPartner, self)\
            ._restrict_field_access_get_field_whitelist(action=action)
        if action == 'read':
            whitelist.extend(['section_id', 'user_id'])
        return whitelist

    @api.multi
    def _restrict_field_access_is_field_accessible(self, field_name,
                                                   action='read'):
        result = super(ResPartner, self)\
            ._restrict_field_access_is_field_accessible(
                field_name, action=action)
        if result or not self:
            return result
        return all(this.section_id in self.env.user.section_ids or
                   this.user_id == self.env.user
                   for this in self)

    @api.multi
    @api.onchange('section_id', 'user_id')
    @api.depends('section_id', 'user_id')
    def _compute_restrict_field_access(self):
        return super(ResPartner, self)._compute_restrict_field_access()

    @api.model
    def _restrict_field_access_inject_restrict_field_access_domain(
            self, domain):
        domain[:] = expression.AND([
            domain,
            [
                '|',
                ('section_id', 'in', self.env.user.section_ids.ids),
                ('user_id', '=', self.env.user.id),
            ],
        ])
```

simple enough, right? Note that we can have a different set of fields writable than readable.

Now my questions:
- am I doing something stupid and similar functionality exists already?
- I'm inclined to polish the mixin a bit and PR it as a module here, do we want that?
- any features missing?

**Comment by hbrunn** [comment]
ping @gurneyalex @pedrobaeza @StefanRijnhart - I'd be curious about your opinion on this one

**Comment by hbrunn** [comment]
@all I'm just as curious about your opinions too of course

**Comment by pedrobaeza** [comment]
Hi, @hbrunn, you can define record rules to restrict operations depending on a domain, which is similar to what you are doing. Have you checked that option? What I don't know is how multiple record rules mix together.

**Comment by hbrunn** [comment]
@pedrobaeza in my project, I use record rules on top of that. Record rules restrict which _records_ a user can execute an action on, but here, the requirement is that users are allowed to see all partners, but only specified fields. And it has to be a hard restriction as opposed to just hide some fields in the UI (this can be circumvented by using xmlrpc or the like)

How multiple record rules mix is as follows:
- all group-specific record rules are combined with `AND`
- all not group-specific record rules are combined with `OR`
- the two above are combined with `AND`

This has the sometimes counter intuitive result that adding a user to a group actually makes her see less records.

But well, another topic, let's keep talking about field level access restrictions ;-)

**Comment by pedrobaeza** [comment]
Hi, Holger, thanks for the explanation about the record rules. Indeed, I read very fast and didn't take into account about your intention of protecting only certain fields, not at record level.

Commenting on the code you present, I would't put a whitelist, but allow all the fields by default. On contrary, each module that adds a field will need to explicitely inherit your mixin and add itself to whitelist.

I also don't understand why you need two methods to deal with the restriction: _restrict_field_access_inject_restrict_field_access_domain and _restrict_field_access_is_field_accessible

**Comment by hbrunn** [comment]
Thanks for your points. The whitelist is indeed quite specific to the customer, I think in the end there'll be a function for a whitelist and one for a blacklist, both empty, and if the user (=programmer) doesn't fill one of them, nothing happens.
`_restrict_field_access_inject_restrict_field_access_domain` allows you to rewrite the `attrs` attribute on a form, `_restrict_field_access_is_field_accessible` is a helper function programmers can use to have the logic about whether a field is accessible or not at one central place.

**Comment by pedrobaeza** [comment]
OK, I like then the possibilities this brings. You can make a server-tools module or wait for another opinion, but I think this deserves a module.

**Comment by tungocbui** [comment]
@hbrunn i did not take a deep look at your code, but i really like the idea. For us, in some projects we need to create some function fields to store values and do the restriction based on these function fields. I'm looking forward to see your module ;)

**Comment by hbrunn** [comment]
I made a PR in #396, so I'll close this one

**Comment by cuongnmtm** [comment]
I am revisiting this after 10 years. Thank you for the base_mixin_restrict_field_access module.

I would like to know whether there is an alternative, as I do not see this module being migrated to recent versions. Specifically, I am looking for a way to configure field-level access so that only certain user groups can access a field when the record matches a given domain. Basically, field-rule instead of record-rule.

Thank you in advance.

**Comment by hbrunn** [comment]
I'm not aware of anything like that, so you'll want to migrate the PR mentioned here I guess
