### ISSUE TITLE
Odoo runs much slower with auditlog module installed

### ISSUE THREAD

**Issue by wim-a** [OCA/server-tools#339]
I installed the auditlog module in our Odoo 8 application.

Since this module is installed, the Odoo runs much slower. One of my own developed processes runs less than 2 minutes when the auditlog is uninstalled, but with the auditlog installed it takes about 90 minutes.

I have rules installed for 30 models (f.e. partner, product, product variant, accounts, invoices, journal entries and items, purchase orders, manufacturing orders), and for each of these modules, I log writes, deletes, and creates. I never log to reads.

**Comment by sebalix** [comment]
Hi Wim,

If you do not need to log everything starting from a specific method, you can control the log creation with the context key `auditlog_disabled`. Auditlog itself uses it to not log its own operations (https://github.com/OCA/server-tools/blob/8.0/auditlog/models/rule.py#L213).

Another feature I would like to add is to choose the log level for each rule:
- Full log: make a snapshot of the data before/after the CRUD operation and logs the difference, as it is now. It is slow, but even computed fields are logged if they change.
- Fast log: just log the `vals` dictionary for `write` and `create` operations. There is no snapshot of the data before/after, so it should be very fast.

**Comment by wim-a** [comment]
Thanks, Sébastien, I'll change my own module for auditlog_disabled. 

I like fast log feature (certainly for some of the models), would it be a big change to the existing module?

About the full log and computed fields, do you mean that also not-stored computed fields are logged?

**Comment by hbrunn** [comment]
@wim-a technically, he does a `read()` on all records twice, so yes, if you have expensive computed fields, they are probably the culprit. If you have control over the code and are not interested in the computed fields anyways during logging, check for the context key @sebalix mentions in your function and do nothing then.

Make sure you use a version with https://github.com/OCA/server-tools/pull/301 (merged to main branch three weeks ago) merged, this eases the pain already a lot in some cases.

The fast log sounds like a very good idea, I don't think that costs more than a couple of hours to implement.

**Comment by wim-a** [comment]
Thanks for the info, Holger. How can we proceed for having the fast log feature available?

**Comment by hbrunn** [comment]
Ask your favorite Odoo programmer to quote this new feature for you, and let them do it if you like their offer

**Comment by wim-a** [comment]
Sébastien, Holger,

I've modified the code of the auditlog module on my server for fast logging.

In this version, it works as follows:
- The auditlog_rule table has an additional field action_rule in which the system administrator can define if this model is full or fast logged.
- For each action (create, read, write, unlink), there are now 2 patch methods defined, one for full logging, and one for fast logging.
- In case of fast logging, only the vals data is written to the log line.

After making this change, and defining all of my logged models as fast logged (which is currently the default value), my own process, which was running 90 minutes with full logging, is getting back to 2 minutes (as with the auditlog module uninstalled).

I'll send you a tar file with this version of the module. If you want, you can apply these changes also in published version of the module.

Best regards,

Wim

**Comment by hbrunn** [comment]
@wim-a how about a PR? It's simple, just follow steps 4 and following from https://odoo-community.org/page/code

**Comment by sebalix** [comment]
I received your tar.gz (but no time to look at it now). If you are not familiar with Git/GitHub process, I will create it later with your development.

Thank you

**Comment by wim-a** [comment]
I’m not familiar with it. It would be good that you also review the code. Maybe you want to do some things another way.

**Comment by sebalix** [comment]
Indeed, there will be a code review, this step is mandatory to push updates to OCA modules.

**Comment by hbrunn** [comment]
I didn't receive any code, but if @sebalix has it, that's good enough. You should give explicit permission to publish your code as AGPL with the OCA modifications (cf https://odoo-community.org/page/faq, heading 'Licenses & CLA'), otherwise, we can't integrate it with the standard code

**Comment by hbrunn** [comment]
meanwhile, I close this issue as it seems to be resolved

**Comment by wim-a** [comment]
I give you permission to publish my code.
Best regards,
Wim

**Comment by dreispt** [comment]
@wim-a I think signing the CLA is mandatory: https://odoo-community.org/page/cla
You should considering investing few hours trying a Git PR. As a programmers these are skills that you will need sooner nor later. Remember that we are here to help.

**Comment by vcloud9ray** [comment]
FYI https://github.com/OCA/server-tools/issues/974 - auditlog - log_id on table auditlog_log_line is missing an index - DELETE WON'T FINISH due to missing index.
