### ISSUE TITLE
Log viewer in Odoo interface

### ISSUE THREAD

**Issue by bwrsandman** [OCA/server-tools#35]
Is there a module out there which can show the output of Odoo logs inside a Odoo view?

If not, I feel this would a very important module to make for Odoo admins who do not have access to host filesystems.

There are cases where Cronjobs fail silently (no error message in the interface) and it would be great to be able to see the logs and even to filter them by level.

This is an example in gitlab:

![gitlablog](https://cloud.githubusercontent.com/assets/1013356/3843309/335d5fc2-1e3f-11e4-9008-b5c798419f3f.png)

Implementation hints:
- http://opensourcehacker.com/2011/02/23/temporarily-capturing-python-logging-output-to-a-string-buffer/
- https://docs.python.org/2/library/collections.html#collections.deque
- https://docs.python.org/2/library/logging.handlers.html

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Very good idea.

Can this be a part of:
https://code.launchpad.net/~camptocamp/server-env-tools/7.0-monitoring/+merge/215138 ?

**Comment by StefanRijnhart** [comment]
That would absolutely be a great asset. Looks like a good basis too for a module that I've been thinking about which would be able report any occuring exceptions to an external channel (mail or xmlrpc message)

**Comment by bwrsandman** [comment]
@gurneyalex could you port the MP on https://code.launchpad.net/~camptocamp/server-env-tools/7.0-monitoring/+merge/215138

**Comment by gurneyalex** [comment]
@bwrsandman yep, will do. Thanks for reminding me of this :smile_cat:

**Comment by gurneyalex** [comment]
@bwrsandman see #39

**Comment by bwrsandman** [comment]
In v8, one can enable `--log-db=DBNAME` and logs will be in the interface under Technical Features
