### ISSUE TITLE
[qweb_usertime] Separate the hour and date.

### ISSUE THREAD

**Issue by xt0ph** [OCA/server-tools#358]
Hello,
This module is a great job, but I met a problem when using it, in fact he does not just provide the date in the language of the user (or I did not find how). So I wrote a small patch that adds / changes:
- Does userdate: for the Date
- Does userdatetime: for Date and Time
- Does usertime: for the Time

Are you intrested by this patch?

**Comment by pedrobaeza** [comment]
Please do a PR with these improvements.
