### ISSUE TITLE
auth_brute_force does not use forwarded IP address

### ISSUE THREAD

**Issue by RoelAdriaans** [OCA/server-tools#381]
When you install the auth_brute_force module, and have odoo behind a proxy is only registered attempts from 127.0.0.1. It does not use the forwarded IP. 

The module server-tools/log_forwarded_for_ip does logging, can we copy the same code used there?

Changing https://github.com/OCA/server-tools/blob/8.0/auth_brute_force/controllers/controllers.py#L37 is probably enough.

**Comment by hbrunn** [comment]
shouldn't this be fixed by setting `proxy_mode` to `True` in your server configuration?

**Comment by RoelAdriaans** [comment]
You are right @hbrunn  . Searching Odoo for the places where Odoo uses proxy_mode revealed my error.
The http proxy key that Odoo uses X-Forwarded-HOST and the Forwarded-for IPs uses X-Forwarded-For as http header for the source of the ip address..

Should I open a bug for that? :)

**Comment by hbrunn** [comment]
at most places, Odoo just delegates that to werkzeug which handles `proxy_mode`. So if you found an instance where werkzeug is circumvented and `proxy_mode` not respected, you should file a bug.

The two header you write about are supposed to do something entirely else though: `X-Forwarded-Host` is the the _host_ name the client requested, while `X-Forwarded-For` is the _client_ ip and eventual proxy IPs in between: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
