### ISSUE TITLE
cannot cancel uninstalling module by closing confirmation dialog

### ISSUE THREAD

**Issue by grexe** [OCA/server-tools#388]
(see also related forum thread https://www.odoo.com/de_DE/forum/hilfe-1/question/modules-marked-as-uninstalled-server-fails-to-start-99268)

When clicking "uninstall" in the apps/modules list, a confirmation dialog came up that lists dependent modules that would be uninstalled along with the module selected for uninstallation.

When trying to abort by clicking the close icon (didn't try with "Cancel" yet...), the action is still executed, and the module as well as all related modules are marked for uninstall.

While it is possible to unmark the modules from uninstallation, the web interface stopped working after 3 or so modules, and restarting the server just gave me this error (tried to uninstall the discussion module which has dependencies on all the other core modules, which I don't understand and think is a bug):

> ParseError: "The ID "sales_team.team_sales_department" refers to an uninstalled module" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/crm/crm_data.xml:16, near
> 
> <record model="crm.team" id="sales_team.team_sales_department">
> <field name="use_leads">True</field>
> <field name="alias_name">sales</field>
> </record>

Using Debian Linux 8.3/testing with latest nightly as of today and PostgreSQL 9.5.

The only way to restore my installation was to run the server with the "--update=all" option.

**Comment by pedrobaeza** [comment]
Sorry, but this doesn't correspond to this project. Please put it in odoo/odoo.

**Comment by grexe** [comment]
oh I'm sorry, sure, trying to find the right module in the Odoo ecosystem is not easy for newcomers,-)
