### ISSUE TITLE
[8.0][base_report_auto_create_qweb] duplicate report linked to a custom parser

### ISSUE THREAD

**Issue by tafaRU** [OCA/server-tools#390]
The module **base_report_auto_create_qweb** doesn't work properly when the report that your are trying to duplicate is linked to a custom parser, see https://github.com/odoo/odoo/blob/8.0/addons/account/report/account_print_overdue.py#L87 as reference.

Steps to reproduce:
- duplicate the report **Due Payments**, use test as suffix;
- select a partner and launch the report **Due Payments (test)**

Current behavior:

It raises the following error:

```
File "/home/tafaru/dev/envs/buildout/customer/parts/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: ""'NoneType' object has no attribute '__getitem__'" while evaluating
"addresses[o.id].replace('\\n\\n', '\\n').replace('\\n', '<br>')"" while evaluating
"translate_doc(doc_id, doc_model, 'lang', 'account_test.report_overdue_test_document')"
```

This is because https://github.com/odoo/odoo/blob/8.0/addons/account/report/account_print_overdue.py#L45-L54 are still related to the old parser.

During the duplication we need to search for reports that have linked a custom parser and create a new one accordingly the new report name. [1]

@oihane @pedrobaeza any hints how to do [1]?

**Comment by pedrobaeza** [comment]
@oihane, can you check this question?
