### ISSUE TITLE
shell can't use..on odoo v8...

### ISSUE THREAD

**Issue by jaronemo** [OCA/server-tools#395]
Dears:

install this shell module .....
but can't use on my server....I don't know why!!

![image](https://cloud.githubusercontent.com/assets/8476734/13877356/37377ac0-ed45-11e5-8aca-9b9ea17b44fe.png)

**Comment by pedrobaeza** [comment]
You should use:

```
python odoo.py --addons-path=<your_addon_path> shell --config=<your_config_path> -d <database>
```

Maybe a better documentation in the README (or simply put this would be good)

**Comment by sign-josh** [comment]
I've been reading through Daniel Reis' "Odoo Development Essentials", and I was super-excited to try out this shell module, but I'm not having any luck. At first, it'd just exit right back to bash, but using the command @pedrobaeza gave, I get the following: `odoo.py: error: unrecognized parameters: 'shell'`

I've tried running from the directory of odoo.py, but nothing seems to help. It either immediately exits or claims it doesn't recognize the parameter.

I'm using the config file that the server is using -- is that right?

**Comment by pedrobaeza** [comment]
shell is without dashes. You have to install the module "shell" in Odoo v8

**Comment by sign-josh** [comment]
I had the shell module installed, just couldn't get it to run. Finally got it working by leaving out the config file setting. It seems like the order of arguments is pretty important. Thanks --
