### ISSUE TITLE
auditlog, not compatible with auth_signup odoo standard module

### ISSUE THREAD

**Issue by oremacle** [OCA/server-tools#421]
Not compatible with this method (auth_signup/res_users.py):

`sef signup_prepare(self, cr, uid, ids, signup_type="signup", expiration=False, context=None):
        """ generate a new token for the partners with the given validity, if necessary
            :param expiration: the expiration datetime of the token (string, optional)
        """
        for partner in self.browse(cr, uid, ids, context):
            if expiration or not partner.signup_valid:
                token = random_token()
                while self._signup_retrieve_partner(cr, uid, token, context=context):
                    token = random_token()
                partner.write({'signup_token': token, 'signup_type': signup_type, 'signup_expiration': expiration})
        return True`

That cause impossible send email_template:
Write a record auditlog tries to log old and new values, and when it's reading those values function field is computed and it tries again to write, so it calls auditlog and so on and on

**Comment by sebalix** [comment]
Hi,

It is not common to trigger an ORM `write` on a fields.function, I wonder if there is a good fix for that.

Two quick solutions:
- choose the _Fast log_ type on your rule (it prevents to perform the `read` operations to fetch old/new values, it will log the raw values and speed up the log process)
- you can override the `signup_prepare` method and pass the key `auditlog_disabled=True` in the context before calling `super` (but this way the `write` method to store the token will not be logged).

**Comment by oremacle** [comment]
Hi sebalix,

Thanks for solutions!

**Comment by fferreras** [comment]
I override signup_prepare method and deleted 'signup_valid' from context. before calling super.
