### ISSUE TITLE
[Blueprint] Data Import Queue

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#422]
Use an ORM Model/database table as a queue for data imports,
loadable both by RPC or by SQL Inserts.

1) An External process loads records into an Import queue table.
Either by standard RPC or by direct SQL Inserts.
These loaded records include:
- model name, the target
- data text field, containing a CSV-like data content

2) Records created through the ORM are immediatlety processed. 
Records inserted through SQL are processed by a scheduled job, by creation order.

3) The processor routine handles the pending records in the queue,
trying to load them with the `load()` method.
If successful, marks the record as done.
If unsucessful, marks the record as errored, and writes the error message to a log field.

Related work:
- [import_loader](https://github.com/dreispt/odoo-addons/tree/8.0/import_loader) implements a similar feature
- [base_import_match](https://github.com/OCA/server-tools/pull/420) implements a solution for primary key surrogates

**Comment by dreispt** [comment]
cc @Yajo @guewen : does this make any sense to you?

**Comment by yajo** [comment]
My module just allows you to detect updates by other fields than the XMLID, does nothing with the import scheduling. It can be an interesting feature for those importing big amounts of data, but you have to send a notification on import failure/success then.

However this does not seem very easy given the current UI/UX. i.e. How do you "validate" an import asynchronously?

**Comment by pedrobaeza** [comment]
This already exists on https://github.com/OCA/connector-interfaces/tree/8.0/base_import_async (also migrated to 9.0).

**Comment by dreispt** [comment]
@pedrobaeza I took another look at it, but AFAICS it is not enough to cover the use cases described here:
- creating a base.import record through RPC is not enough, you need another RPC call to perform the import; 
- same issue goes for scheduler driven imports: a wrapper method needs to be implemented to do run the actual `do` method.

Also, the async capability provided by the module is not relevant for the use cases above, since imports will run in their own processes, not in a GUI session. So the wrappers suggested could perfectly be built on top of the standard `base.import`, without depending on the Connector.

Now, reusing `base.import` instead of a specific queue table sounds like a good improvement over the original design above. Maybe adding it a "load immediately" flag, triggering the `do` method right after the `create`, would be a good solution.

**Comment by pedrobaeza** [comment]
OK, I don't see the use case for this task, but no matter, if the provided module is not enough for it, go ahead with the specs in this issue.

**Comment by sbidoul** [comment]
@dreispt something like this https://github.com/OCA/connector-interfaces/blob/56f045fbcdd53861772c6ef0b769904b134a1500/test_base_import_async/tests/test_base_import_async.py#L65 with a chunk size of 1 will do something very similar to your scenario.

**Comment by pedrobaeza** [comment]
Closing as there is an implementation of this blueprint.
