### ISSUE TITLE
[8.0][auto_backup] Empty dump using sftp backup option

### ISSUE THREAD

**Issue by Daniel-CA** [OCA/server-tools#428]
Hello,
I was trying to use the auto_backup module to do automatic backups in a different server using sftp connection, but even if the connection to the sftp server is right done and the dump file created it is empty (size 0).
I was thinking that maybe it could be because the `tempfile` python library used to create the temp file, for some reason maybe it is not populated and it does the dump empty in the sftp server.

**Comment by jabibi** [comment]
I confirm this issue. If I get a momment I will pull the fix

**Comment by jabibi** [comment]
There it is: #432 
Enjoy
