### ISSUE TITLE
[8.0] web_context_tunnel doesn't work anymore

### ISSUE THREAD

**Issue by atchuthan** [OCA/server-tools#431]
We were trying to migrate web_context_tunnel for version 9.0, but found that this module was not working.  So, we tested it in OCA runbot for 8.0 and it failed.

Runbot URL: http://3147379-8-0-aae74f.runbot1.odoo-community.org/web?db=3147379-8-0-aae74f-all

![image](https://cloud.githubusercontent.com/assets/4667326/15392194/3d7c2524-1de3-11e6-8932-4deb865c4dca.png)

![image](https://cloud.githubusercontent.com/assets/4667326/15392199/42768ac4-1de3-11e6-9bee-8b2d6e65e3eb.png)

context: {'test_field1': 'my_extra_field'}
context_test: {'test_field2': 'my_extra_field'}

**Current Behaviour:**
context not updated. context is {'test_field1': 'my_extra_field'}

**Expected Behaviour:**
context updated and output in form view needs to be 
context: {'test_field1': 'my_extra_field','test_field2': 'my_extra_field'}

cc: @rvalyi @yvaucher @sbidoul

**Comment by atchuthan** [comment]
closing the issue as this functionality doesn't work if we use new api onchange

More info: https://odoo-community.org/groups/contributors-15/contributors-41001?mode=thread&date_begin=&date_end=

**Comment by yvaucher** [comment]
This module shouldn't be useful with new api onchanges
