### ISSUE TITLE
Letsencrypt with nginx

### ISSUE THREAD

**Issue by kenneth-vkd** [OCA/server-tools#447]
Hi
We have downloaded and installed the letsencrypt module, but are unable to get it working. We have installed the required python modules and openssl binaries, but no certificate seems to come back on the CSR and the private key is there.
Does anyone have a sample nginx configuration file that I can compare to our version or is there somewhere I can look to find out why this is not working?

**Comment by hbrunn** [comment]
the log files of odoo when the cronjob to request a certificate runs

**Comment by kenneth-vkd** [comment]
Found the solution. It seems as if the module does not filter the system parameter web.base.url, so that it removes the port number.
I had to manually remove the port number and then install the module to generate the correct certificate key and request and then I got the certificate and everything worked.

**Comment by fgarcia-humanoide** [comment]
I have the same problem. No crt file.

What is remove the port number?
I have http://subdomain.domain.com in the web.base.url

Will  the problem be fixed with ip in web.base.url ?

**Comment by kenneth-vkd** [comment]
@fgarcia-humanoide normally when you first install Odoo with no nginx proxy, the web.base.url would be http://subdomain.domain.com:8069 and in my case this was not removed before trying to generate the certificates, so the generation failed.
But if your web.base.url is already correct, then your issue could also be related to an incorrect nginx configuration file. You can find a sample configuration file here: https://github.com/OCA/server-tools/issues/570#issuecomment-253150228

**Comment by fgarcia-humanoide** [comment]
I am using apache. 
Thanks
