### ISSUE TITLE
[8.0] Module base_concurrency conflics with auth_ldap

### ISSUE THREAD

**Issue by astirpe** [OCA/server-tools#453]
The module base_concurrency overrides the login function:
`def _login(self, db, login, password):
`

One of the consequences is that the ldap authentication provided by module auth_ldap doesn't work anymore.

Steps to reproduce:
1. Install module auth_ldap and configure Odoo to allow users to be authenticated by ldap credentials
2. Login Odoo as a user by using ldap credentials (and verify that user logs in successfully)
3. Install module base_concurrency
4. Try to login with the same user by the same ldap credentials (user is not able to login)

Note:
Verified on v8.
I didn't test on previous versions of Odoo, but I guess the same problem would occur.

**Comment by moylop260** [comment]
@astirpe 
Thanks for reporting...

Do you have a traceback from the console log (try use `odoo.py --log-level=debug ...`?

**Comment by astirpe** [comment]
@moylop260 Not any traceback is displayed from the log when attempting to login. If you reproduce the problem (step 4) you simply get this message at the login page: "_Wrong login/password_".

**Comment by moylop260** [comment]
@charbeljc @mdietrichc2c 
Please, Could you review this issue?

**Comment by pedrobaeza** [comment]
Anyw news on this?

**Comment by mdietrichc2c** [comment]
Seems the only solution here would be to modify `base_concurrency` so that its `login` method doesn't inherit the base one, but replaces it as well via monkey-patching.
I'm guessing the issue comes from the fact that in the module, the `login` method is redefined instead of extended (which is unfortunately needed).
