### ISSUE TITLE
[8.0] base_name_search_improved, problem with domain of many2one filed.

### ISSUE THREAD

**Issue by kittiu** [OCA/server-tools#476]
As I install this seemingly useful module (with out any configuration yet). Domain stop working properly.
For example,
In Supplier Payment, the payment method should display only Cash or Bank. Now, it display every journal.
It does affect many fields not just payment method.

**Comment by dreispt** [comment]
In theory I proposed a fix.
In practice, it should be confirmed.

**Comment by kittiu** [comment]
Thanks Daniel

I have tested with my server, it looks good now. :+1:

**Comment by dreispt** [comment]
Fixed by #478
