### ISSUE TITLE
disable_odoo_online 

### ISSUE THREAD

**Issue by CHsonia** [OCA/server-tools#479]
i want to install just the module disable_odoo_online .

what do I have to do?

**Comment by elicoidal** [comment]
Hi,
You will have to download the repository and copy the module you want in 
your instance.
To download you can type in command line:
git clone git@github.com:OCA/server-tools.git
or go to the page https://github.com/OCA/server-tools and click on 
"clone or download" button

I will close the issue in the meantime but do not hesitate to open it 
again if necessary

**Comment by CHsonia** [comment]
Hi,
Thank you for your reply.
I already did as you said.
But when I try to install it from the command line, I got this error:
TypeError: 'NoneType' object has no attribute '**getitem**'
Can you help me,Please.

**Comment by elicoidal** [comment]
Can you provide the version of the server, OS, version of the downloaded module and any relevant information that might help us debugging the issue?

**Comment by CHsonia** [comment]
I installed ubuntu 14.04 on 9 Odoo.
I use Python file and name it 'install_module.py', importing ERPpeek.

Example:
import erppeek
client = erppeek.Client('http://localhost:8080', 'ErpPeekDemoDatabase', 'admin', 'admin')
modules = client.modules('sale', installed=False)
if 'sale' in modules['uninstalled']:
    client.install('sale')
    print('The module sale has been installed!')

**Comment by CHsonia** [comment]
sorry Odoo9 on ubuntu-14.04

**Comment by elicoidal** [comment]
Can you provide full log of the error (the traceback part?).
Are you sure the error is related to this module?

**Comment by elicoidal** [comment]
Can you provide full log of the error (the traceback part?).
Are you sure the error is related to this module?

**Comment by pedrobaeza** [comment]
I'm using the module without problem, so it's not related.
