### ISSUE TITLE
[9.0] base_export_manager

### ISSUE THREAD

**Issue by max3903** [OCA/server-tools#491]
This module adds a new column to access rights to enable/disable export and override the export method to check if the user is allowed to export. Export is enabled by default.
# Configuration
- Activate the developer mode
- Go to Settings > Users > Groups to select a user group
- Edit the group and go to the Access Rights tab
- Uncheck the "Can export" box on the object of your choice and save

You can also go to Settings > Technical > Security > Access Rights.
# Usage
- Connect as a user of the previous group
- Go to the list view of the object you disabled the export
- Select records and open the Action menu. The "Export" is not there.

**Comment by pedrobaeza** [comment]
Isn't better to add this in https://github.com/OCA/server-tools/tree/8.0/base_export_manager?

**Comment by max3903** [comment]
@pedrobaeza We need this feature in version 9 and did not plan to migrate base_export_manager.
@smangukiya Can you make the migration fit into the estimate?

**Comment by lasley** [comment]
Hi @max3903 - I have already completed the migration of base_export_manager here - https://github.com/OCA/server-tools/pull/483

May I suggest we rename that module to base_export then provide both functionalities in the same module?

**Comment by max3903** [comment]
@lasley :+1:

**Comment by smangukiya** [comment]
@max3903 : Well, there is no more migration needed for base_export_manager right? We will stick to base_export feature(i.e. which is mention above) at the moment,

**Comment by max3903** [comment]
@pedrobaeza @lasley PR is ready for review.
