### ISSUE TITLE
Quick-merge of a bunch of debranding modules

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/server-tools#504]
You have merged all of this stuff tonight (*_enterprise_remove) including the SVG icon that it's not needed. Now, the repository is going to contain a diff history adding them and lately removing it, making very big (well, bigger than before). The only solution is to amend the commits, but this means that some people making git pull will receive an error. What do you think?

cc @rvalyi @elicoidal @bmw95 @lasley

**Comment by elicoidal** [comment]
@pedrobaeza We indeed did not pay attention on the svg file (shame).
I would suggest that @bmw95 fix it now with a PR removing the file and that we fast merge them (rest of the code was OK AFAIK).
What do you think?

**Comment by pedrobaeza** [comment]
You haven't read the problem, Eric. Now we have added several MB of diffs adding these SVG and removing them. This size will doom us for now on, as we don't reset history through versions. We are talking about 10 MB (as the SVG contains an image) of diff. This is an unneded waste of bandwidth and not very ecological by our part. That's why I suggest an amending.

**Comment by elicoidal** [comment]
ok: understand now.
Agree with your PoV

**Comment by woodbrettm** [comment]
@pedrobaeza Hmm I'm not sure I'm quite following here. Why is the svg not needed?

**Comment by pedrobaeza** [comment]
Because you haven't altered it, so the template one is enough if you want to make any modification.

**Comment by woodbrettm** [comment]
Interesting. Based on the template module that included the svg, I assumed to always include it. I'll get the remaining 3 pull requests fixed right now at least.

**Comment by lasley** [comment]
@pedrobaeza you are right that an amend would be the best way to fix this, and you are also right it will cause an error for anyone that has pulled before then. IMO this has less far-reaching consequences assuming we handle it today, so would probably be worth doing. Is @bmw95 able to do this without write on the repo?

I am still slightly confused here. To confirm- we should only be adding the PNG OCA icon into our repos? I fear that I have added this SVG in many places 😦

**Comment by pedrobaeza** [comment]
Yes, we only need to include the SVG if the design is different, and thus, we need to include the source. This is only for preventing the proliferation of verbatim copies of the same file as something not needed for the module working itself.

OK, I'll do the removal then.

**Comment by lasley** [comment]
This makes perfect sense, thanks for the elaboration @pedrobaeza . I'll make sure this info makes its way to my team + internal docs, and will try to figure out some verbiage for the contribution guidelines as well. 

TBH this is the first I've heard of this; I now feel bad for the SVGs that were accepted in some of my other previous PRs. I will go through my outstanding ones today to make sure there is no SVGs.

**Comment by pedrobaeza** [comment]
I have just removed the SVGs from tonight merges, as well as the one for base_export_manager, that was merged before. Now you just need to make this to let the branch usable again:

```
git reset --hard HEAD~30
git pull
```

**Comment by rvalyi** [comment]
sorry I didn't spot the svg redundance either.

**Comment by rvalyi** [comment]
I also agree it's better to have amended the commits. Sadly this is also the kind of things that makes the Odoo repo itself so heavy too unless you clone it shallow...

**Comment by elicoidal** [comment]
@pedrobaeza @rvalyi @lasley Shouldnot we remove the svg from the template?
For me it is a marketing material that should be made available in some directory but not in the template itself (only the png is necessary).
We will avoid future mistakes and endless discussion and reviewer time about removing it...

**Comment by lasley** [comment]
I agree- it was my understanding that the template module should directly correspond with what our modules should end up looking like. IMO it is misleading to have other files in a folder called `template`.

**Comment by pedrobaeza** [comment]
Yes, that can be helpful, but where do we put it then?

**Comment by pedrobaeza** [comment]
Maybe we can rename it to a more helpful name like `icon_template_(do_not_copy_to_your_module).svg`.

**Comment by elicoidal** [comment]
I would rather create a directory "Resources" or "Material" in the MT repo with all icons, svg, etc. that might be useful for contributors.

**Comment by pedrobaeza** [comment]
The problem with that is the visibility of that resources folder. For now, I prefer to rename the file.

**Comment by lasley** [comment]
I'm ok with a rename, particularly because I cant think of anything else to go in that folder other than the SVG.

Maybe asking for too much of a perfect world here - I wonder what the viability of adding a check into CI to validate that if an `icon.svg` file is included, validate against the checksum of this known file, and error out with a note suggesting rebase. @moylop260 you're probably the best person to ask on that one, yeah?

**Comment by moylop260** [comment]
We have many [README.rst](https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst) referenced to the url with the following content:

``` rst
...

Credits
=======

Images
------

* Odoo Community Association: `Icon <https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg>`_.

Contributors
------------

...
```

Is the proposal rename the file
from https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.svg
to https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon_template_(do_not_copy_to_your_module).svg
?

**Comment by pedrobaeza** [comment]
Yeah, that's my proposal for avoiding confusion, but it's not valid for that link. Moving to another directory will get also to a dead link.

**Comment by moylop260** [comment]
Ok I got it
Are you agree with a pylint-odoo check to avoid added it like as @lasley told us?

**Comment by moylop260** [comment]
I executed `rgrep -i "icon.png" .` and I didn't find a reference to this file too.

Could you remember me for what we added it?

**Comment by pedrobaeza** [comment]
It's not added in any file, but expected to be in /static/description/icon.png as the icon for the module.

**Comment by moylop260** [comment]
Oh yeah, the default icon I got it thank you!
Then I could create a check for svg file but I don't know if a good idea for you.
Let me to know it before work on it

**Comment by pedrobaeza** [comment]
There are some legitimate cases where you have to add the SVG. For example: https://github.com/OCA/vertical-association/blob/8.0/membership_prorrate/static/description/icon.svg

**Comment by moylop260** [comment]
That is a `icon.svg` different to oca one.
We can validate the checksum like as @lasley proposal

**Comment by lasley** [comment]
IMO if the checksum validation isn't too difficult, this would be awesome. Can't beat it when automation lets us be dumb humans with no consequences.

The one potential downside I could see to this validation is if someone does not actually squash their commit, but instead creates a new commit without the icon. This could potentially double our diff data & make it harder for us as reviewers to notice the SVG is there. 

This would be circumvented if we strictly enforced the squashing in PRs, but this is kind of an advanced rule for newcomers & could decrease the amount of new contributors to our community.

**Comment by pedrobaeza** [comment]
The problem with the checksum verification is that some day we will change the default icon by whatever reason, and we will hardly remember all of these "tricks" made on MQT, but it can be a solution. As you say, the double diff (putting and then removing) menace is still there.

**Comment by moylop260** [comment]
We should use the new github feature of `squash and merge` in order to store just one sha commit in the base branch and avoid request a manual squash to contributors.
We will have cleaner projects and we don't have trash log.

![github](https://cloud.githubusercontent.com/assets/6644187/17490267/a3ffe970-5d67-11e6-8437-8f54f6c846a0.png)

**Comment by lasley** [comment]
@pedrobaeza and I were talking about using this feature recently in another PR. There are a few downsides to this, the biggest being that it is now the merger's responsibility for this. 

I'm curious as to what the commit note looks like when this feature is used as well. If it's anything like the auto-squash we're going to end up with semi-useless change log entries anyways, which really seems like sweeping a problem under the rug IMO.

That said I think it may be good to have the option, at least in cases of newcomers where enforcing standards on the code without discouraging is more important than our change logs.

**Comment by gurneyalex** [comment]
<rant>These discussions should happen on the OCA mailing lists. Lots of people are insterested and many of them don't receive notifications from this github project's issues.</rant>

**Comment by pedrobaeza** [comment]
I disagree. They should subscribe here. This is the best place. You can link easily a lot of stuff. A mailing list is not the best place for that I think.

**Comment by dreispt** [comment]
@pedrobaeza I think there are too many subjects on this thread. But I see at least two discussed ideas here that scope all OCA projects, and not only this. These general procedures should be discussed in the ML.

(PS: although I dislike the too unstructured way of the ML threads, at least Issue comments allow for reactions on individual posts...).

**Comment by gurneyalex** [comment]
- regarding "unstructured" ML threads, the main culprit here is odoo's poor handling of threads. 
- regarding public mailing list communication: amending a published branch requires a public announcement to our users. And twitter is not the proper way, nor is an issue on the project. 

If I may add, quoting https://odoo-community.org/page/ogranization, paragraph about Communication

>  PSC members should always be subscribed to their project's public list, and to at least the contributors@ list to be aware of the other collaboration and contributions. Virtually all PSC communication should happen on the project’s public list.
> 
> Ensuring that PSC discussions about the future of the project are held on the public lists ensures that all of the community - including non-members - can follow the discussion and comment on issues. While only PSC members have binding votes on project matters, healthy PSCs certainly work with the larger community of their project.
