### ISSUE TITLE
RFC: Backend Hardware Proxy Management

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#514]
I am currently planning a project to allow backend management of web hardware proxies. Please let me know if this overlaps with some existing work, or if there is already an existing strategy for this that I don't know of 😄 

The proxies work great as it is currently, but they are basically meant for a localhost scenario. I require an unknown set of hardware proxies to be usable by remote users, effectively allowing things like a mobile shipping workflow using a "Shipping Station" consisting of nothing more than a Raspberry Pi, Scale, and Barcode Scanner.

My current plan involves creating a relay proxy using the main Odoo server as a central hub. All external hardware relays will register with the Odoo server, which will maintain a database of available relay via a callback hook implemented into the edge nodes with a client module (similar to dead man's server/client from a 100km view)

The central Odoo server will emulate the hardware relay routes, with an added parameter for the specific relay in which to IO from. It will basically just play MitM between the User and the headless relay servers.

The central Odoo server will need valid network routes to all of the remote proxies in order to provide the necessary communications.

In order to rig the relay parameter, default devices will have to be specified at some level in order to direct the traffic while maintaining full compatibility with core implementation. I'm thinking something similar to `base_report_to_printer`, just for proxies.

An interesting upside to this implementation is that we could begin to make modules that act upon incoming relay data on the backend, without interaction from a client.

cc @t3ddftw

**Comment by pedrobaeza** [comment]
PosBox project itself acts a hardware proxy AFAIK

**Comment by lasley** [comment]
You are correct that POS box implements a lot of this logic - the problem is that it is meant to operate [on devices attached to the localhost machine of the client](https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/js/devices.js#L86), which also has the Odoo instance installed on it to act as the hardware proxy. 

Installing an Odoo instance on client machines is a no go in my scenario, so I need the client machines (in this case mobile devices) to be able to communicate to the remote hardware proxies that are hosted on other machines.

This is technically also not an issue within the current framework, but the proxy addresses have to be hardcoded into the code for the most part, [as illustrated with this loop in POS](https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/js/devices.js#L298).

In order to achieve my desired scalability and maintainability, some sort of centralized aggregation of proxies and drivers needs to be created which can then be utilized via downstream modules.

**Comment by pedrobaeza** [comment]
You can push in abstracting current PosBox/POS implementation from the local network, or creating a new framework that allows us to go out of the boundaries of the initial design. Your choice then!

**Comment by lasley** [comment]
Woot I have a few ideas to go about this and am planning things now. We should see this feature in ~2m

I'm going to keep the issue open, just in case someone sees and has some excellent idea on implementation 😄
