### ISSUE TITLE
Improve common.SavepointCase

### ISSUE THREAD

**Issue by ghost** [OCA/server-tools#524]
Recently, I began using common.SavepointCase instead of common.TransactionCase for my unit tests. It saves a lot of time because the fixture is ran one time for all tests.

But common.SavepointCase has an important limitation. If an exception is raised in setUpClass, it creates a lock on the database.

I would like to propose a module that adds a test class. Here is what it would look like:

`
from openerp.tests import common

class SavepointCase(common.SavepointCase):

```
@classmethod
def setUpClass(cls):
    super(SavepointCase, cls).setUpClass()
    try:
        cls.prepare_class()
    except:
        cls.tearDownClass()
        raise

@classmethod
def prepare_class(cls):
    pass
```

`

The method prepare_class could be inherited to implement the fixture of the test.

What do you think ?

**Comment by ghost** [comment]
@pedrobaeza @dreispt @moylop260 What do you think about this ?

**Comment by moylop260** [comment]
Do you have the traceback log with the lock error?
I found a parameter to use in the cursor when use savepoint...

**Comment by ghost** [comment]
@moylop260 no, I don't have a traceback. Any exception raised in setUpClass could create the lock.

What is your parameter ?

**Comment by moylop260** [comment]
Try it with
`self.env.cr._serialized = False`
`self.env.cr.autocommit(False)`

But if you have a good history to add a extra code... You should create a PR directly to odoo/odoo after that if they refuse it then we could use a oca wrapper

**Comment by moylop260** [comment]
Review the full docstring of Cursor class with the case of isolation level
https://github.com/odoo/odoo/blob/9.0/openerp/sql_db.py#L62

**Comment by ghost** [comment]
@moylop260 ok, I will try this and see if this prevents the lock.

**Comment by ghost** [comment]
@moylop260 Thanks for the feedback. Unfortunately, I am not able to reproduce the bug I had last week. I will close this issue.
