### ISSUE TITLE
[base_export_manager] "TypeError: Session.get_export_models is not a function" bug. 

### ISSUE THREAD

**Issue by jlzhou** [OCA/server-tools#525]
After installing 'base_export_manager' module into odoo 9.0, by access any list tree view I met below error dialog:

Odoo Client Error

TypeError: Session.get_export_models is not a function

http://localhost:8069/base_export_manager/static/src/js/base_export_manager.js:54

**Comment by max3903** [comment]
Ping @smangukiya

Maxime Chambreuil

**Comment by smangukiya** [comment]
Hi @max3903 : I think last pull request is still open which has this solution already! Please refer below link:
https://github.com/max3903/server-tools/pull/2

**Comment by max3903** [comment]
@smangukiya Please make a pull request directly to OCA/server-tools

**Comment by jlzhou** [comment]
This fix still has an issue:
Open any tree list, click the 'Create' button, then the edit form is shown, click 'Cancel' button to close the edit dialog, you will get the error dialog says: TypeError: self.session.get_export_models is not a function

**Comment by smangukiya** [comment]
I will look this case and update it accordingly. Thanks

**Comment by smangukiya** [comment]
@jlzhou : I was not able to generate this error again (i.e. with following your suggested steps). Can you capture it or something?
Thanks
