### ISSUE TITLE
[auth_admin_passkey] User account is locked each time we use auth_admin_passkey

### ISSUE THREAD

**Issue by nowheresly** [OCA/server-tools#529]
We are using auth_admin_passkey in our odoo 8.0 instance with the auth_ldap module.
Our LDAP is an Active Directory (AD).
Unfortunately, each time we use the admin password to log in, the corresponding user account is locked in our AD.
Fyi, our policy is to lock an account after 5 unsuccessful attempts.
Any idea why auth_admin_passkey could generate 5+ unsuccessful log in attempts and how to prevent it ?

**Comment by sbidoul** [comment]
It's most probably because auth_admin_passkey calls super() before doing its thing. Depending how how modules are registered, if auth_ldap is higher in the inheritance chain, auth_ldap gets called repeatedly with a wrong login/password combination (ie the user id with the admin password).

**Comment by rvalyi** [comment]
cc @legalsylvain

**Comment by legalsylvain** [comment]
Hi, 
I don't understand why it will intent to log 5 times on the AD. Could you set log ?

FYI, the compatibility of this module with other module like "auth_crypt" modules has been discussed here, 
https://code.launchpad.net/~sylvain-legal/server-env-tools/7.0-auth_admin_passkey/+merge/211338
with @StefanRijnhart

**Comment by lasley** [comment]
I've had this same issue with the all of the auth modules. @sbidoul is on point with his theory - you can easily replicate this issue when you have two identically named users on the different systems, identify the inheritance chain, then try to login to the one higher up the chain (Odoo is always the highest up). The lower modules are always hit while traversing to the correct system, but I only see them hit once per login.

My interim, non-scalable solution to this was to disallow the use of identically named users on disparate systems. I would recommend not having a user on your AD named `admin`, so that's probably the candidate for change.

Alternatively instead of using `SAMAccountName` for your LDAP bindings, you could use an attribute like `userPrincipalName` which provides domain isolation. This is what I do on Odoos with multiple ADs

Long term solution I have been playing with is a selection on the user of what auth system they are from. I haven't found a viable approach though because the systems don't register themselves, so this change would affect way too many modules - including core stuff 😦

**Comment by nowheresly** [comment]
Hi @lasley, thanks for your explanation. Good to know I'm not the only one struggling with this issue :-). Sure, letting the user choose which auth back-end to use would solve the issue. I agree it seems quite not easy to implement yet...

Hi @legalsylvain, thanks for the provided link.
I spent some time with the debugger to try to understand why so much unsuccessful login attempts are generated when we use auth_admin_passkey with auth_ldap.
You could find below a sequence diagram explaining in details the result of my debugging session.
But here is the short version:

Each login attempt with the admin password results in 2 unsuccessful login attempts in our AD (1 to check credentials, 1 to ensure the password of the user is not the same as the admin password).
Then, when the user is authenticated by means of the admin password, each time the browser calls the url /web/session/get_session_info, an unsuccessful login attempt is sent to our AD.
Since a security policy is defined preventing too much wrong login attempts, account become locked very quickly.

I'm still wondering what could be the easiest way to prevent this behavior... If some of you may have suggestions ?

![trying to authenticate some user with admin password by means of module auth_passkey](https://cloud.githubusercontent.com/assets/916109/18051792/076cfbc0-6df7-11e6-8364-d9c276c925a8.png)

(to generate this diagram, just copy and paste the text below in https://websequencediagrams.com)

```
title Trying to authenticate some user with admin password by means of module auth_passkey

participant common.py as COM
participant "auth_passkey" as PAS
participant "auth_ldap" as ALD
participant "LDAP" as LDAP
participant "auth_crypt" as CRY
participant "res/res_user.py" as USR


COM->PAS: authenticate()
PAS->USR: authenticate()
USR->ALD: _login()
ALD->USR: _login()
USR->PAS: check_credentials(user, password)
PAS->ALD: check_credentials(user, password)
note right of ALD
first, auth_ldap is checking the password in db
end note
ALD->CRY: check_credentials(user, password)
CRY->USR: check_credentials(user, password)
USR-->CRY: AccessDenied
CRY-->ALD: AccessDenied
note right of ALD
this user is NOT defined id db, now it checks LDAP
end note
ALD->LDAP: authenticate()
note right of LDAP
since we are using the admin password, 
LDAP will reject the authentication attempt
At this stage, the current number 
of wrong login attempts is 1
end note
LDAP->ALD: False
ALD-->PAS: AccessDenied
note right of PAS
At this stage, auth_passkey is realizing 
the couple (user, password) is wrong.
It will try to guess if the given password
is the admin password
end note
PAS->ALD: check_credentials(superuser, password)
ALD->CRY: check_credentials(superuser, password)
CRY->USR: check_credentials(superuser, password)
USR->CRY: True
CRY->ALD: True
ALD->PAS: True
note right of PAS
At this stage, the user is authenticated 
by means of the admin pasword.
end note
PAS->USR: True
USR->ALD: True
ALD->USR: True
USR->PAS: True
note right of PAS
But before returning, auth_passkey
authenticate method 
is checking if the user password is 
the same of the admin password.
end note
note right of PAS
First auth_passkey checks admin password
end note
PAS->ALD: check_credentials(superuser, password)
ALD->CRY: check_credentials(superuser, password)
CRY->USR: check_credentials(superuser, password)
USR->CRY: True
CRY->ALD: True
ALD->PAS: True
note right of PAS
Then, it checks the user password
end note
PAS->ALD: check_credentials(user, password)
ALD->CRY: check_credentials(user, password)
CRY->USR: check_credentials(user, password)
USR-->CRY: AccessDenied
CRY-->ALD: AccessDenied
note right of ALD
this user is NOT defined id db, now it checks LDAP
end note
ALD->LDAP: authenticate()
note right of LDAP
This is the second time we check the password
in LDAP.
At this stage, the current number 
of wrong login attempts is 2
end note
LDAP->ALD: False
ALD-->PAS: AccessDenied
note right of PAS
admin and user passwords are not the same,
everything is fine
end note
PAS->COM: True
note over COM, USR
At this stage, the user is authenticated,
the current number of wrong login attempts is 2.
The browser of the client is redirecting from
http://odooserver/web/login to
http://odooserver/web where the user interface
is initializing.
During the initialisation phase, the url
/web/session/get_session_info is called.
This url triggers a call to check_credentials(user, password)
As already demonstrated above, this call will trigger
an unsuccessful login attempt to the LDAP.
At this stage, the current number of unsucessful login
attempts is 3. 

But.. Wait!

Due to race conditions while loading the UI, it happens
very often the url
/web/session/get_session_info could be called several times.
Furthermore, as soon as the user hit the F5 button, 
/web/session/get_session_info will be called
as well. 
If you switch from the back-end UI to the website, 
then back from the website to the back-end UI, 
/web/session/get_session_info will called too.
As a conclusion, this behaviour explains why an account 
can be very easily locked when using auth_passkey
and auth_ldap when a strict security policy
is enforced at the LDAP level.
end note
```

**Comment by lasley** [comment]
@Nowheresly ~~best~~ easiest way to fix this is to guarantee that you aren't using the same user on multiple login systems. I recommend changing your login filter on LDAP from `sAMAccountName`, which was deprecated in 2000, to `userPrincipalName` instead which provides domain isolation.

**Comment by nowheresly** [comment]
Hi @lasley 
Thanks for your reply!
I'm not sure to understand your solution.
Currently, the user admin is **not** defined in our AD. It's an internal odoo user.
The odoo module auth_crypt is used to check admin password.

We have only one AD configuration in our company settings.

Accounts are locked because when using the admin password to log in with a user defined in our AD, auth_admin_passkey is regularly trying to check credentials in our AD using the admin password (which fails).

I will try to use `userPrincipalName` as logon filter (thanks for the tips!), but I don't see how it could solve my issue.

**Comment by lasley** [comment]
`userPrincipalName` is an email style username including your AD domain. Honestly the only way it helps is by creating an isolation so that your AD can't be accidentally hit like this. It's duct tape really

**Comment by nowheresly** [comment]
@lasley : ok now it becomes clearer to me. By using AD domain, we could avoid checking all AD back-ends in a for loop until we find the good one, but directly requesting the good one, right?
In the meantime, as you saw, I proposed a very simple PR #533 that could fix this issue. Many thanks for your review.

**Comment by lasley** [comment]
Exactly - basically it's just enforcing the explicit domain and creating an implicit isolation of your users. This is actually a common issue in AD world in general, hence the deprecation of `sAMAccountName` and recommendation of use `userPrincipalName`. The possibility of multiple login backend just wasn't a thing back in the day, so anything using simply a username is susceptible to this issue - all login backends just walk their way up the chain till they find a good one.

Your fix provides some good measure, but will still leave the issue open in some instances. This is an issue you will run into with essentially any system allowing multiple auth backends. I've had issues with this also causing brute force measures to kick in, banning my server for a time. Gotta love it 😉

**Comment by pedrobaeza** [comment]
Closing as there are PRs solving this.
