### ISSUE TITLE
odoo crashes with this module, and if you disconect it, odoo is ok

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/server-tools#536]
odoo crashes with this module, and if you disconect it, odoo is ok

From some weeks ago, This module makes odoo crash. When I disconnect it from de /custom/addons link, odoo returns to live.

**Comment by pedrobaeza** [comment]
Which module?

**Comment by fgarcia-humanoide** [comment]
Sorry , it is auto_backup
https://github.com/OCA/server-tools/tree/8.0/auto_backup.

It was my fault to publish the issue in the incorrect place.

Sorry and Thanks.

---

Fernando Garcia Hansen

_Humanoide Servicios para la Pyme, S.L.N.E._
_Teléfono 657 054 861_
www.humanoide.es

2016-08-31 9:28 GMT+02:00 Pedro M. Baeza notifications@github.com:

**Comment by pedrobaeza** [comment]
And which is the error?

**Comment by fgarcia-humanoide** [comment]
[https://groups.google.com/forum/#!topic/openerp-spain-users/H9XkmcL-EL0](url)

![seleccion_033](https://cloud.githubusercontent.com/assets/7599709/18120255/f3103b10-6f5e-11e6-9a92-3dac687e2aba.png)

It seems that I have not installed pysftp dependency, but I did install it.

**Comment by fgarcia-humanoide** [comment]
https://groups.google.com/forum/#!topic/openerp-spain-users/H9XkmcL-EL0

**Comment by pedrobaeza** [comment]
You don't have last version, because the import is protected: https://github.com/OCA/server-tools/blob/f35ed340d175a1514f8a0961cbf67db06b4e68f4/auto_backup/models/db_backup.py#L17

**Comment by fgarcia-humanoide** [comment]
Ok, thanks
