### ISSUE TITLE
base_import_match cause import sale order fail

### ISSUE THREAD

**Issue by youring** [OCA/server-tools#537]
v8.0 fresh database with demo data,
Step 1. Import sale order from csv file:
name,customer,order Lines / product,order_line/product_uom_qty
S0011,Camptocamp,Datacard,2
"Everything seems valid" when click Validate.
Step 2. Install base_import_match
Step 3. Create a new match on model Sales Order with one field Order Reference.
Step 4. redo Step 1 Validate, error ocurrs:
No matching record found for name '2' in field 'Order Lines' at row 2.
@Yajo

**Comment by yajo** [comment]
Could you provide a failing CSV and a screenshot/export of your settings? Thanks.

**Comment by youring** [comment]
![import_match_setting](https://cloud.githubusercontent.com/assets/4132418/18166432/be704ef2-707d-11e6-9def-b02d788a0fa2.png)
![import_sale_order_error](https://cloud.githubusercontent.com/assets/4132418/18166436/c3f83434-707d-11e6-81de-862bc5ad18e0.png)
[SALE.IMPORT.TEST.zip](https://github.com/OCA/server-tools/files/449544/SALE.IMPORT.TEST.zip)
csv file is in zip.
