### ISSUE TITLE
[8.0] letsencrypt on RedHat / Centos 7

### ISSUE THREAD

**Issue by zeroheure** [OCA/server-tools#540]
Hi
Thanks for your great work. Here's a little issue with path to openssl.cnf on RedHat / Centos. 
RedHat keep openssl parameters in /etc/pki/tls/openssl.cnf  while /etc/ssl/ contains only a symlink on /etc/pki/tls/certs/

Path to openssl.cnf is hard coded  in models/letsencrypt.py
def generate_csr (self, domain):
(...)
 config = self.env['ir.config_parameter'].get_param('letsencrypt.openssl.cnf', '/etc/ssl/openssl.cnf')

Xavier Brochard

**Comment by zeroheure** [comment]
Note also that the pip released acme-tiny is outdated : it contains path to old Letsencrypt agreement.
Git version is ok.

**Comment by pedrobaeza** [comment]
Thanks for this info. Please do a PR to complete documentation in the module.
