### ISSUE TITLE
Impossible to use auto_backup , it needs to install pysftp but it is impossible

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/server-tools#542]
it is Impossible to use auto_backup.

It asks yout to install pysftp

so you do `

`sudo pip install pysftp`

But the module asks again , even if you have installed it.

This causes the odoo instance to break , you need to disable de module to log in in odoo. 

`

**Comment by fgarcia-humanoide** [comment]
Error

Unable to upgrade module "auto_backup" because an external dependency is not met: No module named pysftp

**Comment by fgarcia-humanoide** [comment]
root@new-host-2:~# pip freeze > requisitos.txt
root@new-host-2:~# cat requisitos.txt 
Babel==1.3
BzrTools==2.6.0
Jinja2==2.7.2
Landscape-Client==14.12
Mako==0.9.1
MarkupSafe==0.18
PAM==0.4.2
Pillow==2.3.0
PyChart==1.39
PyWebDAV==0.9.8
PyYAML==3.10
Pygments==1.6
SecretStorage==2.0.0
Twisted-Core==13.2.0
Unidecode==0.04.19
Werkzeug==0.9.4
ZSI==2.1-a1
apt-xapian-index==0.45
argparse==1.2.1
bzr==2.7.0dev1
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
decorator==3.4.0
docutils==0.11
feedparser==5.1.3
gdata==2.0.18
gevent==1.0
greenlet==0.4.2
html5lib==0.999
httplib2==0.8
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lxml==3.3.3
mock==1.0.1
oauth==1.0.1
paramiko==2.0.2
passlib==1.5.3
psutil==1.2.1
psycopg2==2.4.5
pyOpenSSL==0.13
pyPdf==1.13
pyasn1==0.1.9
pycrypto==2.6.1
pydot==1.0.28
pygobject==3.12.0
pygpgme==0.3
pyinotify==0.9.4
pyparsing==2.0.1
pyserial==2.6
pysftp==0.2.9 .........................................................................................................
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
python-ldap==2.4.10
python-openid==2.2.5
pytz==2012c
reportlab==3.0
requests==2.2.1
roman==2.0.0
simplejson==3.3.1
six==1.5.2
ssh-import-id==3.21
suds==0.4.1
uTidylib==0.2
unicodecsv==0.14.1
unittest2==0.5.1
urllib3==1.7.1
vatnumber==1.1
vobject==0.8.1c
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
xlwt==0.7.5
zope.interface==4.0.5

**Comment by zeroheure** [comment]
I've installed and setup àuto_backup a few days ago, on Centos7... Pysftp was a bit hard to install correctly, because it depends of lots of pacfages. Are you sure that Pysftp was correctly compiled ?

**Comment by fgarcia-humanoide** [comment]
O just have intalled It. Compilación is far beyond my reach

**Comment by lasley** [comment]
Pip compiles PySFTP when you install it, but as @zeroheure mentioned there are many dependencies and thus options for it to fail.

If the command to install did complete successfully, it's also possible that your Odoo instance is running in a VirtualEnv as is best practice. This isolates system python dependencies from your Odoo ones, which would make the module not show up with a standard pip install.

This is certainly an environment issue & is a common problem with any of our module using PySFTP, as noted by [a year old thread](https://ubuntuforums.org/showthread.php?t=2296755) on UbuntuForums regarding this same module and issue.

**Comment by lasley** [comment]
@fgarcia-humanoide - I am going to close this issue as it is not an issue with the module as noted above. If you are unable to resolve, I recommend you look into hiring an OCA team to help you out.

**Comment by zeroheure** [comment]
I'm not a dev, but a sysadmin. So this is just a sysadmin idea :
"pip install module" will compile module.py in module.pyc
In your case you need to check that "pip install pysftp" ran correctly : 
  /usr/lib/python2.7/site-packages/pysftp should contain files ended with ".pyc"
You could also uninstall and reinstall pypsftp and check the output.

**Comment by fgarcia-humanoide** [comment]
The .pyc files are there as can be seen in the photo:
![seleccion_037](https://cloud.githubusercontent.com/assets/7599709/18284384/fd6c9daa-7469-11e6-804a-0e813f3dfacd.png)
