### ISSUE TITLE
8.0 build is failing!

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#548]
I tried restarting the build, and the problem persists.
- ERROR: `Programming error: column "database_cleanup_test" does not exist` [link](https://travis-ci.org/OCA/server-tools/jobs/159251703#L709)
- Error when `loading base_import_match/data/base_import_match.yml`: `TypeError: unsupported operand type(s) for +: 'bool' and 'str'` [link](https://travis-ci.org/OCA/server-tools/jobs/159251703#L872)

Looks like some bad interaction between `database_cleanup` and `base_import_match`.

**Comment by pedrobaeza** [comment]
Fixed already.
