### ISSUE TITLE
RFC: Docker Connector

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#555]
I am in the process of planning an abstract Docker connector, with the intent to allow Odoo to manage Docker in the following capacity:
- Read (Connect) to Registry
- Create, Read, Delete containers
  - Connect to containers - nice to have
- Create, Read, Update, Delete networking
- Read, create Docker composition files
  - Translate into appropriate workflow and record actions

It will also have a concept of Dockerfiles in order to create the containers.
- I am thinking that URL-only would be the way to go, but I could easily add a binary field in order to directly upload a Dockerfile if this is something someone wants.

Following is a prelim data schema:

![docker connector schema 2](https://cloud.githubusercontent.com/assets/7397578/18659125/682a0184-7ebd-11e6-9f1a-260761f88984.png)

Obviously this is a very rough sketch, but I figure something like this would be good to get out early - particularly with its implications towards Dockerized Runbot - cc @moylop260 😉 

I'll probably be updating this more over the next few days as the schema simmers a bit in my head. Any comments/suggestions/questions are welcome!

**Comment by moylop260** [comment]
What do you think about @ruiztulio?

**Comment by lasley** [comment]
FYI I think I will be splitting a lot of the network stuff into a separate module - I am going to need a lot of that for my planned Server and Ansible connectors.

**Comment by elicoidal** [comment]
@lasley interesting initiative. 
Do you plan to include some docker-compose (or anything similar) in the framework?
@seb-elico

**Comment by lasley** [comment]
@elicoidal - It wasn't an explicit plan, but I don't see why I can't support import/export of this file format. My goal is to allow template-based composition & management of Docker containers within Odoo, so providing the pre-existing standard makes a lot of sense IMO.

**Comment by elicoidal** [comment]
@lasley I docker compose allows the templating and easy deployment later IMO too

**Comment by lasley** [comment]
I'm going to go ahead and close this, [Clouder](https://github.com/clouder-community/clouder) will do the trick for most (if not all) of this. Compose is being added in clouder-community/clouder#158 & other functionality is in the works/planned. 

Move of Clouder to OCA has been approved & is pending our incubator completion. Anyone looking to help out or follow the status of the project should do it there for the moment.
