### ISSUE TITLE
Would Odoo App "External Database Sources" can access Oracle with no need to Postgres

### ISSUE THREAD

**Issue by technav98** [OCA/server-tools#557]
@dreispt 
Hello Daniel, 
Regarding Odoo App named "External Database Sources" per this link 
[https://apps.odoo.com/apps/modules/9.0/base_external_dbsource/]
Would this Addon lets Odoo to be based 100% on Oracle (with no need for postgres database) OR it is just help accessing other datasources side by side with main core postgres database?
In other words can we use "External Database Sources" Odoo App to let all of Odoo modules use Oracle database in same exact default way for Postgres?

**Comment by pedrobaeza** [comment]
No, this is only a "connector". You should rely on Postgres for DB storage layer.

**Comment by technav98** [comment]
Thanks for quick answer

**Comment by dreispt** [comment]
@technav98 It is just a gateway to allow getting data from other databases into your app.
It was originally created to be used was used by the `import_loader``  module to automate data imports directly from foreign databases.
