### ISSUE TITLE
Error When using "docs" enumerator: QWebException: foreach enumerator 'docs' is not defined while rendering template

### ISSUE THREAD

**Issue by sergueikp** [OCA/server-tools#569]
module: email_template_qweb
version: 8.0

**Steps to reproduce**
- Create a mass-mailing wizard on Order lines (sale.order.line)
- specify :  'default_composition_mode': 'comment',
- create email template with a loop using docs enumerator looping on some field:

`<?xml version="1.0"?>
<t t-name="aramis_planning.view_sale_order_line_send_email">
            <body>
                <html>
                  <p>
                            <t t-foreach="docs" t-as="o">
                                  <t t-esc="o.name"/>
                            </t>
                        </p>
                </html>
            </body>
        </t>`
- Go to sale.order.line list view
- select lines that you want to use in email body
- Click on the Wizard that opens email composition window, select your template that you want to apply to your email

**Current behavior**
- if you use docs enumerator you get the error trace back:
  QWebException: foreach enumerator 'docs' is not defined while rendering template 1211
  **Expected behavior**
- It should loop through all selected sale.order.lines and print a value of the defined field.

**Comment by pedrobaeza** [comment]
That variable is not usable here. Please see https://github.com/OCA/social/tree/8.0/email_template_qweb#usage that explains which variables are available (essentially, what you need is `object` variable).

**Comment by sergueikp** [comment]
Hi, thank you for your reply,
But is it possible to loop through several Sale order lines with object or email_template, if not how much will cost to develop such thing?

**Comment by pedrobaeza** [comment]
It's automatically done by mail sending if you select several records, not by this module. The mentioned variable is the only one you need.

**Comment by sergueikp** [comment]
Yes, but mail sending do not print all this records in the mail body, how to do this?

**Comment by pedrobaeza** [comment]
No, that's not the purpose of this module and mail sending in odoo in general.
