### ISSUE TITLE
[8.0][mass_editing]  __last_update not written on product.template model with Mass Editing?

### ISSUE THREAD

**Issue by thomasklosinsky** [OCA/server-tools#577]
Hi there,
I am using the basically for product.template mass editing and found that the  __last_update is not written which causes some problems with our shop connector. Products modified are not synced to the shop server this way since no sign of modification is made by mass editing.
How can I add that?
Best regards,
Thomas

**Comment by mmotahar** [comment]
I have the same problem with leads and opportunities.
