### ISSUE TITLE
auth_signup_verify_email: user lang not stored on signup

### ISSUE THREAD

**Issue by simahawk** [OCA/server-tools#585]
The base module `auth_signup` uses `do_signup` https://github.com/odoo/odoo/blob/9.0/addons/auth_signup/controllers/main.py#L99

but `auth_signup_verify_email` skips it

https://github.com/OCA/server-tools/blob/9.0/auth_signup_verify_email/controllers/main.py#L43

which is correct for its behavior but is misses the user language retrieved by current request lang.

**Comment by pedrobaeza** [comment]
Can you please do a PR amending this?

**Comment by simahawk** [comment]
@pedrobaeza there you go ;)

**Comment by pedrobaeza** [comment]
Cool! I'll review it. I close this issue as there's an opened PR.
