### ISSUE TITLE
file date_range/security/ir.model.access.csv could not be processed

### ISSUE THREAD

**Issue by oguerrauci** [OCA/server-tools#591]
I try to install the module date_range and I have this issue when loading the installation:
Exception: Module loading date_range failed: file date_range/security/ir.model.access.csv could not be processed:
 Line 3 : No matching record found for external id 'base.group_configuration' in field 'Group'

**Comment by pedrobaeza** [comment]
I think you have mixed Odoo versions. The module is working without problems.
