### ISSUE TITLE
9.0 database_cleanup: README out of date?

### ISSUE THREAD

**Issue by gurneyalex** [OCA/server-tools#593]
The README of database_cleanup suggests that I may get the option to review what could be cleaned up before the purge actually happens. Yet under Settings -> Technical -> Database Cleanup I only see 'Purge xxxx' entries which don't display a form and directly perform the actual purging. 

Am I overlooking something or is it just a case of outdated README (in which case I'll gladly propose a PR).

**Comment by gurneyalex** [comment]
@hbrunn your input on this is welcome.

**Comment by hbrunn** [comment]
The should be a button 'Select lines', which sends you to a tree view, where you can select lines and launch the purge action

**Comment by pedrobaeza** [comment]
@gurneyalex, that menus are not the actual purging, but you need to still do it on the next screen. I close this.
