### ISSUE TITLE
[9.0] auto_backup The commit history is lost in 9.0

### ISSUE THREAD

**Issue by lmignon** [OCA/server-tools#619]
We must preserve the commit history
https://github.com/OCA/server-tools/commits/8.0/auto_backup
https://github.com/OCA/server-tools/commits/9.0/auto_backup

**Comment by pedrobaeza** [comment]
Closing as this has been solved.

**Comment by antespi** [comment]
There is a problem when merging this addon in 9.0 branch, there is no auto_backup addons at all.
Can you review this?

Thanks all @lasley, @pedrobaeza, @lmignon

**Comment by lasley** [comment]
What the heck - that PR (#620) has no files changed in it anymore. I can guarantee that wasn't the case before though because #614 is based on it. 

I'm not sure what happened here guys. I guess I can resubmit the PR, but what about all the commits that made it on but I guess are blank?

**Comment by antespi** [comment]
ok, @lasley, you can resumit the PR in order to see if that fix it

**Comment by lasley** [comment]
What about the 54 commits already on 9.0 branch that are seemingly empty?

**Comment by lasley** [comment]
Closing, this was resolved in #636
