### ISSUE TITLE
shell command exits

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/server-tools#631]
Have tried all kinds of combinations of commands but shell is not firing:

    /usr/bin/python2.7 ./odoo.py shell --config /etc/odoo/openerp-server.conf -d demo8

    /usr/bin/python2.7 ./odoo.py shell -d demo8

    ./odoo.py shell -d demo8

What can I do to make it work?

**Comment by pedrobaeza** [comment]
Use `./odoo.py --addons-path=<your_addons_path> shell --config=<your_conf>`
