### ISSUE TITLE
Relicense `base_external_dbsource` to LGPL

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#635]
@lasley has asked (#633) for this module to be relicensed to LGPL.
As the original author a agree to change it, but to respect the other contributors I would like to open the discussion and check that no one disagrees.

Original features, other than me, I can only spot @ mstuttgart, adding Firebase support.
Other contributors (migrations, code porting) are: @jlzhou,@naousse, @bwrsandman,  @max3903
Sorry if I missed any contributions.

Comments welcome.

**Comment by max3903** [comment]
I agree to change the license to LGPL.

**Comment by dreispt** [comment]
Just realized I didn't ping @mstuttgart properly: do you agree with the relicensing?

**Comment by mstuttgart** [comment]
Hi @dreispt ! 
I agree  to change the license to LGPL :+1:

**Comment by dreispt** [comment]
@lasley What Odoo version are you planning to use?

**Comment by lasley** [comment]
@dreispt v9 and 10 for this project

**Comment by lasley** [comment]
Whoah hah I didn't realize the commit message on my rebase screw up was going to spam this message. Sorry about that!

**Comment by dreispt** [comment]
Closed by #637
