### ISSUE TITLE
[disable_odoo_online] v10 odoo sa is sending emails using outgoing email server

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/server-tools#639]
[disable_odoo_online] v10 odoo sa is sending emails using outgoing email server

So, something is not disconected and odoo Belgium can manage my community instalation

**Comment by lasley** [comment]
Hi @fgarcia-humanoide - You're saying that Odoo SA is sending emails through your Odoo instance? As far as I know, they do not send emails through your server - with or without `disable_odoo_online` installed. I recommend you contact Odoo SA instead, this is out of scope for `disable_odoo_online`.

**Comment by fgarcia-humanoide** [comment]
This is the mail they sent to me, using the outgoing email.
[Selección_032.pdf](https://github.com/OCA/server-tools/files/648124/Seleccion_032.pdf)

**Comment by lasley** [comment]
That email is built into Odoo and has nothing to do with Odoo SA, outside of the fact they designed it - https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/project/data/project_mail_template_data.xml#L5
