### ISSUE TITLE
[RFC] monitor_web: Remote Web Health Monitoring

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#643]
This module will provide the ability to monitor remote web (mainly) servers with a few simple checks at configurable intervals:
* Ping - this would work for anything accepting pings really
* Web Status - check for a defined status code at URL
  * Also allow for validation regexes on the response
* SSL Status - check certificate at URL
  * Also save the expire date

It will use the new `queue_job` module in order to provide a worker queue for the checks. This will also allow for Odoo to not die in the event that a bunch of the checks are stalling due to timeouts or whatever.

Somewhat of a consideration as well is not allowing someone to create a DoS scenario through the system. A fairly decent safeguard I think would be to save the resolved IP for domains, then add a global rate limit by IP.

Do we already have anything similar to this? Closest I could find was 7.0 server_monitors, but that's more for local database monitoring.

**Comment by pedrobaeza** [comment]
There is https://github.com/OCA/server-tools/tree/8.0/dead_mans_switch_client and https://github.com/OCA/server-tools/tree/8.0/dead_mans_switch_server, but isn't this best suited in an specific tool for this, like Nagios, Munin and so on?

**Comment by lasley** [comment]
I do love those Dead Man's modules, but I don't think they cover what I need here unfortunately.

We're using Shinken & are replacing with ELK & ElastAlert, so we have the tools internally. Problem is that I need to expose these controls to customers inside of their cloud control panel (in Odoo).

Maybe the strategy should instead be to use the external tool, but create a connector to control and view the data from Odoo. Hmmmm that could be significantly easier. Particularly because I'm already creating the Elasticsearch db source.

**Comment by lasley** [comment]
Yeah good idea @pedrobaeza - I'm going to plan an ElastAlert connector instead. This will be much easier and way more scalable, thanks!

**Comment by pedrobaeza** [comment]
Yeah, that's a better and more generic approach. You would need then website_elastalert or similar name for exposing results on a portal (if needed).

**Comment by sebalix** [comment]
@lasley it's not an answer to your issue, but maybe you are interested in this "monitoring related" module too https://github.com/OCA/server-tools/pull/312

**Comment by lasley** [comment]
Ohhh that could be useful too, thanks @sebalix - I'll give you a review on it sometime today or tomorrow 😄
