### ISSUE TITLE
Have Fetchmail add CC recipients to Followers

### ISSUE THREAD

**Issue by dreispt** [OCA/server-tools#655]
I'm using fetchmail as a channel to open Issues, and I would like for people in the email's CC to be added to the Issue as Followers.

Anyone else with the same need?
Is there a chance someone already implemented this?

**Comment by pedrobaeza** [comment]
That's the default behavior AFAIK. The only requirement is that the mails of the cc containers are registered in Odoo as partners. A complement can be to auto-create partners for non existing mails.

**Comment by dreispt** [comment]
Hmm, my tests don't confirm that: the "To" email is detected and maps to the corresponding Partner, but the "Cc" is also a known email and it is not added to the Followers.
I'm digging into the Fetchmail/Mail code to figure out where this logic is buried.

**Comment by pedrobaeza** [comment]
I think the logic is inside `mail` module, not `fetchmail`.

**Comment by dreispt** [comment]
This issue just popped up again. Any chance someone got this working?

**Comment by pedrobaeza** [comment]
The comment remains the same: if you don't have the mail registered in a partner, the follower is not added. Why this issue is not in OCA/social?

**Comment by dreispt** [comment]
Maybe it should have been an ML discussion instead.
While we're at it, AFAICS the responsible method is [mail_thread.message_new()](https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_thread.py#L1318), but I see no Followers being added from the message CC list.
(The CC emails are registered as Users/Partners).

**Comment by pedrobaeza** [comment]
In fact it's here where you call the method for deducing the followers: https://github.com/odoo/odoo/blob/08886028317bee684adca5d4850a7127a829e673/addons/mail/models/mail_thread.py#L1509

You can make a module that overwrites `_message_find_partners` method (or `_find_partner_from_emails` sub-method) that creates a partner from the mail address when no partner is found with that email). It easy to be done. You can also complement it with a flag and a filter for checking out this information easily from "Customers" menu for example.

**Comment by cvinh** [comment]
@dreispt did you solve that one ?
I'm interested
