### ISSUE TITLE
server_environment breaks existing installations

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#667]
`server_environment` breaks existing installations by raising an Exception in the global namespace if there is a missing config variable - https://github.com/OCA/server-tools/blob/10.0/server_environment/serv_config.py#L39

I feel that this should instead be handled similar to our import guards, otherwise pulling this repo breaks things badly. It just happened to us on a production server.

If the `Exception` is truly necessary, it should be moved further back into the module itself. It should also be changed into an `EnvironmentException` at the very least.

@t3ddftw will be submitting a fix soon.

**Comment by pedrobaeza** [comment]
Closing as #670 is merged.
