### ISSUE TITLE
500 internal server error on Google Auth using dbfilter_from_header

### ISSUE THREAD

**Issue by alexanderradahl** [OCA/server-tools#686]
Hello!

I'm having problems with Google Auth after installing this plugin. When I've confirmed that I want to connect to the calendar I get a 500 server error when I'm directed back to the Odoo install.
This wasn't a problem before, I need it to work.

**Comment by alexanderradahl** [comment]
Anyone that can help on this?

**Comment by pedrobaeza** [comment]
Sorry, wrong place for this, as the Google Auth is something of http://github.com/odoo/odoo, not this repository. Anyway, issues are for bug reports and similar, not for questions. There are forums on Odoo web page for that.

**Comment by alexanderradahl** [comment]
That is not true. This problem occurred because of one of the tools provided by the server-tools package, to be specific the dbfilter_from_header.

**Comment by pedrobaeza** [comment]
Then your report is without enough details: first of all, you are not even informing which module until now. After that, you are not reporting the traceback or nothing that can help to see a possible problem. Anyway, remember this is a voluntary community and there's no obligation to help you. Myself are not able to do it as I'm not using that module.

When you provide that details and change the issue name to something more explicit, I'll reopen the issue to see if somebody can help.
