### ISSUE TITLE
[8.0] password_security Installation issue

### ISSUE THREAD

**Issue by AEK-BKF** [OCA/server-tools#704]
Hi,
I'm trying to install the module password_security but an error tells me :
 

> Traceback (most recent call last):
>   File "G:\Odoo\odoo\openerp\http.py", line 544, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "G:\Odoo\odoo\openerp\http.py", line 581, in dispatch
>     result = self._call_function(**self.params)
>   File "G:\Odoo\odoo\openerp\http.py", line 317, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "G:\Odoo\odoo\openerp\service\model.py", line 118, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "G:\Odoo\odoo\openerp\http.py", line 314, in checked_call
>     return self.endpoint(*a, **kw)
>   File "G:\Odoo\odoo\openerp\http.py", line 810, in __call__
>     return self.method(*args, **kw)
>   File "G:\Odoo\odoo\openerp\http.py", line 410, in response_wrap
>     response = f(*args, **kw)
>   File "G:\Odoo\odoo\openerp\addons\web\controllers\main.py", line 948, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "G:\Odoo\odoo\openerp\addons\web\controllers\main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "G:\Odoo\odoo\openerp\api.py", line 268, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "G:\Odoo\odoo\openerp\addons\base\module\module.py", line 447, in button_immediate_install
>     return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>   File "G:\Odoo\odoo\openerp\api.py", line 268, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "G:\Odoo\odoo\openerp\addons\base\module\module.py", line 495, in _button_immediate_function
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>   File "G:\Odoo\odoo\openerp\modules\registry.py", line 370, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "G:\Odoo\odoo\openerp\modules\loading.py", line 355, in load_modules
>     loaded_modules, update_module)
>   File "G:\Odoo\odoo\openerp\modules\loading.py", line 255, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "G:\Odoo\odoo\openerp\modules\loading.py", line 176, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "G:\Odoo\odoo\openerp\modules\loading.py", line 118, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "G:\Odoo\odoo\openerp\tools\convert.py", line 897, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "G:\Odoo\odoo\openerp\tools\convert.py", line 974, in convert_xml_import
>     relaxng.assert_(doc)
>   File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src\lxml\lxml.etree.c:194922)
> AssertionError: Expecting element openerp, got odoo, line 10

Please Help me !

**Comment by lasley** [comment]
Hi @AEK-BKF - This installs fine on Runbot, so I would assume it is a local issue. Are you sure that you are on the v8 branch? This error is indicative of installing a mismatched version.

**Comment by lasley** [comment]
Closing, local issue. Please let us know if you are able to reproduce in Runbot

**Comment by AEK-BKF** [comment]
Hi @lasley ,
Thanks a lot for help, it works fine now, I've fixed it by removing some custom modules and then reinstall them after installing this one.
