### ISSUE TITLE
[10.0] auto_backup : Message subtype ref is wrong

### ISSUE THREAD

**Issue by rousseldenis** [OCA/server-tools#710]
@Yenthe666 @lasley   In auto-backup/models/db_backup.py about line 208 : message subtype reference for exception is wrong (see data).

**Comment by Yenthe666** [comment]
@rousseldenis I believe you mean it should be this? https://github.com/OCA/server-tools/pull/711

**Comment by rousseldenis** [comment]
@Yenthe666 Yes. Didn't see. Close
