### ISSUE TITLE
[RFC] Case Insensitive Logins

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#715]
[This module is actually pre-existing](https://github.com/LasLabs/odoo-base/tree/9.0/res_users_case_insensitive) & I completely forgot it existed until a customer needed it in their v10. I propose moving it to OCA for v10.

Basically the module just creates logins as all lowercase & adds a case insensitive search for them. It is meant to be installed on a new database, because it is possible that two logins could be conflicting in a pre-existing database due to case sensitivity.

It's been a while since we looked at it, so we'd probably give it some sort of overhaul to not make it so incredibly simplistic. An immediate feature that comes to mind is a hook to determine if there are logins that would conflict on a pre-existing database & convert all logins to lowercase if they don't.

Anyone have thoughts or a need for this?

**Comment by dreispt** [comment]
I'm using LDAP auth with M$ Active Directory (tm), and usernames are case insensitive there.
Allowing the login username lookup to be case insensitive would be nice for the users.
Another nice improvement would be to trim whitespace around the username: I found that when typing them in mobile devices we can sometimes get an extra space at the end.

**Comment by lasley** [comment]
> I'm using LDAP auth 

This is my use-case as well. We have also noticed a measurable amount of end user contact to our customers due to missing accounts that really just have a capital letter in the username.

> Another nice improvement would be to trim whitespace around the username:

Good call. So maybe we should generalize the name a bit, something like `user_login_usability`?

**Comment by dreispt** [comment]
Sounds good.

**Comment by dreispt** [comment]
I think `case_insensitive` is more meaningful.
I suggest `auth_user_insensitive`

**Comment by lasley** [comment]
Closing to track in #826
