### ISSUE TITLE
[8.0/9.0][BUG] base_search_fuzzy: Only works on old API cols

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#723]
This is somewhat of a theoretical bug that I noticed as I am upgrading this module to v10 in #722. I'm hoping maybe someone can confirm this with their own installation. This should affect v8 and v9 if I am understanding correctly.

In the [`patch_leaf_trgm`](https://github.com/OCA/server-tools/blob/9.0/base_search_fuzzy/models/ir_model.py#L25) method, the query is being built exclusively from `model._columns`.

Per the [Odoo ORM docs](https://github.com/odoo/odoo/blob/9.0/doc/reference/orm.rst), only old style columns are stored in this attribute:

> * uses of :attr:`~openerp.models.Model._columns` or
>  :attr:`~openerp.models.Model._all_columns` should be replaced by
>  :attr:`~openerp.models.Model._fields`, which provides access to instances of
>  new-style :class:`openerp.fields.Field` instances (rather than old-style
>  :class:`openerp.osv.fields._column`).

From this I am gathering that in older versions, the `_all_columns` attribute should be used (vs `._fields` for v10).

I don't mind fixing this issue, but I want to make sure it's actually an issue first. I feel like this module would be almost unusable in its current state, so I'm uncertain why this hasn't been reported already. This makes me doubt my conclusion.

**Comment by sebalix** [comment]
This should not be a problem because all new-style fields are converted in old-style colums in the [BaseModel._setup_fields()](https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L3003) method with [Field.to_column()](https://github.com/odoo/odoo/blob/8.0/openerp/fields.py#L709) to fill the `_columns` attribute.

**Comment by lasley** [comment]
Sweet thanks for pointing me to the code @sebalix - I agree with your eval. Looks like the docs are just totally wrong, what a surprise!
