### ISSUE TITLE
[9.0][auto_backup] Incorrect menu entry choice

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/server-tools#726]
auto_backup is UNUSABLE on v9:

auto_backup creates a menu entry under 'General Settings'. But by doing so, it disables the General Settings menu itself, preventing access to such important settings as mail gateways, multicompany setup, google integration and more. I can prepare a PR but need advice on the new menu location. Perhaps 'Technical/Database Structure'?

On a side note, the module description mentions "Do you want to know if the database backup succeeded or failed? Subscribe to the corresponding backup setting notification type." How can I do this subscription?

**Comment by lasley** [comment]
@pedrocasi - that menu location sounds fine.

Notifications are in Settings => Technical => Email => Followers => New

![image](https://cloud.githubusercontent.com/assets/7397578/22619754/65537b8e-eab0-11e6-8ae1-a11cd5fde39d.png)

**Comment by astirpe** [comment]
I confirm the menu issue: it also occurs on V10.
Moving the menu to 'Technical/Database Structure' would be nice.

**Comment by pedrocs-exo** [comment]
PR #728 fixes the issue on 9.0. I'll try to correct 10.0 as well as soon as possible. Thank you both!

And also a special thanks to Dave for the email followers tip!

**Comment by astirpe** [comment]
Porting the fix to V10, here is the PR: #735

**Comment by lasley** [comment]
Closing to track in PRs
