### ISSUE TITLE
[10.0][mass_editing] Mass editing doesn't update openchatter openchatter

### ISSUE THREAD

**Issue by mmotahar** [OCA/server-tools#730]
Hello team !

See below usecase for an issue preventing use of mass editing for normal users and why we had to only make it visible to admin 

Usecase:
Create a new opportunity assign it to a new salesrep.
You see the tracking in openchatter from A --> B

Current Situation:
Now do it with mass editing and assign sales rep field from user B --> user A
if you open the formview again you won't see this change tracked anywhere.

Expected situation:
It has to post the same change as user can do by manually updating those records otherwise it may not be functional for the sales team to work with as they can bypass the auditing mechanism in openchatter for them.

I logged it here as well https://github.com/JayVora-SerpentCS/MassEditing/issues/16

**Comment by mmotahar** [comment]
I realized that it's logged here and issue is there since v8 !  https://github.com/OCA/server-tools/issues/577

**Comment by pedrobaeza** [comment]
Mass editing doesn't update the regular way for several reasons like performance, because it's an admin tool, so it's not expected to have things like chatter tracks and so on.
