### ISSUE TITLE
[10][mass_editing] mass update doesn't update the active field

### ISSUE THREAD

**Issue by mmotahar** [OCA/server-tools#731]
Create a new opportunity and set it to inactive.
select it from the view and click on mass update.
See below message : #

![boolean_doest_work](https://cloud.githubusercontent.com/assets/4558819/22770320/92c45fca-eeca-11e6-988f-75598d22a7f9.png)

**Comment by rafaelbn** [comment]
Hello!! @seyed-mohammad-motahar 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- https://github.com/OCA/server-tools/pull/848
- https://github.com/OCA/server-tools/pull/849 
- https://github.com/OCA/server-tools/pull/786

Thanks
