### ISSUE TITLE
[10.0] [base_external_dbsource_mysql] Password in clear in error messages

### ISSUE THREAD

**Issue by qtheuret** [OCA/server-tools#742]
Revision: https://github.com/OCA/server-tools/commit/2d47eb47c4ad221ff81fb36e857c9712e939793a

If you have an error during your connection with MySQL server, the error message displays the password in clear. I didn't set the password in the connection string. The password is set on the password field.

Please see the screenshot
![github_clear_pwd](https://cloud.githubusercontent.com/assets/728779/23134286/8095601a-f794-11e6-9ae4-6bbbfcc0d827.png)

**Comment by lasley** [comment]
Hi @qtheuret - Thank you for the report.

You can only see this information if you already have access to view the plain text password. The only group with access to this information is `base.group_system`, which basically means that only the superuser & the system can see this data.

The alternative is to completely remove the error from this window altogether, which is only displayed when using the connection test feature. IMO insight into the connection string that is used is incredibly valuable during the connection test, and the plaintext password would already be known to anyone able to click the button. 

Thoughts?

**Comment by qtheuret** [comment]
The password has been entered in the password field which hide the text value. I did not write the password in the connection string in plain text, so, it is why I was suprised to show the password in the error message.

**Comment by qtheuret** [comment]
The error is displayed because my connection string is not like this one : 
`
mysql://user:%s@server:port/dbname 
`
but like this one:
`Server=myServerAddress;Database=myDataBase;Uid=myUsername;
`

**Comment by lasley** [comment]
> I did not write the password in the connection string in plain text

That field just obscures the password and provides a false sense of security. Absolutely everything is plain text in Odoo. There are a few modules that circumvent this, such as [Red October](#673) or [Keychain](#644). Neither of these would stop Odoo from reading the password though, or from throwing it in errors. This error is only admin facing though, so I think it is negligible & removing would do more harm than leaving.

> The error is displayed because my connection string is not like this one :

Automatic connection string generation is not a feature of this module at this time. You would need to update from the default as specified in the ReadMe & the help attribute of the connection string field.
