### ISSUE TITLE
[10.0][auto_backup] Disables general settings menu entry

### ISSUE THREAD

**Issue by yajo** [OCA/server-tools#748]
In Odoo 10.0, `auto_backup` addon adds its menu entry under the *General Settings* one, but that is causing that *General Settings* cannot be clicked anymore.

It should put its menu under another entry or under a section in that configuration page.

**Comment by eLBati** [comment]
Fixing with https://github.com/OCA/server-tools/pull/772

**Comment by lasley** [comment]
This has been fixed per https://github.com/OCA/server-tools/pull/772#issuecomment-295676432
