### ISSUE TITLE
[9.0] mass_editing: issue with product tags module

### ISSUE THREAD

**Issue by moy2010** [OCA/server-tools#749]
module: mass-editing
version: 9.0

**Steps to reproduce**
- Download product-tags module: https://www.odoo.com/apps/modules/9.0/product_tags/
- Create the mass editing field for product tags in the product template model.
- Add one or multiple product tags to a single product: ok
- Add one or multiple product tags to more than one product: error message
- error message says "ValueError: Expected singleton: product.template(1847, 2804)"

**Current behavior**

- mass-editing works only when one product is selected

**Expected behavior**

- It should work when multiple products are selected

**Comment by rafaelbn** [comment]
Hello!! @moy2010 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- https://github.com/OCA/server-tools/pull/848
- https://github.com/OCA/server-tools/pull/849 
- https://github.com/OCA/server-tools/pull/786

Thanks
