### ISSUE TITLE
[10.0] Travis broken

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-tools#758]
The recent merge of https://github.com/OCA/server-tools/pull/718 broke travis.

commit number : 385e9b7b2c1ce1ffad5d047f944ee40508e65816

see last commits history.
https://github.com/OCA/server-tools/commits/10.0

**Comment by florian-dacosta** [comment]
@legalsylvain 
https://github.com/OCA/server-tools/pull/762 seems to fix travis

**Comment by lasley** [comment]
Confirmed fixed, closing!
