### ISSUE TITLE
[ 10 auto_backup] pysftp version may block backup

### ISSUE THREAD

**Issue by EBII** [OCA/server-tools#782]
hello 
i just install auto_backup and i made pip install pysftp. It was the 2.9 version. 
i can not connect to external storage with pysftp due to error: SSHException: No hostkey for host XXXX
after search around it seems due to update of pysftp 
Change Log
    0.2.9 (current, released 2016-07-04)
        bugfix: correctly implement hostcheck. Now, be default pysftp will verify the host. See pysftp.CnOpts.hostkeys
        added pysftp.Connection.remote_server_key - used to retrieve the remote hosts server key.

so i resolve my issue with 
pip install pysftp==0.2.8

maybe we need to add destination storage public host key somewhere ? 
regards

**Comment by lasley** [comment]
I was planning on updating `auto_backup` to use [`connector_sftp`](https://github.com/OCA/server-tools/pull/985), which uses [`base_external_system`](https://github.com/OCA/server-tools/pull/993) and does include support for host key checking (as well as the overriding of it)
