### ISSUE TITLE
[RFC] base_data_integrity: Sign & Hash Records

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#787]
This module will provide the ability to verify the integrity of a data record. This is required as part of HIPAA in the US for medical records, but could also be great for some other uses.

It will allow you to select models to monitor, and will override the create/write methods using the base model in order to inject the integrity method.

The integrity method will sign each applicable data record using a private key that is provided to Odoo. This key will be a file on the server, and the path will be configured with a system parameter. Because Odoo needs to be able to read this file, it might make sense to simply allow a file upload somewhere instead, which would allow for no server config. **This feature will be deferred into another module in order to allow for different signature methods (OpenSSL, CFSSL, etc).**

An option will be provided to also store an SHA hash of the record contents on create/write. This will allow for the verification that data has not been corrupted in some way while leaving the signature in tact. The hashing option will be at the model level, just like the signature option. 

The hash will be stored in a new table `data.integrity.hash`. A method would be provided in the BaseModel, which would then be able to be accessed by all models for the hash get/set. Something like

``` python
@api.multi
def data_integrity_hash(update=False):
    old_hash = HashModel.search(domain)
    if update:
       old_hash.upsert(data)
    return old_hash
```

Another option at the model level will be record locking. Options would be provided to disable write or unlike for records matching the filter. This is described further in the [comments](https://github.com/OCA/server-tools/issues/787#issuecomment-289059654). A `LockedError` should be raised in the event of this.

Both the hashing and record locking options will utilize a filter to match records that should receive a hash, and no longer be able to be written/unlinked - based on the options selected.

The options should be settable via a `data.integrity.model` model, which allow for the selection of:
* A model to monitor
* Enable Signature
* Enable Hashing
   * Fields to include in hash
      * If a relation is provided, use its hash if existing else '%s.%s' % (record._name, record.id)
  * Hash generation should be in isolated method to allow inherited overrides
  * Salt to include in hash
     * Salt generation/return should be in isolated method to allow inherited overrides
* Enable Record Locking
* Domain filter for hash/record lock

If an applicable data record does not contain a signature, if the signature is invalid, or if the hash is invalid - an `InvalidSignatureError` will be raised. All custom errors will be a subclass of the custom error `IntegrityError`.

The `IntegrityError` should accept the associated record as an argument, as well as an arg for the check that failed (which would be provided by the child `__init__`). It should create a new `data.integrity.error` & trigger a notification on that record.

The `data.integrity.error` model should store the error, record id, model name, have a state, and _inherit from `mail.thread`. The record should automatically add users that are part of the security group able to configure the integrity options.

A Kanban view should be provided for the errors, with the following states:
* New
* Verifying
* Resolved

Any user browsing to a record through the error queue will circumvent the record's error, but will not be able to resave the record without first releasing the integrity lock via the queue record.

Releasing the integrity lock will generate a new hash and signature. If the error was due to an attempted record action (write/unlink), the release would perform the action on the record. Releasing the lock would also move the error into the resolved state.

Anyone have any thoughts on this, or know some pre-existing code I can base on?

**Comment by dreispt** [comment]
What content of the record will be fed to hash? 
All table fields except the ones in a black list (such as create_uid and create_date)?
In some cases we also want the content in related o2m lines to be hashed.

For example, to hash/sign an Invoice, the hash should work on header data and line date, plus some related information, such as the customer and our company VAT numbers.

This particular case can't be automatically handled by the generic implementation, so some code or configuration hooks should be available to ease the implementation of the above scenario.

The Portuguese legal requirements for invoices and waybills have something like this.
The hash is printed in the document and a data file with all the invoices must be sent to tax authorities every month. In this case the hash is computed using the invoice data, plus the hash and number of the generated for the previous invoice.

I also see this feature relevant for the French finance act to be in force in 2018.

**Comment by lasley** [comment]
Maybe it would make sense to allow for the customization of what specific fields get hashed then?

This could be accomplished by adding an m2m for the fields that should be hashed when selecting the model. 

Hashing the related records is going to be a bit rough I think though - I'm not really sure how I'd drill down through one field to another by using the `ir.model`/`ir.model.fields` pattern.

What about recursive hashing though? In the example of an invoice/invoice line, we would just validate both right? The hash of the invoice lines inside of the invoice could simply be the database IDs, or maybe even the hash from the child records - although guaranteeing that the child is written before the parent could be a bit tricky.

**Comment by dreispt** [comment]
Yes, that was my point: it should be extensible (as usual...).

There are a few steps involved:
a) building a string to hash
b) computing the hash
c) storing the hash

IMO the default "naive" method to build the string to hash would be a white list of model fields (the m2m you mention) to generate it. A hook method should be provided that, if implemented, would override the default behaviour.  The more complex header/lines/related data cases should be implemented using that hook. In my previous example, I even need to browse the previous Invoice to get it's computed hash. This can only be done with code.

The hash storing logic may also need specific extensions. Taking the Invoice example I gave before, we only want to compute the hash when the Invoice goes into a "Confirmed" state.  So, at least having specific conditions on when to compute and store the hash will be something frequently needed.

It comes to mind that it can make sense to add an extra feature, allowing to prevent change in the records once a hash was computed and stored.

**Comment by lasley** [comment]
> So, at least having specific conditions on when to compute and store the hash will be something frequently needed.

Almost like the filters provided in server actions? Basically if the record matches the filter after it is updated, the hash is generated?

> It comes to mind that it can make sense to add an extra feature, allowing to prevent change in the records once a hash was computed and stored.

Yup that's part of the plan too, albeit slightly more long term. We're trying to do away with [medical_base_history](https://github.com/LasLabs/vertical-medical/tree/release/10.0/medical_base_history), which does lock the records at a specific point. Turns out we didn't hit everything we needed in terms of the verification there though, hence the rewrite towards a more abstract framework.

**Comment by dreispt** [comment]
> Almost like the filters provided in server actions? Basically if the record matches the filter after it is updated, the hash is generated?

Yes, something like that would work.
The use case in my mind is to trigger the hash (and lock for writes) when the record reaches a certain state. Filters or evaluated expressions are a generic solution supporting that.

**Comment by lasley** [comment]
@dreispt - I updated the RFC with the final plan. Let me know if I missed something

**Comment by lasley** [comment]
After investigation of #1064 (base_blockchain), these align slightly. Linking them
