### ISSUE TITLE
[mass editing] Feature request: Add/Substract amount or % to a float field

### ISSUE THREAD

**Issue by arnelap** [OCA/server-tools#791]
It would be super nice if you can mass edit for example product prices to be 10% higher, or add 5 usd to current price. 

![capture](https://cloud.githubusercontent.com/assets/9718808/24240449/39e541ae-0fe4-11e7-9716-4f8ec25070be.PNG)

**Comment by arnelap** [comment]
or allowing some regex maybe?

**Comment by rafaelbn** [comment]
Hello!! @arnelap 

Maybe you could review this PR? This PR merge should improve and fix some issues

PRs:

- https://github.com/OCA/server-tools/pull/848
- https://github.com/OCA/server-tools/pull/849 
- https://github.com/OCA/server-tools/pull/786

Thanks

**Comment by rafaelbn** [comment]
- [x] - https://github.com/OCA/server-tools/pull/848
- [x] - https://github.com/OCA/server-tools/pull/849 

Merged! :smiley:

**Comment by pedrobaeza** [comment]
Unrelated features and wishlists.
