### ISSUE TITLE
RFC exception management for supervision purpose

### ISSUE THREAD

**Issue by bealdav** [OCA/server-tools#792]
When you use a solution like Sentry https://github.com/OCA/server-tools/pull/761 , 
you need to deal with exceptions: filter these which must be sent to sentry, according to rules:

1.  some exceptions are critical and must be sent
2.  some are not critical but if it happens often, information could be relevant
3.  some are required to follow for a certain types of user: (portal, ecommerce, etc)
 
Most exceptions class in Odoo/Oca are UserError (old Warning) or Access...

Whatever you choose to send or not to sentry, there is no way to have a behavior according to user group (portal user vs internal user by example)

I think it could be interesting to have a behavior different according to the user group.

How to do that ? 

Maybe not directly raise an exception but manage by another way according to the kind of user which class Exception should be raised.

Then it becomes easy to send to sentry the adhoc alert.

Is there other other options to do that ?

**Comment by lasley** [comment]
@bealdav - Hmmmm what would the use case be for sending the error in one case and not another?

I think this would probably need to be in the proprietary handlers, unless we came up with some sort of central exception interface/adapter framework to build everything on top of.
