### ISSUE TITLE
[RFC] base_fields_ephemeral: Cache-only storage

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#797]
This module will provide a field that will be used for ephemeral datasets only, meaning that the data will not live past the session cache. 

Use case for this would be an external system password in a wizard that should never actually touch the database. Another possible case could be the transmission of PCI protected data to a merchant provider without having to worry about where the data ends up. This will be great for HIPAA and PCI compliance risk assessments, because the data obviously can't travel beyond the current request thread.

This will be accomplished by subclassing the field types and stubbing out their `convert_to_write` methods to create an `EphemeralType` field. I currently only need Text, so this module will only contain an `EphemeralText` to start with. 

For performance reasons, the column itself will be created as a bool in the database. It will always be 0. It would be nice if the column could just not be created such as in the case of a computed, but I haven't explored that just yet.

Another consideration of this module will be to block the logging module from outputting it, which could result in unintentional compromise of the confidential data.

This should be a pretty simple module, but will allow for the transmission of protected data without touching anything other than the application that had to be touched anyways. The only thing that could be slightly more secure would be transmission directly to the external systems, which isn't possible in my use case.

Does anyone have any thoughts on this, or know of some pre-existing code we can base from?

**Comment by jcdrubay** [comment]
:+1: I have been in need of this in the past

**Comment by lasley** [comment]
Turns out it's actually quite hard to do this in all instances, and definitely not the way originally planned. I'm about halfway there though & I'm pretty pissed off at it, so I assume it'll be cracked soon!

**Comment by hbrunn** [comment]
shouldn't `fields.Serialized(compute=lambda self: None)` allow what you want?

**Comment by lasley** [comment]
I didn't try with `Serialized`, but I did try that strategy with `Char`. I had to use an inverse too, because I also need the field user editable. This is what my code looked like:
```python
password = fields.Char(
    compute=lambda self: None,
    inverse=lambda self: None,
)
```

Unfortunately, the value is coming up `False` in cache. My current strategy is on the field itself, leverages the Werkzeug local, and looks like this:

```python
class EphemeralChar(fields.Char):

    column_type = ('bool', 'bool')

    def get_local_name(self, record):
        return '%s.%s.%s' % (record._name, record.id, self.name)

    def get_local(self, record):
        value = getattr(record.env._local,
                        self.get_local_name(record),
                        self.null(record),
                        )
        _logger.debug('Get local %s - "%s"', record, value)
        return value

    def set_local(self, record, value, type_=str, force=False):
        _logger.debug('Set Local %s, %s', record, value)
        if value or force:
            setattr(record.env._local,
                    self.get_local_name(record),
                    type_(value),
                    )
        return self.get_local(record)

    def convert_to_cache(self, value, record, validate=True):
        return self.set_local(record, value)

    def convert_to_column(self, value, record):
        _logger.debug('Convert to col %s, %s', value, record)
        self.set_local(record, value)
        return True

    def determine_value(self, record):
        record._cache[self.name] = self.convert_to_cache(
            self.get_local(record),
            record,
            validate=False,
        )
        _logger.debug('Cache %s', record._cache[self])

    def determine_draft_value(self, record):
        record._cache[self.name] = self.convert_to_cache(
            self.get_local(record),
            record,
            validate=False,
        )
        _logger.debug('Draft Cache %s', record._cache[self])
```

It works in most instances, but I'm still running into some edge cases where it doesn't. I think the problem is that I haven't been able to truly identify where the entry point for the field value is, so there are instances when the local isn't being set.

I'm at the point where I'm basically just replacing random interface methods and seeing what happens ¯\\\_(ツ)\_/¯

**Comment by lasley** [comment]
Alright so it turns out the issue is that in wizards the create and action buttons are actually being performed in different web requests. This is creating a disparity between the caches, and thus yields the `False` from both the Werkzeug locals and the record caches.

The easy solution here is to use the request session, but then we're back into problem territory. The Odoo password is already stored in plaintext here, so this is already a target for malicious intent. I would like to avoid adding into that target if at all possible.

I don't have a better solution though, so maybe someone has an idea. Otherwise, I will continue pondering & will update this RFC when I have something more.

Request breakdown (mainly for my future reference):
1. `write` Request Payload: 
         ```
{"jsonrpc":"2.0","method":"call","params":{"model":"red.october.vault.activate","method":"write","args":[[7],{"admin_password":"1234","admin_password_confirm":"1234"}],"kwargs":{"context":{"lang":"en_US","tz":"Europe/Brussels","uid":1,"active_id":7,"active_ids":[7],"active_model":"red.october.vault","search_disable_custom_filters":true,"params":{"action":81}}}},"id":150537847}
        ```
2. `call_button` Request Payload: 
         ```
{"jsonrpc":"2.0","method":"call","params":{"model":"red.october.vault.activate","method":"action_save","domain_id":null,"context_id":1,"args":[[7],{"lang":"en_US","tz":"Europe/Brussels","uid":1,"active_id":7,"active_ids":[7],"active_model":"red.october.vault","search_disable_custom_filters":true,"params":{"action":81}}]},"id":982627109}
        ```
3. `search_read` Request Payload: 
         ```
{"jsonrpc":"2.0","method":"call","params":{"model":"red.october.vault.activate","method":"search_read","args":[[["id","in",[7]]],["admin_user_id","is_active","vault_ids","admin_password_confirm","admin_password","display_name","__last_update"]],"kwargs":{"context":{"lang":"en_US","tz":"Europe/Brussels","uid":1,"active_id":7,"active_ids":[7],"active_model":"red.october.vault","search_disable_custom_filters":true,"params":{"action":81},"bin_size":true,"active_test":false}}},"id":698534465}
        ```
4. `read` Request Payload: 
         ```
{"jsonrpc":"2.0","method":"call","params":{"model":"red.october.vault","method":"read","args":[[7],["name","host","port","is_active"]],"kwargs":{"context":{"lang":"en_US","tz":"Europe/Brussels","uid":1,"bin_size":true}}},"id":426057874}
        ```

**Comment by lasley** [comment]
Alright so the above challenges ended up basically just being the way things work, so I would deem this module technically infeasible. My solution was to JavaScript everything 😦
