### ISSUE TITLE
 [ 10 date_range] Error Applying Filters

### ISSUE THREAD

**Issue by JuanJoseGomez** [OCA/server-tools#807]
Depending on the web browser I can see two different errors when I try to apply a filter:
Uncaght TypeError: Cannot read property 'name' of undefined
or
Uncaght TypeError: this.field is undefined

![imagen](https://cloud.githubusercontent.com/assets/7678088/24799999/7d39d3b4-1b9e-11e7-9e48-9200477d7802.png)

![imagen](https://cloud.githubusercontent.com/assets/7678088/24799891/f7359910-1b9d-11e7-9c0c-b0d5dfa5ab3e.png)

**Comment by sbidoul** [comment]
@JuanJoseGomez thanks for reporting.

Could you provide more details on the circumstances:
- which browsers
- which Odoo version
- exact steps to reproduce the error on https://runbot.odoo-community.org/runbot/repo/github-com-oca-server-tools-149
