### ISSUE TITLE
[RFC] user_threshold: Impose Superficial User Limit

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#811]
This module will provide the ability to limit the amount of non-portal/public user limits at the following levels:

* Total users per database - System parameter
* Total users per company - Company option

It will provide a security group for the ability to administer the amount of these users, and will restrict view/edit of the parameter & option to that group.

It will look for the environment variable `USER_THRESHOLD_HIDE` to be `1`. If it is, the security option should be removed from all users on all databases (during Odoo start). The security option should also be removed from the view so that administrators cannot add it back.

Also if this trigger is set, we will need to explicitly disable the ability for the sudo user to control these options. We will need to add explicit checks in the relevant models to circumvent this.

This will allow for a lockout of these permissions, and therefore a (possibly remote) configurable user threshold that cannot be circumvented without the proper user - in my case a service account.

We will also create a glue module `user_threshold_immutable` that will auto install if [user_immutable](https://github.com/OCA/server-tools/issues/810) is installed. That module will simply not count the immutable users towards the threshold.

Anyone know of anything existing, or have thoughts on implementation?

**Comment by tedsalmon** [comment]
To add to this RFC, we will need to add an environment variable named `USER_THRESHOLD_USERS` which will hold a CSV list of users who are always exempt from the thresholds. This will allow us to filter out any users who are not currently counting towards the threshold but should be.

We should also add an attribute to `res.users` to hold the exemption flag. This flag is referred to in the above as 'the security option' in the third paragraph.

**Comment by lasley** [comment]
Closing to track in #836
