### ISSUE TITLE
Installing addon from wheelhouse with pip broke odoo package

### ISSUE THREAD

**Issue by Fenkiou** [OCA/server-tools#815]
First of all, this issue isn't specific to this repo but to all (I think, didn't try on all addons), I'm sorry to put this here but wasn't sure if I had to open an issue on https://github.com/acsone/setuptools-odoo or any other OCA repo.

Usually, to have a clean dev environment, I do the following steps:
- create a virtualenv
- clone odoo sources
- install requirements with pip `pip install -r requirements.txt`
- link odoo in python env `python setup.py develop`

After this, I can:
```
➔ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import odoo
>>> dir(odoo)
['SUPERUSER_ID', '_', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', 'addons', 'api', 'cli', 'conf', 'evented', 'exceptions', 'fields', 'http', 'loglevels', 'models', 'modules', 'multi_process', 'netsvc', 'os', 'osv', 'registry', 'release', 'report', 'service', 'sql_db', 'sys', 'time', 'tools', 'workflow']
>>>
```

I use https://wheelhouse.odoo-community.org/ to install OCA addons with pip. But when installing any addons from the wheelhouse, all modules from odoo package are missing:
```
➔ pip install odoo10-addon-auditlog
➔ python                                     
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import odoo
>>> dir(odoo)
['__doc__', '__name__', '__path__', 'addons']
>>>
```

However, if I clone server-tools and install auditlog (`python setup.py install/develop`) from the setup folder, the problem doesn't appear...

I don't know why this happen, this is not related to [this issue](https://github.com/acsone/setuptools-odoo/issues/10) because even after applying the patch proposed, the behavior remains the same.

**NOTE:** This is not a real issue as odoo works as expected, the problem is that I use vim that use my virtualenv to retrieve definitions from odoo and if I install any OCA addon with pip, vim can't find odoo definitions anymore as they're not exported

**Comment by sbidoul** [comment]
What you observe is correct. The best place for this issue is https://github.com/acsone/setuptools-odoo. Would you mind reopening it there? I'll write the explanation and a workaround.
