### ISSUE TITLE
[BUG] company_country module missing?

### ISSUE THREAD

**Issue by astirpe** [OCA/server-tools#838]
In this repo (server-tools, 10.0 branch) I'm noticing a folder `company_country/i18n` that seems to be part of a module not yet committed: 

https://github.com/OCA/server-tools/tree/10.0/company_country/i18n

To me it looks like that Transifex added some dirty data. Am I wrong?

**Comment by pedrobaeza** [comment]
Yeah, I have seen this also, but as we are switching in short to Weblate, I think we can live with this.

I think the source of the problem comes from pushing to an OCA branch by any of the users that have writing permissions.
