### ISSUE TITLE
[RFC] Service Oriented Odoo

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#853]
I am working on a new architecture design to split Odoo across multiple dedicated application instances, all linking to the same database & file store. This will provide us somewhat of a service oriented approach to Odoo, without having to actually distribute via events. 

In my bit of experimentation before creating this RFC - I was able to DoS the website application instance, but the web instance was chugging along like a champ. This creates a physical isolation between our application layers, and can insulate potential slash-dots.

It would look something like this (sorry for the extra stuff, this is meant for something bigger - relevant portion is the bottom-most section):

![soa odoo](https://user-images.githubusercontent.com/7397578/26947980-95871fc2-4c49-11e7-87cf-8ee95a813c94.png)

One of the main issues I foresee with this architecture is that we will create a competing race for the scheduled task runs among the distributed instances. In this light, we need a module that will disable scheduled tasks with an environment variable - I don't think this is already possible.

Beyond this - most of the work will be handled by the load balancer, so modules aren't necessarily required. All instances are technically capable of performing any action, so it's not a disaster if something misdirects.

I'm probably missing some things here, so this will be a live document. I'd be interested to hear if anyone else has done anything similar to this.

**Action items:**
- [ ] Module to disable scheduled tasks with an environment variable

**Comment by Garamotte** [comment]
If you mean `ir.cron` by "scheduled tasks", disabling them is already possible (at least in workers mode, I didn't check in threaded mode) in Odoo's configuration file: `max_cron_threads = 0`.
(Edit : Looking at the code, it seems to work in both workers and threaded modes)

**Comment by dreispt** [comment]
AFAIK Odoo application server is designed to be able to scale by adding more workers or more application servers side by side.
The restriction is that they must share the same fileserver (for session and attachment data) and db server.
And you can setup your load balancing so that web client request to a group of app servers and website requests go to another group of app servers.

If you have no problem with the two requirements, AFAICS you have it all out of the box.

**Comment by yajo** [comment]
Yeah, I was going to say exactly what @sylvain-garancher and @dreispt just said: all is already there, still from the pre-docker era.

If you share the same base image among backend and frontend instances, you can just launch the frontend ones adding `--max-cron-threads=0` to the boot command.

I hope that soon [Infinit](https://infinit.sh/) hits 1.0  and makes filestore sharing much easier.

**Comment by lasley** [comment]
Hooray thanks @sylvain-garancher, @dreispt, @Yajo - you are most certainly right - this works out of the freaking box! I ❤️  Odoo

> I hope that soon Infinit hits 1.0 and makes filestore sharing much easier.

Have you looked into GlusterFS? This is the [recommended approach by Red Hat](https://www.redhat.com/en/technologies/storage/gluster)

**Comment by rvalyi** [comment]
@lasley @dreispt I also inform or remind you that there is a PR and other prototypes around of a Redis based scalable Odoo session model:
https://github.com/odoo/odoo/pull/12515

I would be very happy to this is feature alive and OCA maintained somewhere...

**Comment by yajo** [comment]
Yeah @lasley I already looked into GlusterFS. Indeed the best production solution as of today, but I still keep the eye pealed for Infinit since it seems to have a better design, and [a Docker volume plugin](https://infinit.sh/documentation/docker/volume-plugin) (they were bought by Docker for some reason...).

**Comment by lasley** [comment]
@Yajo Ohhhhhh that's nice- I'm gonna have to keep an eye on Infinit too!
