### ISSUE TITLE
ERROR "auth_signup_verify_email" is missing a module

### ISSUE THREAD

**Issue by MosabWadea** [OCA/server-tools#861]
hello
I am trying to install `auth_signup_verify_email` on my odoo 10.0 but it is giving me this error:

`Unable to install module "auth_signup_verify_email" because an external dependency is not met: No module named validate_email`

I have installed the `validate_email` for python using `pip install validate_email` and still the same issue

**Comment by pedrobaeza** [comment]
You haven't installed the Python library in the correct environment or you won't get the error. Maybe you haven't restarted your Odoo server. Anyway, it's not a fault of the module itself, so I close the issue.

**Comment by MosabWadea** [comment]
OK good
Can you please help me to know which validate_email module to install or if there any specific thing I should do?

**Comment by pedrobaeza** [comment]
It's a Python library, not a module.

**Comment by MosabWadea** [comment]
yes I am familiar with that and I have installed the lib using `pip install validate_email` and this is the response of the command after I run it again:

```
Collecting validate_email
Installing collected packages: validate-email
Successfully installed validate-email-1.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

then I ran `pip install --upgrade pip` and this is the response:

`Requirement already up-to-date: pip in $HOME/.local/lib/python2.7/site-packages`

I think the library may not be installed in the correct location.. I have restarted odoo many times and updated the apps list in odoo but still the same error appears

**Comment by pedrobaeza** [comment]
You have to check with PYTHONPATH is using your Odoo. Maybe it's using a virtual environment, but as said, this is not the place for helping you with deployment issues.
