### ISSUE TITLE
Tried to connect odoo 10 with MySQL database

### ISSUE THREAD

**Issue by NaziburR** [OCA/server-tools#868]
I have tried to connect odoo 10 with MySQL database using External Database Sources. But I am getting this error. How to solve this issue?
`ParseError: "Wrong value for base.external.dbsource.connector: 'fdb'" while parsing file:///C:/Program%20Files%20(x86)/Odoo%2010.0/server/odoo/addons/base_external_dbsource_firebird/demo/base_external_dbsource.xml:3, near
<record model="base.external.dbsource" id="demo_firebird">
        <field name="name">Firebird Demo</field>
        <field name="conn_string">User=firebird;Database=SampleDatabase.fdb;DataSource=localhost;Port=3050;Dialect=3;Charset=NONE;Role=;Connection lifetime=15;Pooling=true;MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;</field>
        <field name="password">password</field>
        <field name="connector">fdb</field>
    </record>`

**Comment by lasley** [comment]
Hi @NaziburR - You either need to install the `fdb` Python package into your Odoo environment, or uninstall the `base_external_dbsource_firebird` module from your Odoo instance.

I am closing this, please drop your feelings in odoo/odoo#14850 - which is why we have this ghettoness
