### ISSUE TITLE
[8.0/Master] Feature Request - <disable_openerp_online> to remove /website/info from public view

### ISSUE THREAD

**Issue by lukebranch** [OCA/server-tools#87]
I'd like to suggest a feature for the module //OCA/server-tools/disable_openerp_online . By default the 8.0/Master branch of Odoo includes a view that displays all installed modules in a given database to the public so long as the website module is installed.

The code that controls this feature is in /odoo/addons/website/controllers/main.py, specifically the following snippet:
    @http.route('/website/info', type='http', auth="public", website=True)

This is currently being discussed in the thread for Issue #3546 in /odoo/odoo/issues if you are interested.

I would like to suggest either including the over-riding/hiding of the /website/info feature in disable_openerp_online, or an OCA-built module in server-tools designed specifically to remove this feature (at least from anyone without 'Technical Features' access rights) as it poses a security threat by publicly displaying your database's installed modules, both Odoo SA approved and community modules with less QC checks than Odoo SA, or OCA modules.

**Comment by dreispt** [comment]
Issue link: https://github.com/odoo/odoo/issues/3546
This should not be on `disable_openerp_online` since it would mean adding the `website` dependency to it.

**Comment by lukebranch** [comment]
@dreispt ,

Thanks for the correction. Would you suggest the OCA build a separate module in server-tools if they consider this feature request?

I'd be happy to submit code, however I am not by any means an experienced Odoo developer and therefore i'm certain the submission would not meet OCA requirements.

**Comment by dreispt** [comment]
@lukebranch AFAICT it's not clear if Odoo accepts it as a bug or if it's a "feature". For the former, it should be a fix for OCB, for the later, a new module here.

Submitting PRs to OCA is an excellent way to learn. You could just try submitting one and be ready to accept the feedback, and don't be afraid to ask you you don't understand something. I'm sure I can say that reviewers try to be helpful.

**Comment by lukebranch** [comment]
@dreispt ,
I think it may be a considered a feature.

I'll build a simple module to over-ride the feature and submit it to OCA once i've read a bit more about OCA requirements. Thanks for the advice.

**Comment by dreispt** [comment]
I think this discussion is closed.
