### ISSUE TITLE
[10.0] [sentry] NameError: name 'raven' is not defined

### ISSUE THREAD

**Issue by artux404** [OCA/server-tools#879]
After #761 was merged we are getting the following error "NameError: name 'raven' is not defined".
This happens because the sentry module has the static directory inside. It must be removed to solve the issue.

**Comment by bealdav** [comment]
PR https://github.com/OCA/server-tools/pull/881

**Comment by artux404** [comment]
@bealdav if you remove the static folder, problem is solved. it happened similar issue for module server_environment_ir_config_parameter, and static folder was removed but I've seen you've found another workaround. Hope that will be merged as soon as possible.

**Comment by pedrobaeza** [comment]
That's not the actual solution, as the static folder can be there for a lot of reasons. See https://github.com/OCA/server-tools/pull/883. I close this issue as there's a PR already.

**Comment by artux404** [comment]
@pedrobaeza Okk, perfect. Thx
