### ISSUE TITLE
8.0 Incompatibility between base_view_inheritance_extension and stock_packaging_usability_ul

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/server-tools#885]
If you try to install the module base_view_inheritance_extension with the module stock_packaging_usability_ul from here : https://github.com/OCA/stock-logistics-tracking
The installation fail.
I do not have the time to look at here more (maybe latter) , but as I have detected the issue I think it worth to share it.

**Comment by StefanRijnhart** [comment]
I have a problem installing a module that modifies &lt;xpath expr="//field[@name='invoice_line']/tree/field[@name='discount']"> from account.invoice_supplier_form: Element cannot be located in parent view. See buildjob https://travis-ci.org/OCA/account-invoicing/jobs/248811991 from PR https://github.com/OCA/account-invoicing/pull/284. The problem does not occur if base_view_inheritance_extension is not installed.

Notifying @hbrunn as the author of the module.

**Comment by StefanRijnhart** [comment]
Managed to solve my problem by changing the order of the attributes. Seems like base_view_inheritance_extension applies the attributes atomically and then searches the view again for the given xpath expression. As it happened, my first attribute invalidated the expression so the second attribute could not be applied anymore:

```
                <xpath expr="//field[@name='invoice_line']/tree/field[@name='discount']" position="attributes">
                    <attribute name="name">discount_display</attribute>
                    <attribute name="string">Discount (%)</attribute>
                </xpath>
```

**Comment by StefanRijnhart** [comment]
@sebastienbeau the same thing happens in https://github.com/OCA/stock-logistics-tracking/blob/8.0/stock_packaging_usability_ul/wizard/stock_transfer_details.xml#L20. Try putting the attribute that changes the button's name last.

**Comment by hbrunn** [comment]
yes, makes sense to add this to the list of known bugs. not sure if it's simple to solve though, and the workaround seems straightforward enough
