### ISSUE TITLE
[10.0] [base_external_dbsource] PostgreSQL Password is not in clear, will faile the test connection

### ISSUE THREAD

**Issue by devinhuang** [OCA/server-tools#888]
When we created a PostgreSQL connection, the password must in clear. 
If not, it will failed the [Test Connection].

After traced the code, I found the method `connection_open_postgresql`  should use `self.conn_string_full` instead of `self.conn_string`

![issue](https://user-images.githubusercontent.com/10579316/27901375-68972efe-6264-11e7-9623-91234ebee9b7.png)

**Comment by lasley** [comment]
Thanks for the report @devinhuang - fixed in #895
