### ISSUE TITLE
Propose auth module to generate randomly user's password

### ISSUE THREAD

**Issue by legalsylvain** [OCA/server-tools#91]
Hi all, 

I recently developped an 'auth' module for my company (auth_generate_password). The features are: 
- Users can not change them password;
- Password are generated randomly and an email is send to them;
- an action is available to reinitialize many users passwords;

Maybe it can be usefull for other people in the community. If yes, please :+1:, and I'll share it.

If you want to check the code...
https://github.com/grap/odoo-addons-grap/blob/7.0/auth_generate_password/__openerp__.py

Regards.

**Comment by hbrunn** [comment]
That's certainly useful! In a review though, I would ask you to do the mailing via a template and have the password length configurable via an ir_config_parameter.

**Comment by legalsylvain** [comment]
Thanks for your answer. I did the PR #92 .
Regards.
