### ISSUE TITLE
8.0 Super Calendar: It do not display in the next months.

### ISSUE THREAD

**Issue by PereSau** [OCA/server-tools#910]
We are using the super_calendar module (version: '8.0.0.2.0' in Odoo 8 Debian 8) for several months, and it’s very useful.
We configure Project and Task with start and end dates but we have an important trouble, the lines do not appear in the next months, only in the first month. In the example, Project and Task start in Juny and end in August:
![1 super_calendar_projects_captura de pantalla 2017-07-26 a las 9 46 09](https://user-images.githubusercontent.com/29690764/28613414-9fd0eb56-71f2-11e7-96a9-e5e55d709b18.png)
![2 super_calendar_task_captura de pantalla 2017-07-26 a las 9 46 26](https://user-images.githubusercontent.com/29690764/28613417-9ffd5736-71f2-11e7-95c8-702018457a46.png)
![3 super_calendar_displayjune_captura de pantalla 2017-07-26 a las 10 28 13](https://user-images.githubusercontent.com/29690764/28613416-9ff93a7a-71f2-11e7-9faf-d664a28ce495.png)
![4 super_calendar_displayjuly_wrong_captura de pantalla 2017-07-26 a las 10 28 45](https://user-images.githubusercontent.com/29690764/28613418-9ffee272-71f2-11e7-8061-a9cc02669dc6.png)
![5 super_calendar_duration_captura de pantalla 2017-07-26 a las 10 33 40](https://user-images.githubusercontent.com/29690764/28613415-9ff7bbfa-71f2-11e7-8862-01bc925f8f8e.png)

I’m doing something wrong?

Thanks in advance,

**Comment by pedrobaeza** [comment]
Have you refresh values?

**Comment by PereSau** [comment]
Of course Pedro, but this example is independent of it, the last week in June is the first in July and it does not appear in July.

**Comment by pedrobaeza** [comment]
Then I can't help you as I'm not a direct user of this module (as I don't like the approach of "copying" data). Let see if other OCA member has faced the problem.
