### ISSUE TITLE
audit log

### ISSUE THREAD

**Issue by renatonlima** [OCA/server-tools#915]
Hello guys,

I am using auditlog in v8.0 and it works fine, but I think there is a problem. I'm monitoring an object, example: res.partner, but does not monitor relational fields, I think it's very important to have this information because if someone changes partner bank account (relational field), it should appear in res.partner log. Similarly, if you are monitoring a sales order and changes a sales order line, it should appear in the sales order logs. that makes sense?

**Comment by lasley** [comment]
@renatonlima - Just to confirm, you mean that when the data inside of the relational field is changed? Or just the relation itself? I.E. changing the analytic account on a sale order line from A to B, or changing the name of analytic account "A" to "B"?

**Comment by thomaspaulb** [comment]
I don't agree. In both cases this should be handled by an auditlog on "res.partner.bank", in the message we can refer to the partner that it was for to have a full log.
