### ISSUE TITLE
[10.0] auto_backup. Notification to followers of subtypes not sent

### ISSUE THREAD

**Issue by simmatica** [OCA/server-tools#923]
In the code:
Wrong
                subtype=self.env.ref(
                    "auto_backup.mail_message_subtype_failure"
Correct
                subtype="auto_backup.mail_message_subtype_failure"

Wrong and undefined subtype
                subtype=self.env.ref("auto_backup.failure")

**Comment by eLBati** [comment]
@simmatica thanks. Could you open a pull request?

**Comment by simmatica** [comment]
ok @eLBati
