### ISSUE TITLE
[9.0][module_auto_update] Remove hacks from module_auto_update

### ISSUE THREAD

**Issue by yajo** [OCA/server-tools#927]
Now that https://github.com/odoo/odoo/pull/18597 is merged, we can safely remove workarounds from https://github.com/OCA/server-tools/blob/9.0/module_auto_update/models/module.py#L54-L68

**Comment by pedrobaeza** [comment]
Please make the PR and also forwardport changes made in 9.0 to 10.0

**Comment by sbidoul** [comment]
@Yajo this one can thus be closed?

**Comment by pedrobaeza** [comment]
Yes, closing.
