### ISSUE TITLE
auth_totp + password_security - TOTP needs to come first

### ISSUE THREAD

**Issue by lasley** [OCA/server-tools#939]
When `auth_totp` and `password_security` modules are both installed on a server and the user needs a password change, the password change is required before MFA has been validated. 

This is a potential security hole that would allow an unauthorized user to change the password of an account without access to the MFA device. It's no more of a hole than is already existing in core though, because the valid password is still required.

**Comment by hbrunn** [comment]
this is one of the use cases I had in mind for https://github.com/OCA/server-tools/pull/876
You can simply depend on this module and conditionally on `auth_totp` in `password_security`, then you're done. Or, what's nicer, implement my proposal of conditional reverse dependencies in this PR, then you can add this to `auth_totp`'s manifest where it belongs imho

**Comment by lasley** [comment]
Exactly what I needed, thanks @hbrunn! I agree `rdepends_if_installed` is the best way to go here, so I'll look into implementing. Were you planning on forward porting the module or should I also plan on that?

**Comment by hbrunn** [comment]
glad it's useful. I fixed your comment and rebased, so you could do the honors if you like.

At the moment, I don't have plans for forward porting, so go ahead if you need it. And yes, given you guys always hammer on LGPL stuff, I won't complain if you change the license in the process ;-) Shouldn't be so much trouble, this part of the code didn't change a lot in the past years.

**Comment by lasley** [comment]
> do the honors if you like.

Woot I'll hit the button once we get a CI 🍏 !

> At the moment, I don't have plans for forward porting, so go ahead if you need it.

Sweet, I'll tackle the 9 and 10 then. Doing the migrations should get me deep enough into the operation of the code so that I have a better idea of how to implement the reverse depends.

> And yes, given you guys always hammer on LGPL stuff, I won't complain if you change the license in the process ;-) 

Hooray! 😆  that was admittedly going to be my next question

> Shouldn't be so much trouble, this part of the code didn't change a lot in the past years.

This was my thought as well - here's to hoping for a 1:1 conversion 🍻
