### ISSUE TITLE
[10.0][auto_backup] Sanity Check for test_db_backup

### ISSUE THREAD

**Issue by mpdevilleres** [OCA/server-tools#942]
there are 2 test functions with the name test_action_backup_sftp_remote_open located at line 150 and 162.

    # line 150    
    def test_action_backup_sftp_remote_open(self):
        """ It should open remote file w/ proper args """
        rec_id = self.new_record()
        with self.mock_assets() as assets:
            with self.patch_filtered_sftp(rec_id):
                conn = rec_id.sftp_connection().__enter__()
                rec_id.action_backup()
                conn.open.assert_called_once_with(
                    assets['os'].path.join(),
                    'wb'
                )

    # line 162
    def test_action_backup_sftp_remote_open(self):
        """ It should open remote file w/ proper args """
        rec_id = self.new_record()
        with self.mock_assets() as assets:
            with self.patch_filtered_sftp(rec_id):
                conn = rec_id.sftp_connection().__enter__()
                rec_id.action_backup()
                conn.open.assert_called_once_with(
                    assets['os'].path.join(),
                    'wb'
                )

**Comment by eLBati** [comment]
@mpdevilleres thanks. Could you open a PR to fix this?
