### ISSUE TITLE
[10.0 , 9.0]mass_editing: removing a value of a many2many field with mass_editing button delete all values ...

### ISSUE THREAD

**Issue by Troublicious** [OCA/server-tools#959]
Hi all,
a big problem exists with the mass_editing module : when removing a value from a many2many field (eg tags) which contains multiple values with a mass editing button, all the values are deleted !
This is absolutely not the expected behaviour, only the chosen value should be removed ...
(the Add and Set choices are working correctly)
Example:
add tags Distributor, Partner, Employee on a contact
with a mass editing button, remove Distributor
result: no more tags on the partner
expected: Partner and Employee tags should still be present!

This can be tested on v9 runbot, but the same happens in v10 => https://runbot.odoo-community.org/runbot/149/9.0

**Comment by taifu** [comment]
I confirm this is a HUGE bug!

**Comment by MLauri** [comment]
+1

**Comment by rafaelbn** [comment]
Hello @Troublicious @taifu @MLauri ,

Maybe you could review functionaly this PR? This PR merge should improve and fix some issues

PRs:

- [x] https://github.com/OCA/server-tools/pull/848
- [ ] https://github.com/OCA/server-tools/pull/849 
- [ ] https://github.com/OCA/server-tools/pull/786 

Thanks
