### ISSUE TITLE
[9.0] auditlog - log_id on table auditlog_log_line is missing an index

### ISSUE THREAD

**Issue by vcloud9ray** [OCA/server-tools#974]
In cases where a large number (more than 100,000 ***) of audit entries are in the system, a simple DELETE query on AUDITLOG_LOG may not finish in any reasonable amount of time.

This is because there is a FK relationship (auditlog.log is related to auditlog.log.line via line_ids using the log_id field) between AUDITLOG_LOG and AUDITLOG_LOG_LINE and PostgreSQL needs to lookup log_id to delete the corresponding entries from AUDITLOG_LOG_LINE.

On any database with a decent amount of rows, the following SQL will illustrate this:

EXPLAIN ANALYZE DELETE FROM AUDITLOG_LOG WHERE ID < 100;

This returned over 800,000 milliseconds (over THIRTEEN MINUTES to delete 100 records) for me on a production database.

*** 90 days of audit logs on a database I am currently supporting amounts to 1.3 million rows in AUDITLOG_LOG and 7.2 million rows in AUDITLOG_LOG_LINE.

To fix, log_id needs be indexed on the auditlog.log.line model (index=True in field definition).

**Comment by sebalix** [comment]
Hi,
It's weird, this index already exists in the 9.0 version of `auditlog`:
https://github.com/OCA/server-tools/blob/9.0/auditlog/models/log.py#L39

As this fix has been introduced later on the branch 8.0, are you sure you do not use an old 8.0 version on your 9.0 instance?

**Comment by raycarnes** [comment]
Hmm.  Git tells me this is a 9.0 branch with HEAD of 1e935c0028dca77f67a92d00428c6354978e7326

Good to know it has been addressed.  You can close.

**Comment by vcloud9ray** [comment]
Hmm. Git tells me this is a 9.0 branch with HEAD of 1e935c0028dca77f67a92d00428c6354978e7326

Good to know it has been addressed. You can close.
