### ISSUE TITLE
[Master] [Code Sprint] disable odoo online

### ISSUE THREAD

**Issue by gdgellatly** [OCA/server-tools#975]
Uninstallable, the upload_data_thread code has been completely removed.  Didn't find the exact commit but appears its moved nowhere.  Anyway, disabling this module is enough for rest of V10 server-tools to at least load without error.

**Comment by lasley** [comment]
@gdgellatly - 10.0 build is passing [on Travis](https://travis-ci.org/OCA/server-tools/builds/272736656) and the [`upload_data_thread`](https://github.com/odoo/odoo/blob/0fff391c381c58d60a9141464226741cc4df6ae6/odoo/tools/misc.py#L815) code still exists in 10.0. Am I misunderstanding something?

**Comment by lasley** [comment]
Are you maybe referring to master? This method is removed in master.

**Comment by gdgellatly** [comment]
@lasley yeah sorry, not sure what to do for these cases.  I want people to know what changes are needed for v11 as I come across them, to save some time, but don't want to clutter issues and PR's.

**Comment by pedrobaeza** [comment]
OK, we can keep this issue opened until the 11.0 branch creation and take it into account then.

**Comment by gdgellatly** [comment]
I imagine we resolved this

**Comment by pedrobaeza** [comment]
Yes!
