### ISSUE TITLE
[RFC][ir.cron] Define mutually exclusive crons

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/server-tools#984]
We have a requirement to run multiple cron jobs that update the same set of records, but each cron being run at different frequency.  We want to make sure that they won't overlap causing concurrency errors.

For example:
* A daily cron job updates field X of the `stock.warehouse.orderpoint`
* An hourly cron job updates field Y of the same model

This will, sooner or later, end up with concurrency errors.

We are considering to introduce to `ir.cron a` `many2many` field `multually_exclusive_cron_ids`.

When the cron is to be scheduled, it first check if any of the `multually_exclusive_cron_ids` is currently being run. If that is the case, the cron will not start, and will re-attempt to run, until the other crons jobs have finished.

**Comment by LoisRForgeFlow** [comment]
PR addressing this issue created: https://github.com/OCA/server-tools/pull/999

**Comment by LoisRForgeFlow** [comment]
This can be closed.
