### ISSUE TITLE
auth_admin_passkey v10 missing in wheelhouse

### ISSUE THREAD

**Issue by codingforfun** [OCA/server-tools#987]
Not sure where is the best place to report this. 
I noticed that module `auth_admin_passkey` is missing in the [wheelhouse](https://wheelhouse.odoo-community.org/oca-simple) for v10 , although already ported to v10.
I tried locally if I can build it to check if somethings wrong with the setup, but it went fine. 
I could build `odoo10_addon_auth_admin_passkey-10.0.1.0.0.99.dev2-py2-none-any.whl` without any changes necessary, so still wondering why it is not included in the nightly build. 

@sbidoul Maybe you know where to look at this?

**Comment by sbidoul** [comment]
The nightly build scripts were partially failing silently since a few weeks. This should be resolved now.

BTW, note you can use [pypi](https://pypi.python.org/pypi/odoo10-addon-auth-admin-passkey/10.0.1.0.0.99.dev2) too.

**Comment by codingforfun** [comment]
THX
